/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RootEmbeddedApi);
  }
}(this, function(expect, RootEmbeddedApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RootEmbeddedApi.PolicyApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PolicyApi', function() {
    describe('createQuoteFromPolicy', function() {
      it('should call createQuoteFromPolicy successfully', function(done) {
        //uncomment below and update the code to test createQuoteFromPolicy
        //instance.createQuoteFromPolicy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPolicy', function() {
      it('should call getPolicy successfully', function(done) {
        //uncomment below and update the code to test getPolicy
        //instance.getPolicy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPolicyDocuments', function() {
      it('should call getPolicyDocuments successfully', function(done) {
        //uncomment below and update the code to test getPolicyDocuments
        //instance.getPolicyDocuments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPolicyPayment', function() {
      it('should call getPolicyPayment successfully', function(done) {
        //uncomment below and update the code to test getPolicyPayment
        //instance.getPolicyPayment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPolicyQuote', function() {
      it('should call getPolicyQuote successfully', function(done) {
        //uncomment below and update the code to test getPolicyQuote
        //instance.getPolicyQuote(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
