/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RootEmbeddedApi);
  }
}(this, function(expect, RootEmbeddedApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RootEmbeddedApi.QuotingApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QuotingApi', function() {
    describe('createQuote', function() {
      it('should call createQuote successfully', function(done) {
        //uncomment below and update the code to test createQuote
        //instance.createQuote(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAvailableCoveragesByQuoteId', function() {
      it('should call getAvailableCoveragesByQuoteId successfully', function(done) {
        //uncomment below and update the code to test getAvailableCoveragesByQuoteId
        //instance.getAvailableCoveragesByQuoteId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAvailableCoveragesByState', function() {
      it('should call getAvailableCoveragesByState successfully', function(done) {
        //uncomment below and update the code to test getAvailableCoveragesByState
        //instance.getAvailableCoveragesByState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCoverageRulesByQuoteId', function() {
      it('should call getCoverageRulesByQuoteId successfully', function(done) {
        //uncomment below and update the code to test getCoverageRulesByQuoteId
        //instance.getCoverageRulesByQuoteId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCoverageRulesByState', function() {
      it('should call getCoverageRulesByState successfully', function(done) {
        //uncomment below and update the code to test getCoverageRulesByState
        //instance.getCoverageRulesByState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getQuote', function() {
      it('should call getQuote successfully', function(done) {
        //uncomment below and update the code to test getQuote
        //instance.getQuote(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSuggestedCoverages', function() {
      it('should call getSuggestedCoverages successfully', function(done) {
        //uncomment below and update the code to test getSuggestedCoverages
        //instance.getSuggestedCoverages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchQuote', function() {
      it('should call patchQuote successfully', function(done) {
        //uncomment below and update the code to test patchQuote
        //instance.patchQuote(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBindQuote', function() {
      it('should call postBindQuote successfully', function(done) {
        //uncomment below and update the code to test postBindQuote
        //instance.postBindQuote(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postFinalizeQuote', function() {
      it('should call postFinalizeQuote successfully', function(done) {
        //uncomment below and update the code to test postFinalizeQuote
        //instance.postFinalizeQuote(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postViewQuote', function() {
      it('should call postViewQuote successfully', function(done) {
        //uncomment below and update the code to test postViewQuote
        //instance.postViewQuote(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateQuote', function() {
      it('should call updateQuote successfully', function(done) {
        //uncomment below and update the code to test updateQuote
        //instance.updateQuote(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
