/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RootEmbeddedApi);
  }
}(this, function(expect, RootEmbeddedApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RootEmbeddedApi.AvailableCoverageAttributeSelectionsInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AvailableCoverageAttributeSelectionsInner', function() {
    it('should create an instance of AvailableCoverageAttributeSelectionsInner', function() {
      // uncomment below and update the code to test AvailableCoverageAttributeSelectionsInner
      //var instance = new RootEmbeddedApi.AvailableCoverageAttributeSelectionsInner();
      //expect(instance).to.be.a(RootEmbeddedApi.AvailableCoverageAttributeSelectionsInner);
    });

    it('should have the property declined (base name: "declined")', function() {
      // uncomment below and update the code to test the property declined
      //var instance = new RootEmbeddedApi.AvailableCoverageAttributeSelectionsInner();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new RootEmbeddedApi.AvailableCoverageAttributeSelectionsInner();
      //expect(instance).to.be();
    });

    it('should have the property longDescription (base name: "longDescription")', function() {
      // uncomment below and update the code to test the property longDescription
      //var instance = new RootEmbeddedApi.AvailableCoverageAttributeSelectionsInner();
      //expect(instance).to.be();
    });

    it('should have the property deductible (base name: "deductible")', function() {
      // uncomment below and update the code to test the property deductible
      //var instance = new RootEmbeddedApi.AvailableCoverageAttributeSelectionsInner();
      //expect(instance).to.be();
    });

    it('should have the property perDay (base name: "perDay")', function() {
      // uncomment below and update the code to test the property perDay
      //var instance = new RootEmbeddedApi.AvailableCoverageAttributeSelectionsInner();
      //expect(instance).to.be();
    });

    it('should have the property perTimePeriod (base name: "perTimePeriod")', function() {
      // uncomment below and update the code to test the property perTimePeriod
      //var instance = new RootEmbeddedApi.AvailableCoverageAttributeSelectionsInner();
      //expect(instance).to.be();
    });

    it('should have the property perOccurrence (base name: "perOccurrence")', function() {
      // uncomment below and update the code to test the property perOccurrence
      //var instance = new RootEmbeddedApi.AvailableCoverageAttributeSelectionsInner();
      //expect(instance).to.be();
    });

    it('should have the property perPerson (base name: "perPerson")', function() {
      // uncomment below and update the code to test the property perPerson
      //var instance = new RootEmbeddedApi.AvailableCoverageAttributeSelectionsInner();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new RootEmbeddedApi.AvailableCoverageAttributeSelectionsInner();
      //expect(instance).to.be();
    });

  });

}));
