/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RootEmbeddedApi);
  }
}(this, function(expect, RootEmbeddedApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RootEmbeddedApi.AvailableCoverageAttribute();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AvailableCoverageAttribute', function() {
    it('should create an instance of AvailableCoverageAttribute', function() {
      // uncomment below and update the code to test AvailableCoverageAttribute
      //var instance = new RootEmbeddedApi.AvailableCoverageAttribute();
      //expect(instance).to.be.a(RootEmbeddedApi.AvailableCoverageAttribute);
    });

    it('should have the property kind (base name: "kind")', function() {
      // uncomment below and update the code to test the property kind
      //var instance = new RootEmbeddedApi.AvailableCoverageAttribute();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new RootEmbeddedApi.AvailableCoverageAttribute();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new RootEmbeddedApi.AvailableCoverageAttribute();
      //expect(instance).to.be();
    });

    it('should have the property longDescription (base name: "longDescription")', function() {
      // uncomment below and update the code to test the property longDescription
      //var instance = new RootEmbeddedApi.AvailableCoverageAttribute();
      //expect(instance).to.be();
    });

    it('should have the property selectableBy (base name: "selectableBy")', function() {
      // uncomment below and update the code to test the property selectableBy
      //var instance = new RootEmbeddedApi.AvailableCoverageAttribute();
      //expect(instance).to.be();
    });

    it('should have the property selections (base name: "selections")', function() {
      // uncomment below and update the code to test the property selections
      //var instance = new RootEmbeddedApi.AvailableCoverageAttribute();
      //expect(instance).to.be();
    });

  });

}));
