/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RootEmbeddedApi);
  }
}(this, function(expect, RootEmbeddedApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RootEmbeddedApi.PrefillDriver();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PrefillDriver', function() {
    it('should create an instance of PrefillDriver', function() {
      // uncomment below and update the code to test PrefillDriver
      //var instance = new RootEmbeddedApi.PrefillDriver();
      //expect(instance).to.be.a(RootEmbeddedApi.PrefillDriver);
    });

    it('should have the property dob (base name: "dob")', function() {
      // uncomment below and update the code to test the property dob
      //var instance = new RootEmbeddedApi.PrefillDriver();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "firstName")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new RootEmbeddedApi.PrefillDriver();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new RootEmbeddedApi.PrefillDriver();
      //expect(instance).to.be();
    });

    it('should have the property isDenylistedDriver (base name: "isDenylistedDriver")', function() {
      // uncomment below and update the code to test the property isDenylistedDriver
      //var instance = new RootEmbeddedApi.PrefillDriver();
      //expect(instance).to.be();
    });

    it('should have the property isRequestedDriver (base name: "isRequestedDriver")', function() {
      // uncomment below and update the code to test the property isRequestedDriver
      //var instance = new RootEmbeddedApi.PrefillDriver();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "lastName")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new RootEmbeddedApi.PrefillDriver();
      //expect(instance).to.be();
    });

    it('should have the property licenseNumber (base name: "licenseNumber")', function() {
      // uncomment below and update the code to test the property licenseNumber
      //var instance = new RootEmbeddedApi.PrefillDriver();
      //expect(instance).to.be();
    });

    it('should have the property licenseState (base name: "licenseState")', function() {
      // uncomment below and update the code to test the property licenseState
      //var instance = new RootEmbeddedApi.PrefillDriver();
      //expect(instance).to.be();
    });

    it('should have the property prefillReportIdentifiers (base name: "prefillReportIdentifiers")', function() {
      // uncomment below and update the code to test the property prefillReportIdentifiers
      //var instance = new RootEmbeddedApi.PrefillDriver();
      //expect(instance).to.be();
    });

  });

}));
