/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RootEmbeddedApi);
  }
}(this, function(expect, RootEmbeddedApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RootEmbeddedApi.SuggestedCoverages();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SuggestedCoverages', function() {
    it('should create an instance of SuggestedCoverages', function() {
      // uncomment below and update the code to test SuggestedCoverages
      //var instance = new RootEmbeddedApi.SuggestedCoverages();
      //expect(instance).to.be.a(RootEmbeddedApi.SuggestedCoverages);
    });

    it('should have the property coverages (base name: "coverages")', function() {
      // uncomment below and update the code to test the property coverages
      //var instance = new RootEmbeddedApi.SuggestedCoverages();
      //expect(instance).to.be();
    });

    it('should have the property _default (base name: "default")', function() {
      // uncomment below and update the code to test the property _default
      //var instance = new RootEmbeddedApi.SuggestedCoverages();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new RootEmbeddedApi.SuggestedCoverages();
      //expect(instance).to.be();
    });

    it('should have the property derivedFromPriorCoverage (base name: "derivedFromPriorCoverage")', function() {
      // uncomment below and update the code to test the property derivedFromPriorCoverage
      //var instance = new RootEmbeddedApi.SuggestedCoverages();
      //expect(instance).to.be();
    });

    it('should have the property fullTermPayment (base name: "fullTermPayment")', function() {
      // uncomment below and update the code to test the property fullTermPayment
      //var instance = new RootEmbeddedApi.SuggestedCoverages();
      //expect(instance).to.be();
    });

    it('should have the property monthlyTermPayments (base name: "monthlyTermPayments")', function() {
      // uncomment below and update the code to test the property monthlyTermPayments
      //var instance = new RootEmbeddedApi.SuggestedCoverages();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new RootEmbeddedApi.SuggestedCoverages();
      //expect(instance).to.be();
    });

    it('should have the property priority (base name: "priority")', function() {
      // uncomment below and update the code to test the property priority
      //var instance = new RootEmbeddedApi.SuggestedCoverages();
      //expect(instance).to.be();
    });

  });

}));
