/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RootEmbeddedApi);
  }
}(this, function(expect, RootEmbeddedApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RootEmbeddedApi.Vehicle();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Vehicle', function() {
    it('should create an instance of Vehicle', function() {
      // uncomment below and update the code to test Vehicle
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be.a(RootEmbeddedApi.Vehicle);
    });

    it('should have the property annualizedMileage (base name: "annualizedMileage")', function() {
      // uncomment below and update the code to test the property annualizedMileage
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property antiTheftEquipment (base name: "antiTheftEquipment")', function() {
      // uncomment below and update the code to test the property antiTheftEquipment
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property commuteDistance (base name: "commuteDistance")', function() {
      // uncomment below and update the code to test the property commuteDistance
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property garagingAddress1 (base name: "garagingAddress1")', function() {
      // uncomment below and update the code to test the property garagingAddress1
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property garagingAddress2 (base name: "garagingAddress2")', function() {
      // uncomment below and update the code to test the property garagingAddress2
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property garagingCity (base name: "garagingCity")', function() {
      // uncomment below and update the code to test the property garagingCity
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property garagingState (base name: "garagingState")', function() {
      // uncomment below and update the code to test the property garagingState
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property garagingZip (base name: "garagingZip")', function() {
      // uncomment below and update the code to test the property garagingZip
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property make (base name: "make")', function() {
      // uncomment below and update the code to test the property make
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property model (base name: "model")', function() {
      // uncomment below and update the code to test the property model
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property primaryUsage (base name: "primaryUsage")', function() {
      // uncomment below and update the code to test the property primaryUsage
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property purchaseDate (base name: "purchaseDate")', function() {
      // uncomment below and update the code to test the property purchaseDate
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property underwritingRequirements (base name: "underwritingRequirements")', function() {
      // uncomment below and update the code to test the property underwritingRequirements
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property vin (base name: "vin")', function() {
      // uncomment below and update the code to test the property vin
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property vinEtching (base name: "vinEtching")', function() {
      // uncomment below and update the code to test the property vinEtching
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property year (base name: "year")', function() {
      // uncomment below and update the code to test the property year
      //var instance = new RootEmbeddedApi.Vehicle();
      //expect(instance).to.be();
    });

  });

}));
