/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateBraintreeClientToken201Response from '../model/CreateBraintreeClientToken201Response';
import CreateQuoteFromPolicy422Response from '../model/CreateQuoteFromPolicy422Response';
import GetAgencyAgents401Response from '../model/GetAgencyAgents401Response';
import GetBraintreeCustomer200Response from '../model/GetBraintreeCustomer200Response';
import GetLegalDocuments500Response from '../model/GetLegalDocuments500Response';
import GetPolicy404Response from '../model/GetPolicy404Response';

/**
* BraintreePayments service.
* @module api/BraintreePaymentsApi
* @version 3.0.0
*/
export default class BraintreePaymentsApi {

    /**
    * Constructs a new BraintreePaymentsApi. 
    * @alias module:api/BraintreePaymentsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Create Braintree client token
     * Generate a Braintree client token. The client token will be used to initialize the Braintree client SDK for purchasing an auto policy with the quote. Please, refer to https://developer.paypal.com/braintree/docs/guides/authorization/client-token for more information.
     * @param {String} quoteId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CreateBraintreeClientToken201Response} and HTTP response
     */
    createBraintreeClientTokenWithHttpInfo(quoteId) {
      let postBody = null;
      // verify the required parameter 'quoteId' is set
      if (quoteId === undefined || quoteId === null) {
        throw new Error("Missing the required parameter 'quoteId' when calling createBraintreeClientToken");
      }

      let pathParams = {
        'quote_id': quoteId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['agency_access_token', 'legacy_api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CreateBraintreeClientToken201Response;
      return this.apiClient.callApi(
        '/v3/quoting/quote/{quote_id}/payment/braintree/client_token', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create Braintree client token
     * Generate a Braintree client token. The client token will be used to initialize the Braintree client SDK for purchasing an auto policy with the quote. Please, refer to https://developer.paypal.com/braintree/docs/guides/authorization/client-token for more information.
     * @param {String} quoteId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CreateBraintreeClientToken201Response}
     */
    createBraintreeClientToken(quoteId) {
      return this.createBraintreeClientTokenWithHttpInfo(quoteId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Braintree customer
     * Attempt to retrieve a user's Braintree customer ID. This may be utilized with pre-authorization from Root to support server-to-server payments.
     * @param {String} quoteId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetBraintreeCustomer200Response} and HTTP response
     */
    getBraintreeCustomerWithHttpInfo(quoteId) {
      let postBody = null;
      // verify the required parameter 'quoteId' is set
      if (quoteId === undefined || quoteId === null) {
        throw new Error("Missing the required parameter 'quoteId' when calling getBraintreeCustomer");
      }

      let pathParams = {
        'quote_id': quoteId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['agency_access_token', 'legacy_api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetBraintreeCustomer200Response;
      return this.apiClient.callApi(
        '/v3/quoting/quote/{quote_id}/payment/braintree/customer', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Braintree customer
     * Attempt to retrieve a user's Braintree customer ID. This may be utilized with pre-authorization from Root to support server-to-server payments.
     * @param {String} quoteId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetBraintreeCustomer200Response}
     */
    getBraintreeCustomer(quoteId) {
      return this.getBraintreeCustomerWithHttpInfo(quoteId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
