/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AuthenticateBridgeLink400Response from '../model/AuthenticateBridgeLink400Response';
import CreatePrefill422Response from '../model/CreatePrefill422Response';
import CreatePrefillRequest from '../model/CreatePrefillRequest';
import GetAgencyAgents401Response from '../model/GetAgencyAgents401Response';
import GetLegalDocuments500Response from '../model/GetLegalDocuments500Response';
import GetPolicy404Response from '../model/GetPolicy404Response';
import GetPrefill200Response from '../model/GetPrefill200Response';

/**
* Prefill service.
* @module api/PrefillApi
* @version 3.0.0
*/
export default class PrefillApi {

    /**
    * Constructs a new PrefillApi. 
    * @alias module:api/PrefillApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Create prefill report
     * Create a prefill report request associated with the provided quote. Data for the prefill uses the request body instead of data associated with the quote. After the prefill report is created, the associated prefill drivers will be automatically added to the quote with a status of Undecided. The quote will remain unbindable until the status for these drivers is set to either Covered or Excluded.
     * @param {String} quoteId 
     * @param {Object} opts Optional parameters
     * @param {module:model/CreatePrefillRequest} [createPrefillRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    createPrefillWithHttpInfo(quoteId, opts) {
      opts = opts || {};
      let postBody = opts['createPrefillRequest'];
      // verify the required parameter 'quoteId' is set
      if (quoteId === undefined || quoteId === null) {
        throw new Error("Missing the required parameter 'quoteId' when calling createPrefill");
      }

      let pathParams = {
        'quote_id': quoteId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['agency_access_token', 'legacy_api_key'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/v3/quoting/quote/{quote_id}/prefill', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create prefill report
     * Create a prefill report request associated with the provided quote. Data for the prefill uses the request body instead of data associated with the quote. After the prefill report is created, the associated prefill drivers will be automatically added to the quote with a status of Undecided. The quote will remain unbindable until the status for these drivers is set to either Covered or Excluded.
     * @param {String} quoteId 
     * @param {Object} opts Optional parameters
     * @param {module:model/CreatePrefillRequest} opts.createPrefillRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    createPrefill(quoteId, opts) {
      return this.createPrefillWithHttpInfo(quoteId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get prefill report
     * Attempt to retrieve a prefill report. The associated quote must exist and a prefill request must have been previously created on /v3/quoting/quote/{quote_id}/prefill in order to receive a success response. This operation is async and it is recommended to be polled until completion. This operation can take up to 35 seconds to complete.
     * @param {String} quoteId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetPrefill200Response} and HTTP response
     */
    getPrefillWithHttpInfo(quoteId) {
      let postBody = null;
      // verify the required parameter 'quoteId' is set
      if (quoteId === undefined || quoteId === null) {
        throw new Error("Missing the required parameter 'quoteId' when calling getPrefill");
      }

      let pathParams = {
        'quote_id': quoteId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['agency_access_token', 'legacy_api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetPrefill200Response;
      return this.apiClient.callApi(
        '/v3/quoting/quote/{quote_id}/prefill', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get prefill report
     * Attempt to retrieve a prefill report. The associated quote must exist and a prefill request must have been previously created on /v3/quoting/quote/{quote_id}/prefill in order to receive a success response. This operation is async and it is recommended to be polled until completion. This operation can take up to 35 seconds to complete.
     * @param {String} quoteId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetPrefill200Response}
     */
    getPrefill(quoteId) {
      return this.getPrefillWithHttpInfo(quoteId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
