/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetAgencyAgents401Response from '../model/GetAgencyAgents401Response';
import GetYearMakeModel200Response from '../model/GetYearMakeModel200Response';

/**
* YearMakeModel service.
* @module api/YearMakeModelApi
* @version 3.0.0
*/
export default class YearMakeModelApi {

    /**
    * Constructs a new YearMakeModelApi. 
    * @alias module:api/YearMakeModelApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get YearMakeModel
     * Get the YearMakeModel associated with the provided vin.
     * @param {String} vin The vin to get the YearMakeModel for.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetYearMakeModel200Response} and HTTP response
     */
    getYearMakeModelWithHttpInfo(vin) {
      let postBody = null;
      // verify the required parameter 'vin' is set
      if (vin === undefined || vin === null) {
        throw new Error("Missing the required parameter 'vin' when calling getYearMakeModel");
      }

      let pathParams = {
        'vin': vin
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['agency_access_token', 'legacy_api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetYearMakeModel200Response;
      return this.apiClient.callApi(
        '/v3/ymm_for_vin/{vin}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get YearMakeModel
     * Get the YearMakeModel associated with the provided vin.
     * @param {String} vin The vin to get the YearMakeModel for.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetYearMakeModel200Response}
     */
    getYearMakeModel(vin) {
      return this.getYearMakeModelWithHttpInfo(vin)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
