
import React, { useState, useMemo, useEffect } from 'react';
import { useData } from '../../context/DataContext';
import { Client, ProductType, UserRole } from '../../types';
import { Search, Filter, Download, Edit2, X, Mail, Phone, Shield } from 'lucide-react';
import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';

export const Clients: React.FC = () => {
  const { clients, updateClient, user } = useData();
  const [searchTerm, setSearchTerm] = useState('');
  const [productFilter, setProductFilter] = useState<string>('All');
  const [currentTime, setCurrentTime] = useState(new Date());
  
  // Edit State
  const [editingClient, setEditingClient] = useState<Client | null>(null);
  const [editForm, setEditForm] = useState<Partial<Client>>({});

  // Auto-update clock for "real-time" feel
  useEffect(() => {
    const timer = setInterval(() => setCurrentTime(new Date()), 1000);
    return () => clearInterval(timer);
  }, []);

  const filteredClients = useMemo(() => {
    let result = clients;
    
    if (user?.role === UserRole.ADVISOR && user.productsSold) {
        result = result.filter(c => user.productsSold!.includes(c.product));
    }

    if (productFilter !== 'All') {
        result = result.filter(c => c.product === productFilter);
    }

    if (searchTerm) {
        const lower = searchTerm.toLowerCase();
        result = result.filter(c => 
            c.name.toLowerCase().includes(lower) || 
            c.policyNumber.toLowerCase().includes(lower) ||
            (c.email && c.email.toLowerCase().includes(lower))
        );
    }
    
    return result;
  }, [clients, user, productFilter, searchTerm]);

  const handleEdit = (client: Client) => {
      setEditingClient(client);
      setEditForm({...client});
  };

  const handleSave = (e: React.FormEvent) => {
      e.preventDefault();
      if (editingClient && editForm) {
          updateClient(editingClient.id, editForm);
          setEditingClient(null);
      }
  };

  const getStatusText = (renewalDate: string) => {
      const today = new Date();
      const renewal = new Date(renewalDate);
      const diffTime = renewal.getTime() - today.getTime();
      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

      if (diffDays < 0) return 'Expired';
      if (diffDays < 30) return 'Renewing Soon';
      return 'Active';
  };

  const generatePDF = () => {
    const doc = new jsPDF({ orientation: 'landscape' });
    
    // Add Company Logo (Golden Cards)
    const logoX = 14;
    const logoY = 10;
    
    // Back Card (Darker Amber)
    doc.setFillColor(245, 158, 11); // #F59E0B
    doc.roundedRect(logoX, logoY, 9, 6, 1, 1, 'F'); 
    
    // Front Card (Lighter Amber)
    doc.setFillColor(252, 211, 77); // #FCD34D
    doc.roundedRect(logoX + 0.5, logoY + 2, 8, 5.5, 1, 1, 'F');
    
    // Chip (Dark Amber)
    doc.setFillColor(180, 83, 9); // #B45309
    doc.roundedRect(logoX + 3.7, logoY + 3.7, 1.6, 2.2, 0.4, 0.4, 'F');

    doc.setFontSize(22);
    doc.setTextColor(11, 34, 64); // NHFG Dark Blue
    doc.setFont("helvetica", "bold");
    doc.text("NEW HOLLAND", logoX + 11, logoY + 5);
    
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text("FINANCIAL GROUP", logoX + 11, logoY + 8);

    doc.setFontSize(14);
    doc.setTextColor(11, 34, 64);
    doc.text("Client Portfolio Report", 14, 30);
    
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated by: ${user?.name || 'NHFG Advisor'}`, 14, 38);
    doc.text(`Report Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 14, 43);
    doc.text(`Copyright © ${new Date().getFullYear()} New Holland Financial Group. All Rights Reserved.`, 14, 48);

    const tableColumn = ["Client Name", "Email", "Phone", "Product", "Policy #", "Carrier", "Premium", "Status", "Renewal"];
    const tableRows: any[] = [];

    filteredClients.forEach(client => {
      const clientData = [
        client.name,
        client.email || 'N/A',
        client.phone || 'N/A',
        client.product,
        client.policyNumber,
        client.carrier || 'N/A',
        `$${client.premium.toLocaleString()}`,
        getStatusText(client.renewalDate),
        new Date(client.renewalDate).toLocaleDateString(),
      ];
      tableRows.push(clientData);
    });

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 55,
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [11, 34, 64], textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });

    doc.save(`NHFG_Portfolio_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <div className="space-y-8 pb-10">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div>
                <h1 className="text-4xl font-black text-[#0B2240] tracking-tight">Client Management</h1>
                <p className="text-slate-500 font-bold mt-1 uppercase tracking-wider text-xs">Monitor policies and renewal cycles.</p>
            </div>
            <button 
                onClick={generatePDF}
                className="bg-white border border-blue-200 text-blue-600 px-8 py-3.5 rounded-2xl font-black text-[11px] hover:bg-blue-50 shadow-xl shadow-blue-900/5 transition-all flex items-center gap-2 transform active:scale-95 uppercase tracking-[0.15em]"
            >
                <Download className="h-4 w-4" /> Export Portfolio
            </button>
        </div>

        <div className="bg-white rounded-[3.5rem] shadow-2xl border border-slate-100 overflow-hidden min-h-[600px] flex flex-col">
            {/* Search Filters */}
            <div className="p-10 pb-4 border-b border-slate-50 flex flex-col md:flex-row gap-6">
                <div className="relative flex-1">
                    <div className="absolute left-6 top-1/2 -translate-y-1/2 flex items-center gap-4 pointer-events-none text-slate-300">
                        <Search className="h-5 w-5" />
                        <span className="w-px h-6 bg-slate-100"></span>
                    </div>
                    <input 
                        type="text" 
                        placeholder="Search by name, policy or email..." 
                        value={searchTerm}
                        onChange={e => setSearchTerm(e.target.value)}
                        className="w-full pl-20 pr-8 py-6 bg-slate-50 border-none rounded-[2rem] text-sm font-bold focus:ring-0 outline-none text-slate-900 shadow-inner transition-all placeholder:text-slate-300"
                    />
                </div>
                <div className="relative min-w-[240px]">
                    <div className="absolute left-6 top-1/2 -translate-y-1/2 flex items-center gap-4 pointer-events-none text-slate-300">
                        <Filter className="h-5 w-5" />
                        <span className="w-px h-6 bg-slate-100"></span>
                    </div>
                    <select 
                        className="w-full pl-20 pr-10 py-6 bg-slate-50 border-none rounded-[2rem] text-xs font-black uppercase tracking-widest focus:ring-0 appearance-none cursor-pointer shadow-inner text-slate-700"
                        value={productFilter}
                        onChange={e => setProductFilter(e.target.value)}
                    >
                        <option value="All">All Categories</option>
                        {Object.values(ProductType).map(p => <option key={p} value={p}>{p}</option>)}
                    </select>
                </div>
            </div>

            <div className="flex-1 overflow-x-auto px-4 pb-10">
                <table className="w-full text-left">
                    <thead className="text-[10px] uppercase font-black tracking-[0.25em]">
                        <tr>
                            <th className="px-8 py-6 bg-slate-50 text-slate-400 rounded-l-3xl">Client Name</th>
                            <th className="px-8 py-6 bg-blue-50 text-blue-400">Policy Info</th>
                            <th className="px-8 py-6 bg-indigo-50 text-indigo-400">Premium</th>
                            <th className="px-8 py-6 bg-amber-50 text-amber-400">Status</th>
                            <th className="px-8 py-6 bg-emerald-50 text-emerald-400">Contact</th>
                            <th className="px-8 py-6 bg-purple-50 text-purple-400 rounded-r-3xl">Carrier</th>
                        </tr>
                    </thead>
                    <tbody>
                        {filteredClients.map(client => (
                            <tr key={client.id} className="group hover:bg-slate-50/50 transition-all cursor-pointer border-b border-slate-50">
                                <td className="px-8 py-8" onClick={() => handleEdit(client)}>
                                    <div className="font-black text-[#0B2240] text-sm">{client.name}</div>
                                    <div className="text-[10px] text-slate-300 font-black mt-1 uppercase tracking-tighter">Account Registered</div>
                                </td>
                                <td className="px-8 py-8" onClick={() => handleEdit(client)}>
                                    <div className="font-bold text-slate-600 text-xs">{client.product}</div>
                                    <div className="text-[10px] text-blue-500 font-mono mt-1 font-black">{client.policyNumber}</div>
                                </td>
                                <td className="px-8 py-8 font-mono font-black text-slate-700" onClick={() => handleEdit(client)}>
                                    ${client.premium.toLocaleString()}
                                </td>
                                <td className="px-8 py-8" onClick={() => handleEdit(client)}>
                                    <span className={`px-4 py-1.5 rounded-xl text-[9px] font-black uppercase tracking-widest ${
                                        getStatusText(client.renewalDate) === 'Active' ? 'bg-green-100 text-green-700' : 
                                        getStatusText(client.renewalDate) === 'Expired' ? 'bg-red-100 text-red-700' : 
                                        'bg-orange-100 text-orange-700'
                                    }`}>
                                        {getStatusText(client.renewalDate)}
                                    </span>
                                </td>
                                <td className="px-8 py-8">
                                    <div className="flex gap-2">
                                        {client.email && (
                                            <a href={`mailto:${client.email}`} className="p-2.5 bg-white border border-slate-100 text-slate-400 rounded-xl hover:text-blue-500 hover:border-blue-100 transition-all shadow-sm">
                                                <Mail className="h-4 w-4" />
                                            </a>
                                        )}
                                        {client.phone && (
                                            <a href={`tel:${client.phone}`} className="p-2.5 bg-white border border-slate-100 text-slate-400 rounded-xl hover:text-blue-500 hover:border-blue-100 transition-all shadow-sm">
                                                <Phone className="h-4 w-4" />
                                            </a>
                                        )}
                                    </div>
                                </td>
                                <td className="px-8 py-8 text-[11px] font-black text-slate-400 uppercase tracking-widest">
                                    {client.carrier || 'Pending'}
                                </td>
                            </tr>
                        ))}
                        {filteredClients.length === 0 && (
                            <tr>
                                <td colSpan={6} className="px-10 py-48 text-center">
                                    <div className="flex flex-col items-center justify-center opacity-10">
                                        <Shield className="h-32 w-32 mb-6" strokeWidth={1} />
                                        <h2 className="text-4xl font-black uppercase tracking-[0.4em]">Database Empty</h2>
                                    </div>
                                </td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>

            {/* SYNC INDICATOR */}
            <div className="p-6 border-t border-slate-50 flex items-center justify-center gap-4 opacity-50">
                <div className="flex items-center gap-2">
                    <span className="h-2 w-2 bg-green-500 rounded-full animate-pulse"></span>
                    <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Terminal Synced</span>
                </div>
                <span className="text-slate-200">|</span>
                <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{currentTime.toLocaleTimeString()}</span>
            </div>
        </div>

        {/* Edit Modal */}
        {editingClient && (
            <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#0B2240]/70 backdrop-blur-xl p-6 animate-fade-in">
                <div className="bg-white rounded-[3.5rem] shadow-2xl w-full max-w-2xl p-12 relative max-h-[90vh] overflow-y-auto border border-white/20">
                    <div className="flex justify-between items-center mb-10">
                        <div className="flex items-center gap-5">
                            <div className="p-5 bg-blue-600 text-white rounded-[1.5rem] shadow-xl shadow-blue-600/20">
                                <Edit2 className="h-8 w-8" />
                            </div>
                            <div>
                                <h2 className="text-3xl font-black text-[#0B2240] tracking-tight">Edit Client Account</h2>
                                <p className="text-slate-400 font-bold uppercase text-[10px] tracking-widest mt-1">Advisor Administrative Console</p>
                            </div>
                        </div>
                        <button onClick={() => setEditingClient(null)} className="p-4 hover:bg-slate-100 rounded-full transition-colors"><X className="h-8 w-8 text-slate-300" /></button>
                    </div>
                    
                    <form onSubmit={handleSave} className="space-y-8">
                        {/* Identitiy Block */}
                        <div className="bg-slate-50 p-10 rounded-[2.5rem] border-2 border-slate-100 space-y-8">
                            <h3 className="text-[11px] font-black text-slate-400 uppercase tracking-[0.3em] flex items-center gap-3">
                                <span className="h-1.5 w-1.5 bg-blue-600 rounded-full"></span> 
                                Account Identity
                            </h3>
                            <div>
                                <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Legal Full Name</label>
                                <input 
                                    className="w-full bg-white text-slate-900 border-2 border-slate-100 rounded-2xl px-6 py-5 text-base font-bold focus:ring-4 focus:ring-blue-100 focus:border-blue-600 outline-none shadow-sm transition-all"
                                    value={editForm.name || ''}
                                    onChange={e => setEditForm({...editForm, name: e.target.value})}
                                />
                            </div>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                <div>
                                    <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Email Address</label>
                                    <input 
                                        type="email"
                                        className="w-full bg-white text-slate-900 border-2 border-slate-100 rounded-2xl px-6 py-5 text-base font-bold focus:ring-4 focus:ring-blue-100 focus:border-blue-600 outline-none shadow-sm transition-all"
                                        value={editForm.email || ''}
                                        onChange={e => setEditForm({...editForm, email: e.target.value})}
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Primary Phone</label>
                                    <input 
                                        type="tel"
                                        className="w-full bg-white text-slate-900 border-2 border-slate-100 rounded-2xl px-6 py-5 text-base font-bold focus:ring-4 focus:ring-blue-100 focus:border-blue-600 outline-none shadow-sm transition-all"
                                        value={editForm.phone || ''}
                                        onChange={e => setEditForm({...editForm, phone: e.target.value})}
                                    />
                                </div>
                            </div>
                        </div>

                        {/* Policy Block */}
                        <div className="bg-white p-10 rounded-[2.5rem] border-4 border-blue-50 space-y-8 shadow-sm">
                            <h3 className="text-[11px] font-black text-blue-400 uppercase tracking-[0.3em] flex items-center gap-3">
                                <span className="h-1.5 w-1.5 bg-blue-600 rounded-full"></span> 
                                Policy Administration
                            </h3>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                <div className="md:col-span-2">
                                    <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Master Policy Number</label>
                                    <input 
                                        className="w-full bg-blue-50/30 text-[#0B2240] border-2 border-blue-100 rounded-2xl px-6 py-6 text-2xl font-black font-mono focus:ring-4 focus:ring-blue-200 outline-none transition-all"
                                        value={editForm.policyNumber || ''}
                                        onChange={e => setEditForm({...editForm, policyNumber: e.target.value})}
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Coverage Product</label>
                                    <select 
                                        className="w-full bg-slate-50 text-slate-900 border-2 border-slate-100 rounded-2xl px-6 py-5 text-sm font-black focus:ring-4 focus:ring-blue-100 outline-none appearance-none cursor-pointer"
                                        value={editForm.product}
                                        onChange={e => setEditForm({...editForm, product: e.target.value as ProductType})}
                                    >
                                        {Object.values(ProductType).map(p => <option key={p} value={p}>{p}</option>)}
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Issuing Carrier</label>
                                    <input 
                                        className="w-full bg-slate-50 text-slate-900 border-2 border-slate-100 rounded-2xl px-6 py-5 text-sm font-black focus:ring-4 focus:ring-blue-100 outline-none"
                                        value={editForm.carrier || ''}
                                        onChange={e => setEditForm({...editForm, carrier: e.target.value})}
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Annual Premium ($)</label>
                                    <input 
                                        type="number"
                                        className="w-full bg-slate-50 text-slate-900 border-2 border-slate-100 rounded-2xl px-6 py-5 text-sm font-black focus:ring-4 focus:ring-blue-100 outline-none"
                                        value={editForm.premium || ''}
                                        onChange={e => setEditForm({...editForm, premium: Number(e.target.value)})}
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-black text-slate-500 uppercase mb-3 ml-2">Renewal Date</label>
                                    <input 
                                        type="date"
                                        className="w-full bg-slate-50 text-slate-900 border-2 border-slate-100 rounded-2xl px-6 py-5 text-sm font-black focus:ring-4 focus:ring-blue-100 outline-none"
                                        value={editForm.renewalDate || ''}
                                        onChange={e => setEditForm({...editForm, renewalDate: e.target.value})}
                                    />
                                </div>
                            </div>
                        </div>

                        <div className="pt-10 flex gap-6">
                            <button type="button" onClick={() => setEditingClient(null)} className="flex-1 py-6 rounded-full font-black text-slate-400 bg-slate-100 hover:bg-slate-200 transition-all uppercase tracking-widest text-xs">Discard</button>
                            <button type="submit" className="flex-1 py-6 rounded-full font-black bg-[#0B2240] text-white hover:bg-blue-800 transition-all shadow-2xl shadow-blue-900/30 transform active:scale-95 uppercase tracking-widest text-xs">Commit Updates</button>
                        </div>
                    </form>
                </div>
            </div>
        )}
    </div>
  );
};
