
import React, { useMemo, useState, useEffect } from 'react';
import { useData } from '../../context/DataContext';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, Legend } from 'recharts';
import { BadgeDollarSign, TrendingUp, Wallet, ArrowUpRight, DollarSign, Download, Shield } from 'lucide-react';
import { ProductType, UserRole } from '../../types';
import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';

// Vibrant MacOS-style colors
const CHART_COLORS = ['#3B82F6', '#06B6D4', '#8B5CF6', '#10B981', '#F59E0B'];

export const Commissions: React.FC = () => {
  const { commissions, metrics, user } = useData();
  const [lastSync, setLastSync] = useState(new Date());

  // Autonomous update of sync time
  useEffect(() => {
    const timer = setInterval(() => setLastSync(new Date()), 30000);
    return () => clearInterval(timer);
  }, []);

  const filteredCommissions = useMemo(() => {
    if (user?.role === UserRole.ADVISOR && user.productsSold) {
        return commissions.filter(c => user.productsSold!.includes(c.product));
    }
    return commissions;
  }, [commissions, user]);

  const commissionsByProduct = useMemo(() => {
    const data: Record<string, number> = {};
    const relevantProducts = user?.role === UserRole.ADVISOR && user.productsSold 
        ? user.productsSold 
        : Object.values(ProductType);
    
    relevantProducts.forEach(t => data[t] = 0);

    filteredCommissions.forEach(c => {
      if (data[c.product] !== undefined) {
         data[c.product] = (data[c.product] || 0) + c.amount;
      }
    });

    return Object.entries(data)
      .filter(([_, val]) => val > 0)
      .map(([name, value]) => ({ name, value }));
  }, [filteredCommissions, user]);

  const recentCommissions = [...filteredCommissions].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  // Calculate Average Commission Rate
  const avgCommissionRate = filteredCommissions.length > 0
    ? (filteredCommissions.reduce((acc, c) => acc + c.rate, 0) / filteredCommissions.length) * 100
    : 0;

  const generateExport = () => {
    const doc = new jsPDF({ orientation: 'landscape' });
    
    // Add Company Logo (Golden Cards)
    const logoX = 14;
    const logoY = 10;
    
    // Back Card (Darker Amber)
    doc.setFillColor(245, 158, 11); // #F59E0B
    doc.roundedRect(logoX, logoY, 9, 6, 1, 1, 'F'); 
    
    // Front Card (Lighter Amber)
    doc.setFillColor(252, 211, 77); // #FCD34D
    doc.roundedRect(logoX + 0.5, logoY + 2, 8, 5.5, 1, 1, 'F');
    
    // Chip (Dark Amber)
    doc.setFillColor(180, 83, 9); // #B45309
    doc.roundedRect(logoX + 3.7, logoY + 3.7, 1.6, 2.2, 0.4, 0.4, 'F');

    doc.setFontSize(22);
    doc.setTextColor(11, 34, 64);
    doc.setFont("helvetica", "bold");
    doc.text("NEW HOLLAND", logoX + 11, logoY + 5);
    
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text("FINANCIAL GROUP", logoX + 11, logoY + 8);

    doc.setFontSize(14);
    doc.setTextColor(11, 34, 64);
    doc.text("Transaction History & Earnings Report", 14, 30);
    
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated by: ${user?.name || 'NHFG Terminal'}`, 14, 38);
    doc.text(`Export Timestamp: ${new Date().toLocaleString()}`, 14, 43);
    doc.text(`Proprietary Document - Copyright © ${new Date().getFullYear()} New Holland Financial Group. All Rights Reserved.`, 14, 48);

    const tableColumn = ["Client Account", "Product Category", "Written Premium", "Yield Rate", "Advisor Earnings", "Date"];
    const tableRows: any[] = [];

    recentCommissions.forEach(comm => {
      const rowData = [
        comm.clientName,
        comm.product,
        `$${comm.premium.toLocaleString()}`,
        `${(comm.rate * 100).toFixed(1)}%`,
        `$${comm.amount.toLocaleString()}`,
        new Date(comm.date).toLocaleDateString(),
      ];
      tableRows.push(rowData);
    });

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 55,
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [11, 34, 64], textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });

    doc.save(`NHFG_Earnings_Export_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <div className="space-y-8 animate-fade-in pb-10">
      <div>
        <h1 className="text-3xl font-black text-slate-900 tracking-tight uppercase tracking-tighter">Earnings</h1>
        <div className="flex items-center gap-1.5 mt-1">
            <span className="h-1.5 w-1.5 bg-green-500 rounded-full animate-pulse shadow-[0_0_8px_rgba(34,197,94,0.5)]"></span>
            <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Comp Synced: {lastSync.toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'})}</span>
        </div>
      </div>

      {/* Top Stat Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-[#10B981] p-8 rounded-[2.5rem] shadow-xl shadow-emerald-500/20 text-white relative overflow-hidden group hover:scale-[1.02] transition-transform duration-300">
           <div className="absolute -right-6 -top-6 p-8 opacity-10 transform group-hover:rotate-12 transition-transform duration-500">
               <Wallet className="h-32 w-32 text-white" />
           </div>
           <div className="relative z-10 flex flex-col h-full justify-between">
               <div className="flex items-center justify-between mb-2">
                  <p className="text-emerald-100 font-bold text-xs uppercase tracking-widest">Total Earnings</p>
                  <div className="p-2 bg-white/20 rounded-xl backdrop-blur-md">
                    <Wallet className="h-5 w-5 text-white" />
                  </div>
               </div>
               <div>
                   <p className="text-4xl font-black tracking-tight mb-3">${metrics.totalCommission.toLocaleString()}</p>
                   <div className="inline-flex items-center gap-1.5 bg-white/20 px-3 py-1.5 rounded-full text-xs font-bold backdrop-blur-md">
                      <TrendingUp className="h-3 w-3" />
                      Live Feed
                   </div>
               </div>
           </div>
        </div>

        <div className="bg-white p-8 rounded-[2.5rem] shadow-sm border border-slate-100 flex flex-col justify-between hover:shadow-lg transition-all duration-300 group relative overflow-hidden">
           <div className="absolute top-0 right-0 w-32 h-32 bg-blue-50 rounded-full blur-3xl -mr-16 -mt-16 transition-opacity opacity-50 group-hover:opacity-100"></div>
           <div className="flex justify-between items-start mb-4 relative z-10">
              <div>
                  <p className="text-slate-400 font-bold text-xs uppercase tracking-widest mb-1">Avg. Yield</p>
                  <p className="text-4xl font-black text-slate-900">{avgCommissionRate.toFixed(1)}%</p>
              </div>
              <div className="p-3 bg-blue-50 text-blue-600 rounded-2xl group-hover:scale-110 transition-transform shadow-sm">
                  <TrendingUp className="h-6 w-6" />
              </div>
           </div>
           <p className="text-sm text-slate-500 font-medium relative z-10">Commission average</p>
        </div>

         <div className="bg-white p-8 rounded-[2.5rem] shadow-sm border border-slate-100 flex flex-col justify-between hover:shadow-lg transition-all duration-300 group relative overflow-hidden">
           <div className="absolute top-0 right-0 w-32 h-32 bg-purple-50 rounded-full blur-3xl -mr-16 -mt-16 transition-opacity opacity-50 group-hover:opacity-100"></div>
           <div className="flex justify-between items-start mb-4 relative z-10">
              <div>
                  <p className="text-slate-400 font-bold text-xs uppercase tracking-widest mb-1">Production</p>
                  <p className="text-4xl font-black text-slate-900">${metrics.totalRevenue.toLocaleString()}</p>
              </div>
              <div className="p-3 bg-purple-50 text-purple-600 rounded-2xl group-hover:scale-110 transition-transform shadow-sm">
                  <BadgeDollarSign className="h-6 w-6" />
              </div>
           </div>
           <p className="text-sm text-slate-500 font-medium relative z-10">Total premium value</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
        <div className="bg-white p-12 rounded-[4rem] shadow-[0_20px_50px_-10px_rgba(0,0,0,0.03)] border border-slate-100 h-[32rem] flex flex-col transition-all duration-500 group relative">
           <div className="mb-10">
              <h3 className="text-2xl font-black text-slate-800 tracking-tight uppercase">Earnings by Product</h3>
              <p className="text-[10px] text-slate-400 font-black uppercase tracking-[0.3em] mt-1">Transaction Yield Matrix</p>
           </div>
           <div className="flex-1 w-full min-w-0" style={{ height: '350px' }}>
            <ResponsiveContainer width="100%" height={350}>
              <BarChart data={commissionsByProduct} margin={{ left: -20, right: 0, bottom: 0, top: 10 }}>
                <CartesianGrid strokeDasharray="6 6" vertical={false} stroke="#f1f5f9" />
                <XAxis 
                    dataKey="name" 
                    axisLine={false} 
                    tickLine={false} 
                    tick={{fill: '#94a3b8', fontSize: 10, fontWeight: 900}} 
                    dy={15}
                    interval={0}
                />
                <YAxis 
                    axisLine={false} 
                    tickLine={false} 
                    tick={{fill: '#94a3b8', fontSize: 10, fontWeight: 900}} 
                    tickFormatter={(val) => `$${val/1000}k`} 
                />
                <Tooltip 
                    cursor={{fill: '#f8fafc', radius: 10}}
                    contentStyle={{borderRadius: '24px', border: 'none', boxShadow: '0 20px 40px -5px rgba(0,0,0,0.1)', padding: '16px', fontWeight: 'bold'}}
                    formatter={(val: number) => [`$${val.toLocaleString()}`, 'Commission']}
                />
                <Bar dataKey="value" radius={[12, 12, 0, 0]} barSize={40}>
                    {commissionsByProduct.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={CHART_COLORS[index % CHART_COLORS.length]} />
                    ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
           </div>
        </div>

        <div className="bg-white p-12 rounded-[4rem] shadow-[0_20px_50px_-10px_rgba(0,0,0,0.03)] border border-slate-100 h-[32rem] flex flex-col transition-all duration-500 group relative">
           <div className="mb-2">
              <h3 className="text-2xl font-black text-slate-800 tracking-tight uppercase">Portfolio Mix</h3>
              <p className="text-[10px] text-slate-400 font-black uppercase tracking-[0.3em] mt-1">Concentration of Services</p>
           </div>
           <div className="flex-1 w-full relative min-w-0" style={{ height: '350px' }}>
            <ResponsiveContainer width="100%" height={350}>
              <PieChart>
                <Pie
                  data={commissionsByProduct}
                  cx="50%"
                  cy="50%"
                  innerRadius={90}
                  outerRadius={135}
                  paddingAngle={8}
                  dataKey="value"
                  stroke="none"
                  cornerRadius={15}
                >
                  {commissionsByProduct.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={CHART_COLORS[index % CHART_COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip 
                    contentStyle={{borderRadius: '24px', border: 'none', boxShadow: '0 20px 40px -5px rgba(0,0,0,0.1)', padding: '16px', fontWeight: 'bold'}}
                    formatter={(val: number) => `$${val.toLocaleString()}`} 
                />
                <Legend 
                    verticalAlign="bottom" 
                    height={40} 
                    iconType="circle"
                    formatter={(value) => <span className="text-slate-500 font-black text-[10px] ml-1 uppercase tracking-widest">{value}</span>}
                />
              </PieChart>
            </ResponsiveContainer>
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none pb-12">
                <div className="text-center">
                    <p className="text-5xl font-black text-slate-800 tracking-tighter leading-none">{commissionsByProduct.length}</p>
                    <p className="text-[9px] text-slate-400 font-black uppercase tracking-[0.3em] mt-2">Active Channels</p>
                </div>
            </div>
           </div>
        </div>
      </div>

      {/* TRANSACTION HISTORY SECTION - MATCHED TO SCREENSHOT */}
      <div className="bg-white rounded-[4rem] shadow-[0_20px_50px_-10px_rgba(0,0,0,0.03)] border border-slate-100 overflow-hidden">
        <div className="px-12 py-10 flex justify-between items-center border-b border-slate-50">
          <h3 className="text-2xl font-black text-slate-800 tracking-tight uppercase">Transaction History</h3>
          <button 
            onClick={generateExport}
            className="text-[10px] font-black text-blue-600 bg-blue-50/80 px-8 py-3.5 rounded-full hover:bg-blue-100 transition-all uppercase tracking-[0.2em] border border-blue-100/50 shadow-sm flex items-center gap-2"
          >
              <Download className="h-3.5 w-3.5" strokeWidth={3} /> Export Detailed CSV
          </button>
        </div>
        <div className="overflow-x-auto no-scrollbar px-2">
          <table className="min-w-full">
            <thead className="bg-slate-50/50">
              <tr>
                <th className="px-10 py-6 text-left text-[11px] font-black text-slate-400 uppercase tracking-[0.25em]">Client Account</th>
                <th className="px-10 py-6 text-left text-[11px] font-black text-slate-400 uppercase tracking-[0.25em]">Product Category</th>
                <th className="px-10 py-6 text-left text-[11px] font-black text-slate-400 uppercase tracking-[0.25em]">Written Premium</th>
                <th className="px-10 py-6 text-left text-[11px] font-black text-slate-400 uppercase tracking-[0.25em]">Yield Rate</th>
                <th className="px-10 py-6 text-left text-[11px] font-black text-slate-400 uppercase tracking-[0.25em]">Advisor Earnings</th>
                <th className="px-10 py-6 text-left text-[11px] font-black text-slate-400 uppercase tracking-[0.25em]">Date</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-slate-50">
              {recentCommissions.map((comm) => (
                <tr key={comm.id} className="hover:bg-slate-50/80 transition-colors group">
                  <td className="px-10 py-8 whitespace-nowrap text-sm font-black text-slate-800">{comm.clientName}</td>
                  <td className="px-10 py-8 whitespace-nowrap">
                      <span className="px-4 py-1.5 bg-slate-100 text-slate-600 rounded-xl text-[10px] font-black uppercase tracking-widest border border-slate-200/50">{comm.product}</span>
                  </td>
                  <td className="px-10 py-8 whitespace-nowrap text-sm font-bold text-slate-500 tracking-tight">${comm.premium.toLocaleString()}</td>
                  <td className="px-10 py-8 whitespace-nowrap text-sm font-bold text-slate-500 tracking-tight">{(comm.rate * 100).toFixed(1)}%</td>
                  <td className="px-10 py-8 whitespace-nowrap">
                      <span className="text-sm font-black text-green-600 flex items-center gap-1.5">
                          <ArrowUpRight className="h-4 w-4" strokeWidth={3} />
                          ${comm.amount.toLocaleString()}
                      </span>
                  </td>
                  <td className="px-10 py-8 whitespace-nowrap text-[11px] font-black text-slate-400 uppercase tracking-[0.2em]">{new Date(comm.date).toLocaleDateString([], { month: 'short', day: 'numeric', year: 'numeric' })}</td>
                </tr>
              ))}
              {recentCommissions.length === 0 && (
                <tr>
                  <td colSpan={6} className="px-10 py-48 text-center">
                    <div className="flex flex-col items-center justify-center opacity-30 grayscale">
                        <div className="w-20 h-20 bg-slate-100 rounded-[2rem] flex items-center justify-center mb-6">
                            <Shield className="h-8 w-8 text-slate-400" />
                        </div>
                        <p className="text-slate-500 font-black uppercase tracking-[0.35em] text-sm">Database Feed Clear</p>
                    </div>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
