/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AgentPolicy model module.
 * @module model/AgentPolicy
 * @version 3.0.0
 */
class AgentPolicy {
    /**
     * Constructs a new <code>AgentPolicy</code>.
     * A policy associated with the agent ID.
     * @alias module:model/AgentPolicy
     */
    constructor() { 
        
        AgentPolicy.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AgentPolicy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AgentPolicy} obj Optional instance to populate.
     * @return {module:model/AgentPolicy} The populated <code>AgentPolicy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AgentPolicy();

            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('policyNumber')) {
                obj['policyNumber'] = ApiClient.convertToType(data['policyNumber'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
            if (data.hasOwnProperty('agentId')) {
                obj['agentId'] = ApiClient.convertToType(data['agentId'], 'String');
            }
            if (data.hasOwnProperty('inceptionDate')) {
                obj['inceptionDate'] = ApiClient.convertToType(data['inceptionDate'], 'Date');
            }
            if (data.hasOwnProperty('termEffectiveDate')) {
                obj['termEffectiveDate'] = ApiClient.convertToType(data['termEffectiveDate'], 'Date');
            }
            if (data.hasOwnProperty('termExpirationDate')) {
                obj['termExpirationDate'] = ApiClient.convertToType(data['termExpirationDate'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AgentPolicy</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AgentPolicy</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['policyNumber'] && !(typeof data['policyNumber'] === 'string' || data['policyNumber'] instanceof String)) {
            throw new Error("Expected the field `policyNumber` to be a primitive type in the JSON string but got " + data['policyNumber']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['firstName'] && !(typeof data['firstName'] === 'string' || data['firstName'] instanceof String)) {
            throw new Error("Expected the field `firstName` to be a primitive type in the JSON string but got " + data['firstName']);
        }
        // ensure the json data is a string
        if (data['lastName'] && !(typeof data['lastName'] === 'string' || data['lastName'] instanceof String)) {
            throw new Error("Expected the field `lastName` to be a primitive type in the JSON string but got " + data['lastName']);
        }
        // ensure the json data is a string
        if (data['phoneNumber'] && !(typeof data['phoneNumber'] === 'string' || data['phoneNumber'] instanceof String)) {
            throw new Error("Expected the field `phoneNumber` to be a primitive type in the JSON string but got " + data['phoneNumber']);
        }
        // ensure the json data is a string
        if (data['agentId'] && !(typeof data['agentId'] === 'string' || data['agentId'] instanceof String)) {
            throw new Error("Expected the field `agentId` to be a primitive type in the JSON string but got " + data['agentId']);
        }

        return true;
    }


}



/**
 * Boolean for whether the policy is currently active.
 * @member {Boolean} active
 */
AgentPolicy.prototype['active'] = undefined;

/**
 * The policy number for this policy.
 * @member {String} policyNumber
 */
AgentPolicy.prototype['policyNumber'] = undefined;

/**
 * The date the policy was created.
 * @member {Date} createdAt
 */
AgentPolicy.prototype['createdAt'] = undefined;

/**
 * The unique identifier for this policy. This can be used to retrieve the policy details.
 * @member {String} id
 */
AgentPolicy.prototype['id'] = undefined;

/**
 * The email associated with the primary named insured of the policy.
 * @member {String} email
 */
AgentPolicy.prototype['email'] = undefined;

/**
 * The first name of the primary named insured.
 * @member {String} firstName
 */
AgentPolicy.prototype['firstName'] = undefined;

/**
 * The last name of the primary named insured.
 * @member {String} lastName
 */
AgentPolicy.prototype['lastName'] = undefined;

/**
 * The phone number of the primary named insured.
 * @member {String} phoneNumber
 */
AgentPolicy.prototype['phoneNumber'] = undefined;

/**
 * The id of the agent managing the policy.
 * @member {String} agentId
 */
AgentPolicy.prototype['agentId'] = undefined;

/**
 * The first date the policy was effective.
 * @member {Date} inceptionDate
 */
AgentPolicy.prototype['inceptionDate'] = undefined;

/**
 * The effective date of the most recent policy term.
 * @member {Date} termEffectiveDate
 */
AgentPolicy.prototype['termEffectiveDate'] = undefined;

/**
 * The expiration date of the most recent policy term.
 * @member {Date} termExpirationDate
 */
AgentPolicy.prototype['termExpirationDate'] = undefined;






export default AgentPolicy;

