/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AgentQuote from './AgentQuote';

/**
 * The AgencyQuotes model module.
 * @module model/AgencyQuotes
 * @version 3.0.0
 */
class AgencyQuotes {
    /**
     * Constructs a new <code>AgencyQuotes</code>.
     * A collection of quotes associated with the agency, which may be filtered based on specified criteria.
     * @alias module:model/AgencyQuotes
     */
    constructor() { 
        
        AgencyQuotes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AgencyQuotes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AgencyQuotes} obj Optional instance to populate.
     * @return {module:model/AgencyQuotes} The populated <code>AgencyQuotes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AgencyQuotes();

            if (data.hasOwnProperty('currentOffset')) {
                obj['currentOffset'] = ApiClient.convertToType(data['currentOffset'], 'Number');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('quotes')) {
                obj['quotes'] = ApiClient.convertToType(data['quotes'], [AgentQuote]);
            }
            if (data.hasOwnProperty('totalQuotes')) {
                obj['totalQuotes'] = ApiClient.convertToType(data['totalQuotes'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AgencyQuotes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AgencyQuotes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }
        if (data['quotes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['quotes'])) {
                throw new Error("Expected the field `quotes` to be an array in the JSON data but got " + data['quotes']);
            }
            // validate the optional field `quotes` (array)
            for (const item of data['quotes']) {
                AgentQuote.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * The query offset passed in this request. Defaults to 0.
 * @member {Number} currentOffset
 */
AgencyQuotes.prototype['currentOffset'] = undefined;

/**
 * The error message.
 * @member {String} error
 */
AgencyQuotes.prototype['error'] = undefined;

/**
 * A collection of quotes associated with the agency, which may be filtered based on specified criteria.
 * @member {Array.<module:model/AgentQuote>} quotes
 */
AgencyQuotes.prototype['quotes'] = undefined;

/**
 * The number of quotes matching the query. This count is capped for performance, so for very large result sets it may be lower than the true total. Use it for pagination: when it is greater than `offset` plus the number of quotes returned in this response, more results are available, so increase `offset` to fetch the next page.
 * @member {Number} totalQuotes
 */
AgencyQuotes.prototype['totalQuotes'] = undefined;






export default AgencyQuotes;

