/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AgencyAgentSearchParameters model module.
 * @module model/AgencyAgentSearchParameters
 * @version 3.0.0
 */
class AgencyAgentSearchParameters {
    /**
     * Constructs a new <code>AgencyAgentSearchParameters</code>.
     * The search parameters used to filter the agents
     * @alias module:model/AgencyAgentSearchParameters
     */
    constructor() { 
        
        AgencyAgentSearchParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AgencyAgentSearchParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AgencyAgentSearchParameters} obj Optional instance to populate.
     * @return {module:model/AgencyAgentSearchParameters} The populated <code>AgencyAgentSearchParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AgencyAgentSearchParameters();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('nationalProducerNumber')) {
                obj['nationalProducerNumber'] = ApiClient.convertToType(data['nationalProducerNumber'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AgencyAgentSearchParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AgencyAgentSearchParameters</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['nationalProducerNumber'] && !(typeof data['nationalProducerNumber'] === 'string' || data['nationalProducerNumber'] instanceof String)) {
            throw new Error("Expected the field `nationalProducerNumber` to be a primitive type in the JSON string but got " + data['nationalProducerNumber']);
        }

        return true;
    }


}



/**
 * The email address of the agent
 * @member {String} email
 */
AgencyAgentSearchParameters.prototype['email'] = undefined;

/**
 * The national producer number of the agent
 * @member {String} nationalProducerNumber
 */
AgencyAgentSearchParameters.prototype['nationalProducerNumber'] = undefined;






export default AgencyAgentSearchParameters;

