/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AgencyAgent model module.
 * @module model/AgencyAgent
 * @version 3.0.0
 */
class AgencyAgent {
    /**
     * Constructs a new <code>AgencyAgent</code>.
     * A human agent registered with the agency
     * @alias module:model/AgencyAgent
     * @param email {String} The email address of the agent. No value will be returned for digital agents.
     * @param id {String} The unique identifier for the agent
     * @param nationalProducerNumber {String} The national producer number of the agent
     * @param appointedMarkets {Array.<String>} The markets the agent is appointed in
     */
    constructor(email, id, nationalProducerNumber, appointedMarkets) { 
        
        AgencyAgent.initialize(this, email, id, nationalProducerNumber, appointedMarkets);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, id, nationalProducerNumber, appointedMarkets) { 
        obj['email'] = email;
        obj['id'] = id;
        obj['nationalProducerNumber'] = nationalProducerNumber;
        obj['appointedMarkets'] = appointedMarkets;
    }

    /**
     * Constructs a <code>AgencyAgent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AgencyAgent} obj Optional instance to populate.
     * @return {module:model/AgencyAgent} The populated <code>AgencyAgent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AgencyAgent();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('nationalProducerNumber')) {
                obj['nationalProducerNumber'] = ApiClient.convertToType(data['nationalProducerNumber'], 'String');
            }
            if (data.hasOwnProperty('appointedMarkets')) {
                obj['appointedMarkets'] = ApiClient.convertToType(data['appointedMarkets'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AgencyAgent</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AgencyAgent</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AgencyAgent.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['nationalProducerNumber'] && !(typeof data['nationalProducerNumber'] === 'string' || data['nationalProducerNumber'] instanceof String)) {
            throw new Error("Expected the field `nationalProducerNumber` to be a primitive type in the JSON string but got " + data['nationalProducerNumber']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['appointedMarkets'])) {
            throw new Error("Expected the field `appointedMarkets` to be an array in the JSON data but got " + data['appointedMarkets']);
        }

        return true;
    }


}

AgencyAgent.RequiredProperties = ["email", "id", "nationalProducerNumber", "appointedMarkets"];

/**
 * The email address of the agent. No value will be returned for digital agents.
 * @member {String} email
 */
AgencyAgent.prototype['email'] = undefined;

/**
 * The unique identifier for the agent
 * @member {String} id
 */
AgencyAgent.prototype['id'] = undefined;

/**
 * The national producer number of the agent
 * @member {String} nationalProducerNumber
 */
AgencyAgent.prototype['nationalProducerNumber'] = undefined;

/**
 * The markets the agent is appointed in
 * @member {Array.<String>} appointedMarkets
 */
AgencyAgent.prototype['appointedMarkets'] = undefined;






export default AgencyAgent;

