/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiCreditScoreTierValueRequirementsInner from './ApiCreditScoreTierValueRequirementsInner';

/**
 * The ApiCreditScoreTierValue model module.
 * @module model/ApiCreditScoreTierValue
 * @version 3.0.0
 */
class ApiCreditScoreTierValue {
    /**
     * Constructs a new <code>ApiCreditScoreTierValue</code>.
     * A wrapped value with validation information.
     * @alias module:model/ApiCreditScoreTierValue
     * @param message {String} An error message if applicable.
     * @param requirements {Array.<module:model/ApiCreditScoreTierValueRequirementsInner>} A list of requirements that must be met for this value to be valid.
     * @param valid {Boolean} This value is valid.
     * @param value {module:model/ApiCreditScoreTierValue.ValueEnum} The current value.
     */
    constructor(message, requirements, valid, value) { 
        
        ApiCreditScoreTierValue.initialize(this, message, requirements, valid, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, requirements, valid, value) { 
        obj['message'] = message;
        obj['requirements'] = requirements;
        obj['valid'] = valid;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>ApiCreditScoreTierValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiCreditScoreTierValue} obj Optional instance to populate.
     * @return {module:model/ApiCreditScoreTierValue} The populated <code>ApiCreditScoreTierValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiCreditScoreTierValue();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('requirements')) {
                obj['requirements'] = ApiClient.convertToType(data['requirements'], [ApiCreditScoreTierValueRequirementsInner]);
            }
            if (data.hasOwnProperty('valid')) {
                obj['valid'] = ApiClient.convertToType(data['valid'], 'Boolean');
            }
            if (data.hasOwnProperty('inferredValue')) {
                obj['inferredValue'] = ApiClient.convertToType(data['inferredValue'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiCreditScoreTierValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiCreditScoreTierValue</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiCreditScoreTierValue.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        if (data['requirements']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['requirements'])) {
                throw new Error("Expected the field `requirements` to be an array in the JSON data but got " + data['requirements']);
            }
            // validate the optional field `requirements` (array)
            for (const item of data['requirements']) {
                ApiCreditScoreTierValueRequirementsInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['inferredValue'] && !(typeof data['inferredValue'] === 'string' || data['inferredValue'] instanceof String)) {
            throw new Error("Expected the field `inferredValue` to be a primitive type in the JSON string but got " + data['inferredValue']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }

        return true;
    }


}

ApiCreditScoreTierValue.RequiredProperties = ["message", "requirements", "valid", "value"];

/**
 * An error message if applicable.
 * @member {String} message
 */
ApiCreditScoreTierValue.prototype['message'] = undefined;

/**
 * A list of requirements that must be met for this value to be valid.
 * @member {Array.<module:model/ApiCreditScoreTierValueRequirementsInner>} requirements
 */
ApiCreditScoreTierValue.prototype['requirements'] = undefined;

/**
 * This value is valid.
 * @member {Boolean} valid
 */
ApiCreditScoreTierValue.prototype['valid'] = undefined;

/**
 * The value inferred and used instead for pricing when value is invalid.
 * @member {module:model/ApiCreditScoreTierValue.InferredValueEnum} inferredValue
 */
ApiCreditScoreTierValue.prototype['inferredValue'] = undefined;

/**
 * The current value.
 * @member {module:model/ApiCreditScoreTierValue.ValueEnum} value
 */
ApiCreditScoreTierValue.prototype['value'] = undefined;





/**
 * Allowed values for the <code>inferredValue</code> property.
 * @enum {String}
 * @readonly
 */
ApiCreditScoreTierValue['InferredValueEnum'] = {

    /**
     * value: "excellent"
     * @const
     */
    "excellent": "excellent",

    /**
     * value: "very_good"
     * @const
     */
    "very_good": "very_good",

    /**
     * value: "good"
     * @const
     */
    "good": "good",

    /**
     * value: "average"
     * @const
     */
    "average": "average",

    /**
     * value: "poor"
     * @const
     */
    "poor": "poor"
};


/**
 * Allowed values for the <code>value</code> property.
 * @enum {String}
 * @readonly
 */
ApiCreditScoreTierValue['ValueEnum'] = {

    /**
     * value: "excellent"
     * @const
     */
    "excellent": "excellent",

    /**
     * value: "very_good"
     * @const
     */
    "very_good": "very_good",

    /**
     * value: "good"
     * @const
     */
    "good": "good",

    /**
     * value: "average"
     * @const
     */
    "average": "average",

    /**
     * value: "poor"
     * @const
     */
    "poor": "poor"
};



export default ApiCreditScoreTierValue;

