/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiDateValueRequirementsInner from './ApiDateValueRequirementsInner';

/**
 * The ApiDateValue model module.
 * @module model/ApiDateValue
 * @version 3.0.0
 */
class ApiDateValue {
    /**
     * Constructs a new <code>ApiDateValue</code>.
     * A wrapped value with validation information.
     * @alias module:model/ApiDateValue
     * @param message {String} An error message if applicable.
     * @param requirements {Array.<module:model/ApiDateValueRequirementsInner>} A list of requirements that must be met for this value to be valid.
     * @param valid {Boolean} This value is valid.
     * @param value {Date} The current value in ISO 8601 full-date format. See rfc 3339 section 5.6: https://www.rfc-editor.org/rfc/rfc3339#section-5.6.
     */
    constructor(message, requirements, valid, value) { 
        
        ApiDateValue.initialize(this, message, requirements, valid, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, requirements, valid, value) { 
        obj['message'] = message;
        obj['requirements'] = requirements;
        obj['valid'] = valid;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>ApiDateValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiDateValue} obj Optional instance to populate.
     * @return {module:model/ApiDateValue} The populated <code>ApiDateValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiDateValue();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('requirements')) {
                obj['requirements'] = ApiClient.convertToType(data['requirements'], [ApiDateValueRequirementsInner]);
            }
            if (data.hasOwnProperty('valid')) {
                obj['valid'] = ApiClient.convertToType(data['valid'], 'Boolean');
            }
            if (data.hasOwnProperty('inferredValue')) {
                obj['inferredValue'] = ApiClient.convertToType(data['inferredValue'], 'Date');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiDateValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiDateValue</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiDateValue.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        if (data['requirements']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['requirements'])) {
                throw new Error("Expected the field `requirements` to be an array in the JSON data but got " + data['requirements']);
            }
            // validate the optional field `requirements` (array)
            for (const item of data['requirements']) {
                ApiDateValueRequirementsInner.validateJSON(item);
            };
        }

        return true;
    }


}

ApiDateValue.RequiredProperties = ["message", "requirements", "valid", "value"];

/**
 * An error message if applicable.
 * @member {String} message
 */
ApiDateValue.prototype['message'] = undefined;

/**
 * A list of requirements that must be met for this value to be valid.
 * @member {Array.<module:model/ApiDateValueRequirementsInner>} requirements
 */
ApiDateValue.prototype['requirements'] = undefined;

/**
 * This value is valid.
 * @member {Boolean} valid
 */
ApiDateValue.prototype['valid'] = undefined;

/**
 * The value inferred and used instead for pricing when value is invalid.
 * @member {Date} inferredValue
 */
ApiDateValue.prototype['inferredValue'] = undefined;

/**
 * The current value in ISO 8601 full-date format. See rfc 3339 section 5.6: https://www.rfc-editor.org/rfc/rfc3339#section-5.6.
 * @member {Date} value
 */
ApiDateValue.prototype['value'] = undefined;






export default ApiDateValue;

