/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiFactIntegerRangeRequirementMetadata model module.
 * @module model/ApiFactIntegerRangeRequirementMetadata
 * @version 3.0.0
 */
class ApiFactIntegerRangeRequirementMetadata {
    /**
     * Constructs a new <code>ApiFactIntegerRangeRequirementMetadata</code>.
     * Metadata to describe an allowed integer range
     * @alias module:model/ApiFactIntegerRangeRequirementMetadata
     */
    constructor() { 
        
        ApiFactIntegerRangeRequirementMetadata.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiFactIntegerRangeRequirementMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiFactIntegerRangeRequirementMetadata} obj Optional instance to populate.
     * @return {module:model/ApiFactIntegerRangeRequirementMetadata} The populated <code>ApiFactIntegerRangeRequirementMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiFactIntegerRangeRequirementMetadata();

            if (data.hasOwnProperty('max')) {
                obj['max'] = ApiClient.convertToType(data['max'], 'Number');
            }
            if (data.hasOwnProperty('min')) {
                obj['min'] = ApiClient.convertToType(data['min'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiFactIntegerRangeRequirementMetadata</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiFactIntegerRangeRequirementMetadata</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * The maximum allowed value for the provided value
 * @member {Number} max
 */
ApiFactIntegerRangeRequirementMetadata.prototype['max'] = undefined;

/**
 * The minimum allowed value for the provided value
 * @member {Number} min
 */
ApiFactIntegerRangeRequirementMetadata.prototype['min'] = undefined;






export default ApiFactIntegerRangeRequirementMetadata;

