/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiFactRequiredValueRequirementMetadata model module.
 * @module model/ApiFactRequiredValueRequirementMetadata
 * @version 3.0.0
 */
class ApiFactRequiredValueRequirementMetadata {
    /**
     * Constructs a new <code>ApiFactRequiredValueRequirementMetadata</code>.
     * Metadata to describe the values that are required to be selected on at least one entity
     * @alias module:model/ApiFactRequiredValueRequirementMetadata
     * @param requiredValues {Array.<String>} Values that satisfy the requirement. All of these must be selected by at least one entity, so if there are three values then there would need to be at least three entities to fulfill the requirement
     */
    constructor(requiredValues) { 
        
        ApiFactRequiredValueRequirementMetadata.initialize(this, requiredValues);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, requiredValues) { 
        obj['requiredValues'] = requiredValues;
    }

    /**
     * Constructs a <code>ApiFactRequiredValueRequirementMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiFactRequiredValueRequirementMetadata} obj Optional instance to populate.
     * @return {module:model/ApiFactRequiredValueRequirementMetadata} The populated <code>ApiFactRequiredValueRequirementMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiFactRequiredValueRequirementMetadata();

            if (data.hasOwnProperty('requiredValues')) {
                obj['requiredValues'] = ApiClient.convertToType(data['requiredValues'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiFactRequiredValueRequirementMetadata</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiFactRequiredValueRequirementMetadata</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiFactRequiredValueRequirementMetadata.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['requiredValues'])) {
            throw new Error("Expected the field `requiredValues` to be an array in the JSON data but got " + data['requiredValues']);
        }

        return true;
    }


}

ApiFactRequiredValueRequirementMetadata.RequiredProperties = ["requiredValues"];

/**
 * Values that satisfy the requirement. All of these must be selected by at least one entity, so if there are three values then there would need to be at least three entities to fulfill the requirement
 * @member {Array.<String>} requiredValues
 */
ApiFactRequiredValueRequirementMetadata.prototype['requiredValues'] = undefined;






export default ApiFactRequiredValueRequirementMetadata;

