/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiFactRequiredValueRequirementMetadata from './ApiFactRequiredValueRequirementMetadata';
import ApiFactRequirement from './ApiFactRequirement';

/**
 * The ApiFactRequiredValueRequirement model module.
 * @module model/ApiFactRequiredValueRequirement
 * @version 3.0.0
 */
class ApiFactRequiredValueRequirement {
    /**
     * Constructs a new <code>ApiFactRequiredValueRequirement</code>.
     * Describes a required value requirement
     * @alias module:model/ApiFactRequiredValueRequirement
     * @extends module:model/ApiFactRequirement
     * @implements module:model/ApiFactRequirement
     * @param fulfilled {Boolean} Whether the requirement has been fulfilled
     * @param kind {module:model/ApiFactRequiredValueRequirement.KindEnum} The kind of requirement
     * @param message {String} An optional message describing the requirement
     */
    constructor(fulfilled, kind, message) { 
        ApiFactRequirement.initialize(this, fulfilled, kind, message);
        ApiFactRequiredValueRequirement.initialize(this, fulfilled, kind, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fulfilled, kind, message) { 
        obj['metadata'] = metadata;
    }

    /**
     * Constructs a <code>ApiFactRequiredValueRequirement</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiFactRequiredValueRequirement} obj Optional instance to populate.
     * @return {module:model/ApiFactRequiredValueRequirement} The populated <code>ApiFactRequiredValueRequirement</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiFactRequiredValueRequirement();
            ApiFactRequirement.constructFromObject(data, obj);
            ApiFactRequirement.constructFromObject(data, obj);

            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiFactRequiredValueRequirementMetadata.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiFactRequiredValueRequirement</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiFactRequiredValueRequirement</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiFactRequiredValueRequirement.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `metadata`
        if (data['metadata']) { // data not null
          ApiFactRequiredValueRequirementMetadata.validateJSON(data['metadata']);
        }

        return true;
    }


}

ApiFactRequiredValueRequirement.RequiredProperties = ["metadata", "fulfilled", "kind", "message"];

/**
 * @member {module:model/ApiFactRequiredValueRequirementMetadata} metadata
 */
ApiFactRequiredValueRequirement.prototype['metadata'] = undefined;


// Implement ApiFactRequirement interface:
/**
 * Whether the requirement has been fulfilled
 * @member {Boolean} fulfilled
 */
ApiFactRequirement.prototype['fulfilled'] = undefined;
/**
 * The kind of requirement
 * @member {module:model/ApiFactRequirement.KindEnum} kind
 */
ApiFactRequirement.prototype['kind'] = undefined;
/**
 * An optional message describing the requirement
 * @member {String} message
 */
ApiFactRequirement.prototype['message'] = undefined;




export default ApiFactRequiredValueRequirement;

