/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiRequestedTierValueRequirementsInner from './ApiRequestedTierValueRequirementsInner';

/**
 * The ApiRequestedTierValue model module.
 * @module model/ApiRequestedTierValue
 * @version 3.0.0
 */
class ApiRequestedTierValue {
    /**
     * Constructs a new <code>ApiRequestedTierValue</code>.
     * A wrapped value with validation information.
     * @alias module:model/ApiRequestedTierValue
     * @param message {String} An error message if applicable.
     * @param requirements {Array.<module:model/ApiRequestedTierValueRequirementsInner>} A list of requirements that must be met for this value to be valid.
     * @param valid {Boolean} This value is valid.
     * @param value {module:model/ApiRequestedTierValue.ValueEnum} The current value.
     */
    constructor(message, requirements, valid, value) { 
        
        ApiRequestedTierValue.initialize(this, message, requirements, valid, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, requirements, valid, value) { 
        obj['message'] = message;
        obj['requirements'] = requirements;
        obj['valid'] = valid;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>ApiRequestedTierValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiRequestedTierValue} obj Optional instance to populate.
     * @return {module:model/ApiRequestedTierValue} The populated <code>ApiRequestedTierValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiRequestedTierValue();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('requirements')) {
                obj['requirements'] = ApiClient.convertToType(data['requirements'], [ApiRequestedTierValueRequirementsInner]);
            }
            if (data.hasOwnProperty('valid')) {
                obj['valid'] = ApiClient.convertToType(data['valid'], 'Boolean');
            }
            if (data.hasOwnProperty('inferredValue')) {
                obj['inferredValue'] = ApiClient.convertToType(data['inferredValue'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiRequestedTierValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiRequestedTierValue</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiRequestedTierValue.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        if (data['requirements']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['requirements'])) {
                throw new Error("Expected the field `requirements` to be an array in the JSON data but got " + data['requirements']);
            }
            // validate the optional field `requirements` (array)
            for (const item of data['requirements']) {
                ApiRequestedTierValueRequirementsInner.validateJSON(item);
            };
        }

        return true;
    }


}

ApiRequestedTierValue.RequiredProperties = ["message", "requirements", "valid", "value"];

/**
 * An error message if applicable.
 * @member {String} message
 */
ApiRequestedTierValue.prototype['message'] = undefined;

/**
 * A list of requirements that must be met for this value to be valid.
 * @member {Array.<module:model/ApiRequestedTierValueRequirementsInner>} requirements
 */
ApiRequestedTierValue.prototype['requirements'] = undefined;

/**
 * This value is valid.
 * @member {Boolean} valid
 */
ApiRequestedTierValue.prototype['valid'] = undefined;

/**
 * The value inferred and used instead for pricing when value is invalid.
 * @member {module:model/ApiRequestedTierValue.InferredValueEnum} inferredValue
 */
ApiRequestedTierValue.prototype['inferredValue'] = undefined;

/**
 * The current value.
 * @member {module:model/ApiRequestedTierValue.ValueEnum} value
 */
ApiRequestedTierValue.prototype['value'] = undefined;





/**
 * Allowed values for the <code>inferredValue</code> property.
 * @enum {Number}
 * @readonly
 */
ApiRequestedTierValue['InferredValueEnum'] = {

    /**
     * value: 1
     * @const
     */
    "1": 1,

    /**
     * value: 2
     * @const
     */
    "2": 2,

    /**
     * value: 3
     * @const
     */
    "3": 3
};


/**
 * Allowed values for the <code>value</code> property.
 * @enum {Number}
 * @readonly
 */
ApiRequestedTierValue['ValueEnum'] = {

    /**
     * value: 1
     * @const
     */
    "1": 1,

    /**
     * value: 2
     * @const
     */
    "2": 2,

    /**
     * value: 3
     * @const
     */
    "3": 3
};



export default ApiRequestedTierValue;

