/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiFactRequirement from './ApiFactRequirement';

/**
 * The ApiTemporarilyUnavailableRequirement model module.
 * @module model/ApiTemporarilyUnavailableRequirement
 * @version 3.0.0
 */
class ApiTemporarilyUnavailableRequirement {
    /**
     * Constructs a new <code>ApiTemporarilyUnavailableRequirement</code>.
     * Describes requirements explaining the selection is temporarily unavailable
     * @alias module:model/ApiTemporarilyUnavailableRequirement
     * @extends module:model/ApiFactRequirement
     * @implements module:model/ApiFactRequirement
     * @param fulfilled {Boolean} Whether the requirement has been fulfilled
     * @param kind {module:model/ApiTemporarilyUnavailableRequirement.KindEnum} The kind of requirement
     * @param message {String} An optional message describing the requirement
     */
    constructor(fulfilled, kind, message) { 
        ApiFactRequirement.initialize(this, fulfilled, kind, message);
        ApiTemporarilyUnavailableRequirement.initialize(this, fulfilled, kind, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fulfilled, kind, message) { 
    }

    /**
     * Constructs a <code>ApiTemporarilyUnavailableRequirement</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiTemporarilyUnavailableRequirement} obj Optional instance to populate.
     * @return {module:model/ApiTemporarilyUnavailableRequirement} The populated <code>ApiTemporarilyUnavailableRequirement</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiTemporarilyUnavailableRequirement();
            ApiFactRequirement.constructFromObject(data, obj);
            ApiFactRequirement.constructFromObject(data, obj);

        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiTemporarilyUnavailableRequirement</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiTemporarilyUnavailableRequirement</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiTemporarilyUnavailableRequirement.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

ApiTemporarilyUnavailableRequirement.RequiredProperties = ["fulfilled", "kind", "message"];


// Implement ApiFactRequirement interface:
/**
 * Whether the requirement has been fulfilled
 * @member {Boolean} fulfilled
 */
ApiFactRequirement.prototype['fulfilled'] = undefined;
/**
 * The kind of requirement
 * @member {module:model/ApiFactRequirement.KindEnum} kind
 */
ApiFactRequirement.prototype['kind'] = undefined;
/**
 * An optional message describing the requirement
 * @member {String} message
 */
ApiFactRequirement.prototype['message'] = undefined;




export default ApiTemporarilyUnavailableRequirement;

