/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AttributionEvent model module.
 * @module model/AttributionEvent
 * @version 3.0.0
 */
class AttributionEvent {
    /**
     * Constructs a new <code>AttributionEvent</code>.
     * An attribution event with partner-passed parameters.
     * @alias module:model/AttributionEvent
     * @param data {Object} The partner-passed params associated with the event. This is an arbitrary object with any params that were provided.
     * @param name {module:model/AttributionEvent.NameEnum} The name of the event.
     */
    constructor(data, name) { 
        
        AttributionEvent.initialize(this, data, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data, name) { 
        obj['data'] = data;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>AttributionEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AttributionEvent} obj Optional instance to populate.
     * @return {module:model/AttributionEvent} The populated <code>AttributionEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AttributionEvent();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AttributionEvent</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AttributionEvent</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AttributionEvent.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

AttributionEvent.RequiredProperties = ["data", "name"];

/**
 * The partner-passed params associated with the event. This is an arbitrary object with any params that were provided.
 * @member {Object} data
 */
AttributionEvent.prototype['data'] = undefined;

/**
 * The name of the event.
 * @member {module:model/AttributionEvent.NameEnum} name
 */
AttributionEvent.prototype['name'] = undefined;





/**
 * Allowed values for the <code>name</code> property.
 * @enum {String}
 * @readonly
 */
AttributionEvent['NameEnum'] = {

    /**
     * value: "authenticate_bridge_link"
     * @const
     */
    "authenticate_bridge_link": "authenticate_bridge_link",

    /**
     * value: "create_bridge_link"
     * @const
     */
    "create_bridge_link": "create_bridge_link",

    /**
     * value: "create_policy"
     * @const
     */
    "create_policy": "create_policy",

    /**
     * value: "create_quote"
     * @const
     */
    "create_quote": "create_quote"
};



export default AttributionEvent;

