/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthTokenReference model module.
 * @module model/AuthTokenReference
 * @version 3.0.0
 */
class AuthTokenReference {
    /**
     * Constructs a new <code>AuthTokenReference</code>.
     * A possible token reference associated with your integration and query parameters.
     * @alias module:model/AuthTokenReference
     * @param agencyName {String} The name of the agency.
     * @param partnerAgencyId {String} The partner agency ID.
     * @param partnerAgencyName {String} The name of the partner agency.
     * @param tokenReference {String} The token reference associated with the partner agency.
     */
    constructor(agencyName, partnerAgencyId, partnerAgencyName, tokenReference) { 
        
        AuthTokenReference.initialize(this, agencyName, partnerAgencyId, partnerAgencyName, tokenReference);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, agencyName, partnerAgencyId, partnerAgencyName, tokenReference) { 
        obj['agencyName'] = agencyName;
        obj['partnerAgencyId'] = partnerAgencyId;
        obj['partnerAgencyName'] = partnerAgencyName;
        obj['tokenReference'] = tokenReference;
    }

    /**
     * Constructs a <code>AuthTokenReference</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthTokenReference} obj Optional instance to populate.
     * @return {module:model/AuthTokenReference} The populated <code>AuthTokenReference</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthTokenReference();

            if (data.hasOwnProperty('agencyName')) {
                obj['agencyName'] = ApiClient.convertToType(data['agencyName'], 'String');
            }
            if (data.hasOwnProperty('partnerAgencyId')) {
                obj['partnerAgencyId'] = ApiClient.convertToType(data['partnerAgencyId'], 'String');
            }
            if (data.hasOwnProperty('partnerAgencyName')) {
                obj['partnerAgencyName'] = ApiClient.convertToType(data['partnerAgencyName'], 'String');
            }
            if (data.hasOwnProperty('tokenReference')) {
                obj['tokenReference'] = ApiClient.convertToType(data['tokenReference'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthTokenReference</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthTokenReference</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuthTokenReference.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['agencyName'] && !(typeof data['agencyName'] === 'string' || data['agencyName'] instanceof String)) {
            throw new Error("Expected the field `agencyName` to be a primitive type in the JSON string but got " + data['agencyName']);
        }
        // ensure the json data is a string
        if (data['partnerAgencyId'] && !(typeof data['partnerAgencyId'] === 'string' || data['partnerAgencyId'] instanceof String)) {
            throw new Error("Expected the field `partnerAgencyId` to be a primitive type in the JSON string but got " + data['partnerAgencyId']);
        }
        // ensure the json data is a string
        if (data['partnerAgencyName'] && !(typeof data['partnerAgencyName'] === 'string' || data['partnerAgencyName'] instanceof String)) {
            throw new Error("Expected the field `partnerAgencyName` to be a primitive type in the JSON string but got " + data['partnerAgencyName']);
        }
        // ensure the json data is a string
        if (data['tokenReference'] && !(typeof data['tokenReference'] === 'string' || data['tokenReference'] instanceof String)) {
            throw new Error("Expected the field `tokenReference` to be a primitive type in the JSON string but got " + data['tokenReference']);
        }

        return true;
    }


}

AuthTokenReference.RequiredProperties = ["agencyName", "partnerAgencyId", "partnerAgencyName", "tokenReference"];

/**
 * The name of the agency.
 * @member {String} agencyName
 */
AuthTokenReference.prototype['agencyName'] = undefined;

/**
 * The partner agency ID.
 * @member {String} partnerAgencyId
 */
AuthTokenReference.prototype['partnerAgencyId'] = undefined;

/**
 * The name of the partner agency.
 * @member {String} partnerAgencyName
 */
AuthTokenReference.prototype['partnerAgencyName'] = undefined;

/**
 * The token reference associated with the partner agency.
 * @member {String} tokenReference
 */
AuthTokenReference.prototype['tokenReference'] = undefined;






export default AuthTokenReference;

