/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthenticateBridgeLink200Response model module.
 * @module model/AuthenticateBridgeLink200Response
 * @version 3.0.0
 */
class AuthenticateBridgeLink200Response {
    /**
     * Constructs a new <code>AuthenticateBridgeLink200Response</code>.
     * The success response body.
     * @alias module:model/AuthenticateBridgeLink200Response
     * @param partnerAgencyId {String} The id of the Agency associated with the quote.
     * @param quoteId {String} The quoteId of the quote being bridged.
     */
    constructor(partnerAgencyId, quoteId) { 
        
        AuthenticateBridgeLink200Response.initialize(this, partnerAgencyId, quoteId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, partnerAgencyId, quoteId) { 
        obj['partnerAgencyId'] = partnerAgencyId;
        obj['quoteId'] = quoteId;
    }

    /**
     * Constructs a <code>AuthenticateBridgeLink200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthenticateBridgeLink200Response} obj Optional instance to populate.
     * @return {module:model/AuthenticateBridgeLink200Response} The populated <code>AuthenticateBridgeLink200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthenticateBridgeLink200Response();

            if (data.hasOwnProperty('agentId')) {
                obj['agentId'] = ApiClient.convertToType(data['agentId'], 'String');
            }
            if (data.hasOwnProperty('cancelUrl')) {
                obj['cancelUrl'] = ApiClient.convertToType(data['cancelUrl'], 'String');
            }
            if (data.hasOwnProperty('partnerAgencyId')) {
                obj['partnerAgencyId'] = ApiClient.convertToType(data['partnerAgencyId'], 'String');
            }
            if (data.hasOwnProperty('quoteId')) {
                obj['quoteId'] = ApiClient.convertToType(data['quoteId'], 'String');
            }
            if (data.hasOwnProperty('successUrl')) {
                obj['successUrl'] = ApiClient.convertToType(data['successUrl'], 'String');
            }
            if (data.hasOwnProperty('tokenReference')) {
                obj['tokenReference'] = ApiClient.convertToType(data['tokenReference'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthenticateBridgeLink200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthenticateBridgeLink200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuthenticateBridgeLink200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['agentId'] && !(typeof data['agentId'] === 'string' || data['agentId'] instanceof String)) {
            throw new Error("Expected the field `agentId` to be a primitive type in the JSON string but got " + data['agentId']);
        }
        // ensure the json data is a string
        if (data['cancelUrl'] && !(typeof data['cancelUrl'] === 'string' || data['cancelUrl'] instanceof String)) {
            throw new Error("Expected the field `cancelUrl` to be a primitive type in the JSON string but got " + data['cancelUrl']);
        }
        // ensure the json data is a string
        if (data['partnerAgencyId'] && !(typeof data['partnerAgencyId'] === 'string' || data['partnerAgencyId'] instanceof String)) {
            throw new Error("Expected the field `partnerAgencyId` to be a primitive type in the JSON string but got " + data['partnerAgencyId']);
        }
        // ensure the json data is a string
        if (data['quoteId'] && !(typeof data['quoteId'] === 'string' || data['quoteId'] instanceof String)) {
            throw new Error("Expected the field `quoteId` to be a primitive type in the JSON string but got " + data['quoteId']);
        }
        // ensure the json data is a string
        if (data['successUrl'] && !(typeof data['successUrl'] === 'string' || data['successUrl'] instanceof String)) {
            throw new Error("Expected the field `successUrl` to be a primitive type in the JSON string but got " + data['successUrl']);
        }
        // ensure the json data is a string
        if (data['tokenReference'] && !(typeof data['tokenReference'] === 'string' || data['tokenReference'] instanceof String)) {
            throw new Error("Expected the field `tokenReference` to be a primitive type in the JSON string but got " + data['tokenReference']);
        }

        return true;
    }


}

AuthenticateBridgeLink200Response.RequiredProperties = ["partnerAgencyId", "quoteId"];

/**
 * The id of the agent of record for the associated quote.
 * @member {String} agentId
 */
AuthenticateBridgeLink200Response.prototype['agentId'] = undefined;

/**
 * The return path when a customer does not want to                         finish the bridged section. May be blank.
 * @member {String} cancelUrl
 */
AuthenticateBridgeLink200Response.prototype['cancelUrl'] = undefined;

/**
 * The id of the Agency associated with the quote.
 * @member {String} partnerAgencyId
 */
AuthenticateBridgeLink200Response.prototype['partnerAgencyId'] = undefined;

/**
 * The quoteId of the quote being bridged.
 * @member {String} quoteId
 */
AuthenticateBridgeLink200Response.prototype['quoteId'] = undefined;

/**
 * The return path when a customer finishes the bridged                         section. May be blank.
 * @member {String} successUrl
 */
AuthenticateBridgeLink200Response.prototype['successUrl'] = undefined;

/**
 * The reference for the token used to authenticate the bridge link.
 * @member {String} tokenReference
 */
AuthenticateBridgeLink200Response.prototype['tokenReference'] = undefined;






export default AuthenticateBridgeLink200Response;

