/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AvailableCoverage from './AvailableCoverage';

/**
 * The AvailableCoverages model module.
 * @module model/AvailableCoverages
 * @version 3.0.0
 */
class AvailableCoverages {
    /**
     * Constructs a new <code>AvailableCoverages</code>.
     * This object is meant to represent the current coverage selections associated with this Root provided quote.
     * @alias module:model/AvailableCoverages
     * @param policy {Array.<module:model/AvailableCoverage>} Coverages under this key apply to the whole policy.
     * @param vehicles {Array.<module:model/AvailableCoverage>} Coverages under this key apply to vehicles.
     * @param automotive {Array.<module:model/AvailableCoverage>} (Experimental) A flat array of all coverage selections, as a sibling to policy and vehicles. This is expected to eventually replace the policy/vehicles split. Please see your Root representative to request access to this experimental endpoint.
     */
    constructor(policy, vehicles, automotive) { 
        
        AvailableCoverages.initialize(this, policy, vehicles, automotive);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, policy, vehicles, automotive) { 
        obj['policy'] = policy;
        obj['vehicles'] = vehicles;
        obj['automotive'] = automotive;
    }

    /**
     * Constructs a <code>AvailableCoverages</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AvailableCoverages} obj Optional instance to populate.
     * @return {module:model/AvailableCoverages} The populated <code>AvailableCoverages</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AvailableCoverages();

            if (data.hasOwnProperty('policy')) {
                obj['policy'] = ApiClient.convertToType(data['policy'], [AvailableCoverage]);
            }
            if (data.hasOwnProperty('vehicles')) {
                obj['vehicles'] = ApiClient.convertToType(data['vehicles'], [AvailableCoverage]);
            }
            if (data.hasOwnProperty('automotive')) {
                obj['automotive'] = ApiClient.convertToType(data['automotive'], [AvailableCoverage]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AvailableCoverages</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AvailableCoverages</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AvailableCoverages.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['policy']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['policy'])) {
                throw new Error("Expected the field `policy` to be an array in the JSON data but got " + data['policy']);
            }
            // validate the optional field `policy` (array)
            for (const item of data['policy']) {
                AvailableCoverage.validateJSON(item);
            };
        }
        if (data['vehicles']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['vehicles'])) {
                throw new Error("Expected the field `vehicles` to be an array in the JSON data but got " + data['vehicles']);
            }
            // validate the optional field `vehicles` (array)
            for (const item of data['vehicles']) {
                AvailableCoverage.validateJSON(item);
            };
        }
        if (data['automotive']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['automotive'])) {
                throw new Error("Expected the field `automotive` to be an array in the JSON data but got " + data['automotive']);
            }
            // validate the optional field `automotive` (array)
            for (const item of data['automotive']) {
                AvailableCoverage.validateJSON(item);
            };
        }

        return true;
    }


}

AvailableCoverages.RequiredProperties = ["policy", "vehicles", "automotive"];

/**
 * Coverages under this key apply to the whole policy.
 * @member {Array.<module:model/AvailableCoverage>} policy
 */
AvailableCoverages.prototype['policy'] = undefined;

/**
 * Coverages under this key apply to vehicles.
 * @member {Array.<module:model/AvailableCoverage>} vehicles
 */
AvailableCoverages.prototype['vehicles'] = undefined;

/**
 * (Experimental) A flat array of all coverage selections, as a sibling to policy and vehicles. This is expected to eventually replace the policy/vehicles split. Please see your Root representative to request access to this experimental endpoint.
 * @member {Array.<module:model/AvailableCoverage>} automotive
 */
AvailableCoverages.prototype['automotive'] = undefined;






export default AvailableCoverages;

