/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AvailableCoverageAttributeSelectionsInner from './AvailableCoverageAttributeSelectionsInner';

/**
 * The AvailableCoverageAttribute model module.
 * @module model/AvailableCoverageAttribute
 * @version 3.0.0
 */
class AvailableCoverageAttribute {
    /**
     * Constructs a new <code>AvailableCoverageAttribute</code>.
     * A single attribute associated with a coverage.
     * @alias module:model/AvailableCoverageAttribute
     * @param kind {module:model/AvailableCoverageAttribute.KindEnum} A discriminator indicating what kind of attribute this describes.
     * @param type {module:model/AvailableCoverageAttribute.TypeEnum} (Experimental) A discriminator indicating the true type of this attribute (declined, deductible, limits, or modifier), as `kind` may in the future be used as a more specific unique identifier. Please see your Root representative to request access to this experimental endpoint.
     * @param name {String} A human readable version of the kind.
     * @param longDescription {String} (Experimental) A more detailed human readable description of the coverage attribute. Please see your Root representative to request access to this experimental endpoint.
     * @param selectableBy {module:model/AvailableCoverageAttribute.SelectableByEnum} (Experimental) The level at which a customer can select this coverage attribute ('policy', 'vehicle', or 'none'). Please see your Root representative to request access to this experimental endpoint.
     */
    constructor(kind, type, name, longDescription, selectableBy) { 
        
        AvailableCoverageAttribute.initialize(this, kind, type, name, longDescription, selectableBy);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, kind, type, name, longDescription, selectableBy) { 
        obj['kind'] = kind;
        obj['type'] = type;
        obj['name'] = name;
        obj['longDescription'] = longDescription;
        obj['selectableBy'] = selectableBy;
    }

    /**
     * Constructs a <code>AvailableCoverageAttribute</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AvailableCoverageAttribute} obj Optional instance to populate.
     * @return {module:model/AvailableCoverageAttribute} The populated <code>AvailableCoverageAttribute</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AvailableCoverageAttribute();

            if (data.hasOwnProperty('kind')) {
                obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('longDescription')) {
                obj['longDescription'] = ApiClient.convertToType(data['longDescription'], 'String');
            }
            if (data.hasOwnProperty('selectableBy')) {
                obj['selectableBy'] = ApiClient.convertToType(data['selectableBy'], 'String');
            }
            if (data.hasOwnProperty('selections')) {
                obj['selections'] = ApiClient.convertToType(data['selections'], [AvailableCoverageAttributeSelectionsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AvailableCoverageAttribute</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AvailableCoverageAttribute</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AvailableCoverageAttribute.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['kind'] && !(typeof data['kind'] === 'string' || data['kind'] instanceof String)) {
            throw new Error("Expected the field `kind` to be a primitive type in the JSON string but got " + data['kind']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['longDescription'] && !(typeof data['longDescription'] === 'string' || data['longDescription'] instanceof String)) {
            throw new Error("Expected the field `longDescription` to be a primitive type in the JSON string but got " + data['longDescription']);
        }
        // ensure the json data is a string
        if (data['selectableBy'] && !(typeof data['selectableBy'] === 'string' || data['selectableBy'] instanceof String)) {
            throw new Error("Expected the field `selectableBy` to be a primitive type in the JSON string but got " + data['selectableBy']);
        }
        if (data['selections']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['selections'])) {
                throw new Error("Expected the field `selections` to be an array in the JSON data but got " + data['selections']);
            }
            // validate the optional field `selections` (array)
            for (const item of data['selections']) {
                AvailableCoverageAttributeSelectionsInner.validateJSON(item);
            };
        }

        return true;
    }


}

AvailableCoverageAttribute.RequiredProperties = ["kind", "type", "name", "longDescription", "selectableBy"];

/**
 * A discriminator indicating what kind of attribute this describes.
 * @member {module:model/AvailableCoverageAttribute.KindEnum} kind
 */
AvailableCoverageAttribute.prototype['kind'] = undefined;

/**
 * (Experimental) A discriminator indicating the true type of this attribute (declined, deductible, limits, or modifier), as `kind` may in the future be used as a more specific unique identifier. Please see your Root representative to request access to this experimental endpoint.
 * @member {module:model/AvailableCoverageAttribute.TypeEnum} type
 */
AvailableCoverageAttribute.prototype['type'] = undefined;

/**
 * A human readable version of the kind.
 * @member {String} name
 */
AvailableCoverageAttribute.prototype['name'] = undefined;

/**
 * (Experimental) A more detailed human readable description of the coverage attribute. Please see your Root representative to request access to this experimental endpoint.
 * @member {String} longDescription
 */
AvailableCoverageAttribute.prototype['longDescription'] = undefined;

/**
 * (Experimental) The level at which a customer can select this coverage attribute ('policy', 'vehicle', or 'none'). Please see your Root representative to request access to this experimental endpoint.
 * @member {module:model/AvailableCoverageAttribute.SelectableByEnum} selectableBy
 */
AvailableCoverageAttribute.prototype['selectableBy'] = undefined;

/**
 * All possible attribute selections for the current market.
 * @member {Array.<module:model/AvailableCoverageAttributeSelectionsInner>} selections
 */
AvailableCoverageAttribute.prototype['selections'] = undefined;





/**
 * Allowed values for the <code>kind</code> property.
 * @enum {String}
 * @readonly
 */
AvailableCoverageAttribute['KindEnum'] = {

    /**
     * value: "declined"
     * @const
     */
    "declined": "declined",

    /**
     * value: "deductible"
     * @const
     */
    "deductible": "deductible",

    /**
     * value: "limits"
     * @const
     */
    "limits": "limits",

    /**
     * value: "tort_selection"
     * @const
     */
    "tort_selection": "tort_selection",

    /**
     * value: "conversion_modifier"
     * @const
     */
    "conversion_modifier": "conversion_modifier",

    /**
     * value: "enhanced_modifier"
     * @const
     */
    "enhanced_modifier": "enhanced_modifier",

    /**
     * value: "income_loss_modifier"
     * @const
     */
    "income_loss_modifier": "income_loss_modifier",

    /**
     * value: "full_glass_modifier"
     * @const
     */
    "full_glass_modifier": "full_glass_modifier",

    /**
     * value: "resident_relatives_included_modifier"
     * @const
     */
    "resident_relatives_included_modifier": "resident_relatives_included_modifier",

    /**
     * value: "stacked_modifier"
     * @const
     */
    "stacked_modifier": "stacked_modifier",

    /**
     * value: "work_loss_excluded_modifier"
     * @const
     */
    "work_loss_excluded_modifier": "work_loss_excluded_modifier",

    /**
     * value: "supplemental_modifier"
     * @const
     */
    "supplemental_modifier": "supplemental_modifier",

    /**
     * value: "extra_ordinary_medical_benefits_modifier"
     * @const
     */
    "extra_ordinary_medical_benefits_modifier": "extra_ordinary_medical_benefits_modifier"
};


/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
AvailableCoverageAttribute['TypeEnum'] = {

    /**
     * value: "deductible"
     * @const
     */
    "deductible": "deductible",

    /**
     * value: "limits"
     * @const
     */
    "limits": "limits",

    /**
     * value: "modifier"
     * @const
     */
    "modifier": "modifier",

    /**
     * value: "declined"
     * @const
     */
    "declined": "declined"
};


/**
 * Allowed values for the <code>selectableBy</code> property.
 * @enum {String}
 * @readonly
 */
AvailableCoverageAttribute['SelectableByEnum'] = {

    /**
     * value: "policy"
     * @const
     */
    "policy": "policy",

    /**
     * value: "vehicle"
     * @const
     */
    "vehicle": "vehicle",

    /**
     * value: "none"
     * @const
     */
    "none": "none"
};



export default AvailableCoverageAttribute;

