/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiDateTimeValue from './ApiDateTimeValue';
import ApiPaymentMethodValue from './ApiPaymentMethodValue';

/**
 * The BindErrorResponse model module.
 * @module model/BindErrorResponse
 * @version 3.0.0
 */
class BindErrorResponse {
    /**
     * Constructs a new <code>BindErrorResponse</code>.
     * The information used to bind a quote.
     * @alias module:model/BindErrorResponse
     * @param paymentMethod {module:model/ApiPaymentMethodValue} 
     * @param policyEffectiveDate {module:model/ApiDateTimeValue} 
     */
    constructor(paymentMethod, policyEffectiveDate) { 
        
        BindErrorResponse.initialize(this, paymentMethod, policyEffectiveDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, paymentMethod, policyEffectiveDate) { 
        obj['paymentMethod'] = paymentMethod;
        obj['policyEffectiveDate'] = policyEffectiveDate;
    }

    /**
     * Constructs a <code>BindErrorResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BindErrorResponse} obj Optional instance to populate.
     * @return {module:model/BindErrorResponse} The populated <code>BindErrorResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BindErrorResponse();

            if (data.hasOwnProperty('paymentMethod')) {
                obj['paymentMethod'] = ApiPaymentMethodValue.constructFromObject(data['paymentMethod']);
            }
            if (data.hasOwnProperty('policyEffectiveDate')) {
                obj['policyEffectiveDate'] = ApiDateTimeValue.constructFromObject(data['policyEffectiveDate']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BindErrorResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BindErrorResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BindErrorResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `paymentMethod`
        if (data['paymentMethod']) { // data not null
          ApiPaymentMethodValue.validateJSON(data['paymentMethod']);
        }
        // validate the optional field `policyEffectiveDate`
        if (data['policyEffectiveDate']) { // data not null
          ApiDateTimeValue.validateJSON(data['policyEffectiveDate']);
        }

        return true;
    }


}

BindErrorResponse.RequiredProperties = ["paymentMethod", "policyEffectiveDate"];

/**
 * @member {module:model/ApiPaymentMethodValue} paymentMethod
 */
BindErrorResponse.prototype['paymentMethod'] = undefined;

/**
 * @member {module:model/ApiDateTimeValue} policyEffectiveDate
 */
BindErrorResponse.prototype['policyEffectiveDate'] = undefined;






export default BindErrorResponse;

