/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiPaymentMethod from './ApiPaymentMethod';
import AttributionParameters from './AttributionParameters';

/**
 * The BindRequestParameters model module.
 * @module model/BindRequestParameters
 * @version 3.0.0
 */
class BindRequestParameters {
    /**
     * Constructs a new <code>BindRequestParameters</code>.
     * The information used to bind a quote.
     * @alias module:model/BindRequestParameters
     * @param paymentMethod {module:model/ApiPaymentMethod} 
     * @param policyEffectiveDate {Date} The date the policy is effective as of.
     */
    constructor(paymentMethod, policyEffectiveDate) { 
        
        BindRequestParameters.initialize(this, paymentMethod, policyEffectiveDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, paymentMethod, policyEffectiveDate) { 
        obj['paymentMethod'] = paymentMethod;
        obj['policyEffectiveDate'] = policyEffectiveDate;
    }

    /**
     * Constructs a <code>BindRequestParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BindRequestParameters} obj Optional instance to populate.
     * @return {module:model/BindRequestParameters} The populated <code>BindRequestParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BindRequestParameters();

            if (data.hasOwnProperty('attributionParameters')) {
                obj['attributionParameters'] = AttributionParameters.constructFromObject(data['attributionParameters']);
            }
            if (data.hasOwnProperty('paymentMethod')) {
                obj['paymentMethod'] = ApiPaymentMethod.constructFromObject(data['paymentMethod']);
            }
            if (data.hasOwnProperty('policyEffectiveDate')) {
                obj['policyEffectiveDate'] = ApiClient.convertToType(data['policyEffectiveDate'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BindRequestParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BindRequestParameters</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BindRequestParameters.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `attributionParameters`
        if (data['attributionParameters']) { // data not null
          AttributionParameters.validateJSON(data['attributionParameters']);
        }
        // validate the optional field `paymentMethod`
        if (data['paymentMethod']) { // data not null
          ApiPaymentMethod.validateJSON(data['paymentMethod']);
        }

        return true;
    }


}

BindRequestParameters.RequiredProperties = ["paymentMethod", "policyEffectiveDate"];

/**
 * @member {module:model/AttributionParameters} attributionParameters
 */
BindRequestParameters.prototype['attributionParameters'] = undefined;

/**
 * @member {module:model/ApiPaymentMethod} paymentMethod
 */
BindRequestParameters.prototype['paymentMethod'] = undefined;

/**
 * The date the policy is effective as of.
 * @member {Date} policyEffectiveDate
 */
BindRequestParameters.prototype['policyEffectiveDate'] = undefined;






export default BindRequestParameters;

