/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Charge model module.
 * @module model/Charge
 * @version 3.0.0
 */
class Charge {
    /**
     * Constructs a new <code>Charge</code>.
     * A single charge or line item for a payment.
     * @alias module:model/Charge
     * @param name {String} The name of the charge.
     * @param amountInCents {Number} The amount this charge entails in USD cents.
     * @param isFee {Boolean} This charge is a fee.
     * @param type {module:model/Charge.TypeEnum} The kind of this charge.
     */
    constructor(name, amountInCents, isFee, type) { 
        
        Charge.initialize(this, name, amountInCents, isFee, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, amountInCents, isFee, type) { 
        obj['name'] = name;
        obj['amountInCents'] = amountInCents;
        obj['isFee'] = isFee;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>Charge</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Charge} obj Optional instance to populate.
     * @return {module:model/Charge} The populated <code>Charge</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Charge();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('amountInCents')) {
                obj['amountInCents'] = ApiClient.convertToType(data['amountInCents'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('isFee')) {
                obj['isFee'] = ApiClient.convertToType(data['isFee'], 'Boolean');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Charge</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Charge</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Charge.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}

Charge.RequiredProperties = ["name", "amountInCents", "isFee", "type"];

/**
 * The name of the charge.
 * @member {String} name
 */
Charge.prototype['name'] = undefined;

/**
 * The amount this charge entails in USD cents.
 * @member {Number} amountInCents
 */
Charge.prototype['amountInCents'] = undefined;

/**
 * A description of this charge.
 * @member {String} description
 */
Charge.prototype['description'] = undefined;

/**
 * This charge is a fee.
 * @member {Boolean} isFee
 */
Charge.prototype['isFee'] = undefined;

/**
 * The kind of this charge.
 * @member {module:model/Charge.TypeEnum} type
 */
Charge.prototype['type'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Charge['TypeEnum'] = {

    /**
     * value: "balance_alignment"
     * @const
     */
    "balance_alignment": "balance_alignment",

    /**
     * value: "auto_payment_credit"
     * @const
     */
    "auto_payment_credit": "auto_payment_credit",

    /**
     * value: "installment_fee"
     * @const
     */
    "installment_fee": "installment_fee",

    /**
     * value: "late_fee"
     * @const
     */
    "late_fee": "late_fee",

    /**
     * value: "monthly_policy_fee"
     * @const
     */
    "monthly_policy_fee": "monthly_policy_fee",

    /**
     * value: "new_vehicle_fee"
     * @const
     */
    "new_vehicle_fee": "new_vehicle_fee",

    /**
     * value: "past_due"
     * @const
     */
    "past_due": "past_due",

    /**
     * value: "policy_fee"
     * @const
     */
    "policy_fee": "policy_fee",

    /**
     * value: "premium"
     * @const
     */
    "premium": "premium",

    /**
     * value: "reinstatement_fee"
     * @const
     */
    "reinstatement_fee": "reinstatement_fee",

    /**
     * value: "renewal_policy_fee"
     * @const
     */
    "renewal_policy_fee": "renewal_policy_fee",

    /**
     * value: "rewrite_fee"
     * @const
     */
    "rewrite_fee": "rewrite_fee"
};



export default Charge;

