/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PolicyCoveragePatchParameters from './PolicyCoveragePatchParameters';
import VehicleCoveragesPatchParameters from './VehicleCoveragesPatchParameters';

/**
 * The CoveragesPatchParameters model module.
 * @module model/CoveragesPatchParameters
 * @version 3.0.0
 */
class CoveragesPatchParameters {
    /**
     * Constructs a new <code>CoveragesPatchParameters</code>.
     * This object is meant to represent the current coverage selections associated with this quote.
     * @alias module:model/CoveragesPatchParameters
     */
    constructor() { 
        
        CoveragesPatchParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CoveragesPatchParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CoveragesPatchParameters} obj Optional instance to populate.
     * @return {module:model/CoveragesPatchParameters} The populated <code>CoveragesPatchParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CoveragesPatchParameters();

            if (data.hasOwnProperty('policy')) {
                obj['policy'] = ApiClient.convertToType(data['policy'], {'String': PolicyCoveragePatchParameters});
            }
            if (data.hasOwnProperty('vehicles')) {
                obj['vehicles'] = ApiClient.convertToType(data['vehicles'], {'String': VehicleCoveragesPatchParameters});
            }
            if (data.hasOwnProperty('automotive')) {
                obj['automotive'] = ApiClient.convertToType(data['automotive'], {'String': PolicyCoveragePatchParameters});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CoveragesPatchParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CoveragesPatchParameters</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * The object's key is the index of the coverage within the policy array, and the value is an object with the parameters to be updated. If value is null, the coverage will be deleted.
 * @member {Object.<String, module:model/PolicyCoveragePatchParameters>} policy
 */
CoveragesPatchParameters.prototype['policy'] = undefined;

/**
 * The object's key is the index of the vehicle within the vehicles array, and the value is an object with the parameters to be updated. If value is null, the coverages for that vehicle will be deleted.
 * @member {Object.<String, module:model/VehicleCoveragesPatchParameters>} vehicles
 */
CoveragesPatchParameters.prototype['vehicles'] = undefined;

/**
 * (Experimental) The object's key is the index of the coverage within the automotive array, and the value is an object with the parameters to be updated. If value is null, the coverage will be deleted. Please see your Root representative to request access to this experimental endpoint.
 * @member {Object.<String, module:model/PolicyCoveragePatchParameters>} automotive
 */
CoveragesPatchParameters.prototype['automotive'] = undefined;






export default CoveragesPatchParameters;

