/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttributionEvent from './AttributionEvent';
import Quote from './Quote';

/**
 * The CreateQuote201ResponseAnyOf model module.
 * @module model/CreateQuote201ResponseAnyOf
 * @version 3.0.0
 */
class CreateQuote201ResponseAnyOf {
    /**
     * Constructs a new <code>CreateQuote201ResponseAnyOf</code>.
     * The success response body.
     * @alias module:model/CreateQuote201ResponseAnyOf
     * @param quote {module:model/Quote} 
     * @param attributionEvents {Array.<module:model/AttributionEvent>} The attribution events associated with this quote.
     */
    constructor(quote, attributionEvents) { 
        
        CreateQuote201ResponseAnyOf.initialize(this, quote, attributionEvents);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, quote, attributionEvents) { 
        obj['quote'] = quote;
        obj['attributionEvents'] = attributionEvents;
    }

    /**
     * Constructs a <code>CreateQuote201ResponseAnyOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateQuote201ResponseAnyOf} obj Optional instance to populate.
     * @return {module:model/CreateQuote201ResponseAnyOf} The populated <code>CreateQuote201ResponseAnyOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateQuote201ResponseAnyOf();

            if (data.hasOwnProperty('quote')) {
                obj['quote'] = Quote.constructFromObject(data['quote']);
            }
            if (data.hasOwnProperty('attributionEvents')) {
                obj['attributionEvents'] = ApiClient.convertToType(data['attributionEvents'], [AttributionEvent]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateQuote201ResponseAnyOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateQuote201ResponseAnyOf</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateQuote201ResponseAnyOf.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `quote`
        if (data['quote']) { // data not null
          Quote.validateJSON(data['quote']);
        }
        if (data['attributionEvents']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['attributionEvents'])) {
                throw new Error("Expected the field `attributionEvents` to be an array in the JSON data but got " + data['attributionEvents']);
            }
            // validate the optional field `attributionEvents` (array)
            for (const item of data['attributionEvents']) {
                AttributionEvent.validateJSON(item);
            };
        }

        return true;
    }


}

CreateQuote201ResponseAnyOf.RequiredProperties = ["quote", "attributionEvents"];

/**
 * @member {module:model/Quote} quote
 */
CreateQuote201ResponseAnyOf.prototype['quote'] = undefined;

/**
 * The attribution events associated with this quote.
 * @member {Array.<module:model/AttributionEvent>} attributionEvents
 */
CreateQuote201ResponseAnyOf.prototype['attributionEvents'] = undefined;






export default CreateQuote201ResponseAnyOf;

