/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttributionEvent from './AttributionEvent';
import Quote from './Quote';

/**
 * The CreateQuoteFromPolicy201Response model module.
 * @module model/CreateQuoteFromPolicy201Response
 * @version 3.0.0
 */
class CreateQuoteFromPolicy201Response {
    /**
     * Constructs a new <code>CreateQuoteFromPolicy201Response</code>.
     * @alias module:model/CreateQuoteFromPolicy201Response
     */
    constructor() { 
        
        CreateQuoteFromPolicy201Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateQuoteFromPolicy201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateQuoteFromPolicy201Response} obj Optional instance to populate.
     * @return {module:model/CreateQuoteFromPolicy201Response} The populated <code>CreateQuoteFromPolicy201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateQuoteFromPolicy201Response();

            if (data.hasOwnProperty('quote')) {
                obj['quote'] = Quote.constructFromObject(data['quote']);
            }
            if (data.hasOwnProperty('attributionEvents')) {
                obj['attributionEvents'] = ApiClient.convertToType(data['attributionEvents'], [AttributionEvent]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateQuoteFromPolicy201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateQuoteFromPolicy201Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `quote`
        if (data['quote']) { // data not null
          Quote.validateJSON(data['quote']);
        }
        if (data['attributionEvents']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['attributionEvents'])) {
                throw new Error("Expected the field `attributionEvents` to be an array in the JSON data but got " + data['attributionEvents']);
            }
            // validate the optional field `attributionEvents` (array)
            for (const item of data['attributionEvents']) {
                AttributionEvent.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:model/Quote} quote
 */
CreateQuoteFromPolicy201Response.prototype['quote'] = undefined;

/**
 * @member {Array.<module:model/AttributionEvent>} attributionEvents
 */
CreateQuoteFromPolicy201Response.prototype['attributionEvents'] = undefined;






export default CreateQuoteFromPolicy201Response;

