/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeclinedOption model module.
 * @module model/DeclinedOption
 * @version 3.0.0
 */
class DeclinedOption {
    /**
     * Constructs a new <code>DeclinedOption</code>.
     * An attribute representing if this coverage is declined. Note if declined all other attributes are ignored.
     * @alias module:model/DeclinedOption
     * @param declined {Boolean} This coverage is declined.
     * @param description {String} A human readable description of the declined status.
     * @param longDescription {String} (Experimental) A more detailed human readable description of the declined status. Please see your Root representative to request access to this experimental endpoint.
     */
    constructor(declined, description, longDescription) { 
        
        DeclinedOption.initialize(this, declined, description, longDescription);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, declined, description, longDescription) { 
        obj['declined'] = declined;
        obj['description'] = description;
        obj['longDescription'] = longDescription;
    }

    /**
     * Constructs a <code>DeclinedOption</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeclinedOption} obj Optional instance to populate.
     * @return {module:model/DeclinedOption} The populated <code>DeclinedOption</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeclinedOption();

            if (data.hasOwnProperty('declined')) {
                obj['declined'] = ApiClient.convertToType(data['declined'], 'Boolean');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('longDescription')) {
                obj['longDescription'] = ApiClient.convertToType(data['longDescription'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeclinedOption</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeclinedOption</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeclinedOption.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['longDescription'] && !(typeof data['longDescription'] === 'string' || data['longDescription'] instanceof String)) {
            throw new Error("Expected the field `longDescription` to be a primitive type in the JSON string but got " + data['longDescription']);
        }

        return true;
    }


}

DeclinedOption.RequiredProperties = ["declined", "description", "longDescription"];

/**
 * This coverage is declined.
 * @member {Boolean} declined
 */
DeclinedOption.prototype['declined'] = undefined;

/**
 * A human readable description of the declined status.
 * @member {String} description
 */
DeclinedOption.prototype['description'] = undefined;

/**
 * (Experimental) A more detailed human readable description of the declined status. Please see your Root representative to request access to this experimental endpoint.
 * @member {String} longDescription
 */
DeclinedOption.prototype['longDescription'] = undefined;






export default DeclinedOption;

