/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DriverVehicleAssignmentParameters model module.
 * @module model/DriverVehicleAssignmentParameters
 * @version 3.0.0
 */
class DriverVehicleAssignmentParameters {
    /**
     * Constructs a new <code>DriverVehicleAssignmentParameters</code>.
     * A single association between a driver and a vehicle indicating the driver&#39;s usage related to the vehicle.
     * @alias module:model/DriverVehicleAssignmentParameters
     */
    constructor() { 
        
        DriverVehicleAssignmentParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DriverVehicleAssignmentParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DriverVehicleAssignmentParameters} obj Optional instance to populate.
     * @return {module:model/DriverVehicleAssignmentParameters} The populated <code>DriverVehicleAssignmentParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DriverVehicleAssignmentParameters();

            if (data.hasOwnProperty('driverId')) {
                obj['driverId'] = ApiClient.convertToType(data['driverId'], 'String');
            }
            if (data.hasOwnProperty('primaryVehicle')) {
                obj['primaryVehicle'] = ApiClient.convertToType(data['primaryVehicle'], 'Boolean');
            }
            if (data.hasOwnProperty('vin')) {
                obj['vin'] = ApiClient.convertToType(data['vin'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DriverVehicleAssignmentParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DriverVehicleAssignmentParameters</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['driverId'] && !(typeof data['driverId'] === 'string' || data['driverId'] instanceof String)) {
            throw new Error("Expected the field `driverId` to be a primitive type in the JSON string but got " + data['driverId']);
        }
        // ensure the json data is a string
        if (data['vin'] && !(typeof data['vin'] === 'string' || data['vin'] instanceof String)) {
            throw new Error("Expected the field `vin` to be a primitive type in the JSON string but got " + data['vin']);
        }

        return true;
    }


}



/**
 * The ID of the driver in this association.
 * @member {String} driverId
 */
DriverVehicleAssignmentParameters.prototype['driverId'] = undefined;

/**
 * This vehicle is this driver's primary use vehicle.
 * @member {Boolean} primaryVehicle
 */
DriverVehicleAssignmentParameters.prototype['primaryVehicle'] = undefined;

/**
 * The VIN for the vehicle in this association.
 * @member {String} vin
 */
DriverVehicleAssignmentParameters.prototype['vin'] = undefined;






export default DriverVehicleAssignmentParameters;

