/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiBooleanValue from './ApiBooleanValue';
import ApiDateValue from './ApiDateValue';
import ApiDriverGenderValue from './ApiDriverGenderValue';
import ApiDriverMaritalStatusValue from './ApiDriverMaritalStatusValue';
import ApiDriverStatusValue from './ApiDriverStatusValue';
import ApiDriverYearsLicensedValue from './ApiDriverYearsLicensedValue';
import ApiIntegerValue from './ApiIntegerValue';
import ApiMarketValue from './ApiMarketValue';
import ApiStringValue from './ApiStringValue';
import ApiUuidValue from './ApiUuidValue';
import DriverCredit from './DriverCredit';
import PrefillReportIdentifier from './PrefillReportIdentifier';
import UnderwritingRequirement from './UnderwritingRequirement';

/**
 * The Driver model module.
 * @module model/Driver
 * @version 3.0.0
 */
class Driver {
    /**
     * Constructs a new <code>Driver</code>.
     * A single driver associated with this quote.
     * @alias module:model/Driver
     * @param accidentPreventionCourse {module:model/ApiBooleanValue} 
     * @param activeDutyMilitary {module:model/ApiBooleanValue} 
     * @param ageWhenLicensed {module:model/ApiIntegerValue} 
     * @param collegeGraduate {module:model/ApiBooleanValue} 
     * @param dob {module:model/ApiDateValue} 
     * @param firstName {module:model/ApiStringValue} 
     * @param gender {module:model/ApiDriverGenderValue} 
     * @param goodStudent {module:model/ApiBooleanValue} 
     * @param id {module:model/ApiUuidValue} 
     * @param lastName {module:model/ApiStringValue} 
     * @param licenseNumber {module:model/ApiStringValue} 
     * @param licenseState {module:model/ApiMarketValue} 
     * @param maritalStatus {module:model/ApiDriverMaritalStatusValue} 
     * @param nameSuffix {module:model/ApiStringValue} 
     * @param nationalGuardMember {module:model/ApiBooleanValue} 
     * @param occasionalDriver {module:model/ApiBooleanValue} 
     * @param prefillDriverId {module:model/ApiUuidValue} 
     * @param prefillReportIdentifiers {Array.<module:model/PrefillReportIdentifier>} The unique identifiers for the associated prefilled report.
     * @param refresherPreventionCourse {module:model/ApiBooleanValue} 
     * @param status {module:model/ApiDriverStatusValue} 
     * @param yearsLicensedSelection {module:model/ApiDriverYearsLicensedValue} 
     */
    constructor(accidentPreventionCourse, activeDutyMilitary, ageWhenLicensed, collegeGraduate, dob, firstName, gender, goodStudent, id, lastName, licenseNumber, licenseState, maritalStatus, nameSuffix, nationalGuardMember, occasionalDriver, prefillDriverId, prefillReportIdentifiers, refresherPreventionCourse, status, yearsLicensedSelection) { 
        
        Driver.initialize(this, accidentPreventionCourse, activeDutyMilitary, ageWhenLicensed, collegeGraduate, dob, firstName, gender, goodStudent, id, lastName, licenseNumber, licenseState, maritalStatus, nameSuffix, nationalGuardMember, occasionalDriver, prefillDriverId, prefillReportIdentifiers, refresherPreventionCourse, status, yearsLicensedSelection);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, accidentPreventionCourse, activeDutyMilitary, ageWhenLicensed, collegeGraduate, dob, firstName, gender, goodStudent, id, lastName, licenseNumber, licenseState, maritalStatus, nameSuffix, nationalGuardMember, occasionalDriver, prefillDriverId, prefillReportIdentifiers, refresherPreventionCourse, status, yearsLicensedSelection) { 
        obj['accidentPreventionCourse'] = accidentPreventionCourse;
        obj['activeDutyMilitary'] = activeDutyMilitary;
        obj['ageWhenLicensed'] = ageWhenLicensed;
        obj['collegeGraduate'] = collegeGraduate;
        obj['dob'] = dob;
        obj['firstName'] = firstName;
        obj['gender'] = gender;
        obj['goodStudent'] = goodStudent;
        obj['id'] = id;
        obj['lastName'] = lastName;
        obj['licenseNumber'] = licenseNumber;
        obj['licenseState'] = licenseState;
        obj['maritalStatus'] = maritalStatus;
        obj['nameSuffix'] = nameSuffix;
        obj['nationalGuardMember'] = nationalGuardMember;
        obj['occasionalDriver'] = occasionalDriver;
        obj['prefillDriverId'] = prefillDriverId;
        obj['prefillReportIdentifiers'] = prefillReportIdentifiers;
        obj['refresherPreventionCourse'] = refresherPreventionCourse;
        obj['status'] = status;
        obj['yearsLicensedSelection'] = yearsLicensedSelection;
    }

    /**
     * Constructs a <code>Driver</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Driver} obj Optional instance to populate.
     * @return {module:model/Driver} The populated <code>Driver</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Driver();

            if (data.hasOwnProperty('accidentPreventionCourse')) {
                obj['accidentPreventionCourse'] = ApiBooleanValue.constructFromObject(data['accidentPreventionCourse']);
            }
            if (data.hasOwnProperty('activeDutyMilitary')) {
                obj['activeDutyMilitary'] = ApiBooleanValue.constructFromObject(data['activeDutyMilitary']);
            }
            if (data.hasOwnProperty('ageWhenLicensed')) {
                obj['ageWhenLicensed'] = ApiIntegerValue.constructFromObject(data['ageWhenLicensed']);
            }
            if (data.hasOwnProperty('collegeGraduate')) {
                obj['collegeGraduate'] = ApiBooleanValue.constructFromObject(data['collegeGraduate']);
            }
            if (data.hasOwnProperty('credit')) {
                obj['credit'] = DriverCredit.constructFromObject(data['credit']);
            }
            if (data.hasOwnProperty('dob')) {
                obj['dob'] = ApiDateValue.constructFromObject(data['dob']);
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiStringValue.constructFromObject(data['firstName']);
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiDriverGenderValue.constructFromObject(data['gender']);
            }
            if (data.hasOwnProperty('goodStudent')) {
                obj['goodStudent'] = ApiBooleanValue.constructFromObject(data['goodStudent']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiUuidValue.constructFromObject(data['id']);
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiStringValue.constructFromObject(data['lastName']);
            }
            if (data.hasOwnProperty('licenseNumber')) {
                obj['licenseNumber'] = ApiStringValue.constructFromObject(data['licenseNumber']);
            }
            if (data.hasOwnProperty('licenseState')) {
                obj['licenseState'] = ApiMarketValue.constructFromObject(data['licenseState']);
            }
            if (data.hasOwnProperty('maritalStatus')) {
                obj['maritalStatus'] = ApiDriverMaritalStatusValue.constructFromObject(data['maritalStatus']);
            }
            if (data.hasOwnProperty('nameSuffix')) {
                obj['nameSuffix'] = ApiStringValue.constructFromObject(data['nameSuffix']);
            }
            if (data.hasOwnProperty('nationalGuardMember')) {
                obj['nationalGuardMember'] = ApiBooleanValue.constructFromObject(data['nationalGuardMember']);
            }
            if (data.hasOwnProperty('occasionalDriver')) {
                obj['occasionalDriver'] = ApiBooleanValue.constructFromObject(data['occasionalDriver']);
            }
            if (data.hasOwnProperty('prefillDriverId')) {
                obj['prefillDriverId'] = ApiUuidValue.constructFromObject(data['prefillDriverId']);
            }
            if (data.hasOwnProperty('prefillReportIdentifiers')) {
                obj['prefillReportIdentifiers'] = ApiClient.convertToType(data['prefillReportIdentifiers'], [PrefillReportIdentifier]);
            }
            if (data.hasOwnProperty('refresherPreventionCourse')) {
                obj['refresherPreventionCourse'] = ApiBooleanValue.constructFromObject(data['refresherPreventionCourse']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiDriverStatusValue.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('underwritingRequirements')) {
                obj['underwritingRequirements'] = ApiClient.convertToType(data['underwritingRequirements'], [UnderwritingRequirement]);
            }
            if (data.hasOwnProperty('yearsLicensedSelection')) {
                obj['yearsLicensedSelection'] = ApiDriverYearsLicensedValue.constructFromObject(data['yearsLicensedSelection']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Driver</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Driver</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Driver.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `accidentPreventionCourse`
        if (data['accidentPreventionCourse']) { // data not null
          ApiBooleanValue.validateJSON(data['accidentPreventionCourse']);
        }
        // validate the optional field `activeDutyMilitary`
        if (data['activeDutyMilitary']) { // data not null
          ApiBooleanValue.validateJSON(data['activeDutyMilitary']);
        }
        // validate the optional field `ageWhenLicensed`
        if (data['ageWhenLicensed']) { // data not null
          ApiIntegerValue.validateJSON(data['ageWhenLicensed']);
        }
        // validate the optional field `collegeGraduate`
        if (data['collegeGraduate']) { // data not null
          ApiBooleanValue.validateJSON(data['collegeGraduate']);
        }
        // validate the optional field `credit`
        if (data['credit']) { // data not null
          DriverCredit.validateJSON(data['credit']);
        }
        // validate the optional field `dob`
        if (data['dob']) { // data not null
          ApiDateValue.validateJSON(data['dob']);
        }
        // validate the optional field `firstName`
        if (data['firstName']) { // data not null
          ApiStringValue.validateJSON(data['firstName']);
        }
        // validate the optional field `gender`
        if (data['gender']) { // data not null
          ApiDriverGenderValue.validateJSON(data['gender']);
        }
        // validate the optional field `goodStudent`
        if (data['goodStudent']) { // data not null
          ApiBooleanValue.validateJSON(data['goodStudent']);
        }
        // validate the optional field `id`
        if (data['id']) { // data not null
          ApiUuidValue.validateJSON(data['id']);
        }
        // validate the optional field `lastName`
        if (data['lastName']) { // data not null
          ApiStringValue.validateJSON(data['lastName']);
        }
        // validate the optional field `licenseNumber`
        if (data['licenseNumber']) { // data not null
          ApiStringValue.validateJSON(data['licenseNumber']);
        }
        // validate the optional field `licenseState`
        if (data['licenseState']) { // data not null
          ApiMarketValue.validateJSON(data['licenseState']);
        }
        // validate the optional field `maritalStatus`
        if (data['maritalStatus']) { // data not null
          ApiDriverMaritalStatusValue.validateJSON(data['maritalStatus']);
        }
        // validate the optional field `nameSuffix`
        if (data['nameSuffix']) { // data not null
          ApiStringValue.validateJSON(data['nameSuffix']);
        }
        // validate the optional field `nationalGuardMember`
        if (data['nationalGuardMember']) { // data not null
          ApiBooleanValue.validateJSON(data['nationalGuardMember']);
        }
        // validate the optional field `occasionalDriver`
        if (data['occasionalDriver']) { // data not null
          ApiBooleanValue.validateJSON(data['occasionalDriver']);
        }
        // validate the optional field `prefillDriverId`
        if (data['prefillDriverId']) { // data not null
          ApiUuidValue.validateJSON(data['prefillDriverId']);
        }
        if (data['prefillReportIdentifiers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['prefillReportIdentifiers'])) {
                throw new Error("Expected the field `prefillReportIdentifiers` to be an array in the JSON data but got " + data['prefillReportIdentifiers']);
            }
            // validate the optional field `prefillReportIdentifiers` (array)
            for (const item of data['prefillReportIdentifiers']) {
                PrefillReportIdentifier.validateJSON(item);
            };
        }
        // validate the optional field `refresherPreventionCourse`
        if (data['refresherPreventionCourse']) { // data not null
          ApiBooleanValue.validateJSON(data['refresherPreventionCourse']);
        }
        // validate the optional field `status`
        if (data['status']) { // data not null
          ApiDriverStatusValue.validateJSON(data['status']);
        }
        if (data['underwritingRequirements']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['underwritingRequirements'])) {
                throw new Error("Expected the field `underwritingRequirements` to be an array in the JSON data but got " + data['underwritingRequirements']);
            }
            // validate the optional field `underwritingRequirements` (array)
            for (const item of data['underwritingRequirements']) {
                UnderwritingRequirement.validateJSON(item);
            };
        }
        // validate the optional field `yearsLicensedSelection`
        if (data['yearsLicensedSelection']) { // data not null
          ApiDriverYearsLicensedValue.validateJSON(data['yearsLicensedSelection']);
        }

        return true;
    }


}

Driver.RequiredProperties = ["accidentPreventionCourse", "activeDutyMilitary", "ageWhenLicensed", "collegeGraduate", "dob", "firstName", "gender", "goodStudent", "id", "lastName", "licenseNumber", "licenseState", "maritalStatus", "nameSuffix", "nationalGuardMember", "occasionalDriver", "prefillDriverId", "prefillReportIdentifiers", "refresherPreventionCourse", "status", "yearsLicensedSelection"];

/**
 * @member {module:model/ApiBooleanValue} accidentPreventionCourse
 */
Driver.prototype['accidentPreventionCourse'] = undefined;

/**
 * @member {module:model/ApiBooleanValue} activeDutyMilitary
 */
Driver.prototype['activeDutyMilitary'] = undefined;

/**
 * @member {module:model/ApiIntegerValue} ageWhenLicensed
 */
Driver.prototype['ageWhenLicensed'] = undefined;

/**
 * @member {module:model/ApiBooleanValue} collegeGraduate
 */
Driver.prototype['collegeGraduate'] = undefined;

/**
 * @member {module:model/DriverCredit} credit
 */
Driver.prototype['credit'] = undefined;

/**
 * @member {module:model/ApiDateValue} dob
 */
Driver.prototype['dob'] = undefined;

/**
 * @member {module:model/ApiStringValue} firstName
 */
Driver.prototype['firstName'] = undefined;

/**
 * @member {module:model/ApiDriverGenderValue} gender
 */
Driver.prototype['gender'] = undefined;

/**
 * @member {module:model/ApiBooleanValue} goodStudent
 */
Driver.prototype['goodStudent'] = undefined;

/**
 * @member {module:model/ApiUuidValue} id
 */
Driver.prototype['id'] = undefined;

/**
 * @member {module:model/ApiStringValue} lastName
 */
Driver.prototype['lastName'] = undefined;

/**
 * @member {module:model/ApiStringValue} licenseNumber
 */
Driver.prototype['licenseNumber'] = undefined;

/**
 * @member {module:model/ApiMarketValue} licenseState
 */
Driver.prototype['licenseState'] = undefined;

/**
 * @member {module:model/ApiDriverMaritalStatusValue} maritalStatus
 */
Driver.prototype['maritalStatus'] = undefined;

/**
 * @member {module:model/ApiStringValue} nameSuffix
 */
Driver.prototype['nameSuffix'] = undefined;

/**
 * @member {module:model/ApiBooleanValue} nationalGuardMember
 */
Driver.prototype['nationalGuardMember'] = undefined;

/**
 * @member {module:model/ApiBooleanValue} occasionalDriver
 */
Driver.prototype['occasionalDriver'] = undefined;

/**
 * @member {module:model/ApiUuidValue} prefillDriverId
 */
Driver.prototype['prefillDriverId'] = undefined;

/**
 * The unique identifiers for the associated prefilled report.
 * @member {Array.<module:model/PrefillReportIdentifier>} prefillReportIdentifiers
 */
Driver.prototype['prefillReportIdentifiers'] = undefined;

/**
 * @member {module:model/ApiBooleanValue} refresherPreventionCourse
 */
Driver.prototype['refresherPreventionCourse'] = undefined;

/**
 * @member {module:model/ApiDriverStatusValue} status
 */
Driver.prototype['status'] = undefined;

/**
 * The additional requirements that must be met before a policy including this driver can be fully underwritten. (Experimental)
 * @member {Array.<module:model/UnderwritingRequirement>} underwritingRequirements
 */
Driver.prototype['underwritingRequirements'] = undefined;

/**
 * @member {module:model/ApiDriverYearsLicensedValue} yearsLicensedSelection
 */
Driver.prototype['yearsLicensedSelection'] = undefined;






export default Driver;

