/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiBooleanValue from './ApiBooleanValue';
import ApiStringValue from './ApiStringValue';
import ApiUuidValue from './ApiUuidValue';

/**
 * The DriverVehicleAssignment model module.
 * @module model/DriverVehicleAssignment
 * @version 3.0.0
 */
class DriverVehicleAssignment {
    /**
     * Constructs a new <code>DriverVehicleAssignment</code>.
     * A single association between a driver and a vehicle indicating the driver&#39;s usage related to the vehicle.
     * @alias module:model/DriverVehicleAssignment
     * @param driverId {module:model/ApiUuidValue} 
     * @param primaryVehicle {module:model/ApiBooleanValue} 
     * @param vin {module:model/ApiStringValue} 
     */
    constructor(driverId, primaryVehicle, vin) { 
        
        DriverVehicleAssignment.initialize(this, driverId, primaryVehicle, vin);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, driverId, primaryVehicle, vin) { 
        obj['driverId'] = driverId;
        obj['primaryVehicle'] = primaryVehicle;
        obj['vin'] = vin;
    }

    /**
     * Constructs a <code>DriverVehicleAssignment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DriverVehicleAssignment} obj Optional instance to populate.
     * @return {module:model/DriverVehicleAssignment} The populated <code>DriverVehicleAssignment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DriverVehicleAssignment();

            if (data.hasOwnProperty('driverId')) {
                obj['driverId'] = ApiUuidValue.constructFromObject(data['driverId']);
            }
            if (data.hasOwnProperty('primaryVehicle')) {
                obj['primaryVehicle'] = ApiBooleanValue.constructFromObject(data['primaryVehicle']);
            }
            if (data.hasOwnProperty('vin')) {
                obj['vin'] = ApiStringValue.constructFromObject(data['vin']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DriverVehicleAssignment</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DriverVehicleAssignment</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DriverVehicleAssignment.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `driverId`
        if (data['driverId']) { // data not null
          ApiUuidValue.validateJSON(data['driverId']);
        }
        // validate the optional field `primaryVehicle`
        if (data['primaryVehicle']) { // data not null
          ApiBooleanValue.validateJSON(data['primaryVehicle']);
        }
        // validate the optional field `vin`
        if (data['vin']) { // data not null
          ApiStringValue.validateJSON(data['vin']);
        }

        return true;
    }


}

DriverVehicleAssignment.RequiredProperties = ["driverId", "primaryVehicle", "vin"];

/**
 * @member {module:model/ApiUuidValue} driverId
 */
DriverVehicleAssignment.prototype['driverId'] = undefined;

/**
 * @member {module:model/ApiBooleanValue} primaryVehicle
 */
DriverVehicleAssignment.prototype['primaryVehicle'] = undefined;

/**
 * @member {module:model/ApiStringValue} vin
 */
DriverVehicleAssignment.prototype['vin'] = undefined;






export default DriverVehicleAssignment;

