/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InvoicePeriod from './InvoicePeriod';

/**
 * The FinalizeParameters model module.
 * @module model/FinalizeParameters
 * @version 3.0.0
 */
class FinalizeParameters {
    /**
     * Constructs a new <code>FinalizeParameters</code>.
     * The information used to finalize a quote.
     * @alias module:model/FinalizeParameters
     * @param invoicePeriod {module:model/InvoicePeriod} 
     */
    constructor(invoicePeriod) { 
        
        FinalizeParameters.initialize(this, invoicePeriod);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, invoicePeriod) { 
        obj['invoicePeriod'] = invoicePeriod;
    }

    /**
     * Constructs a <code>FinalizeParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FinalizeParameters} obj Optional instance to populate.
     * @return {module:model/FinalizeParameters} The populated <code>FinalizeParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FinalizeParameters();

            if (data.hasOwnProperty('invoicePeriod')) {
                obj['invoicePeriod'] = InvoicePeriod.constructFromObject(data['invoicePeriod']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FinalizeParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FinalizeParameters</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FinalizeParameters.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

FinalizeParameters.RequiredProperties = ["invoicePeriod"];

/**
 * @member {module:model/InvoicePeriod} invoicePeriod
 */
FinalizeParameters.prototype['invoicePeriod'] = undefined;






export default FinalizeParameters;

