/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AgencyAgent from './AgencyAgent';
import AgencyAgentSearchParameters from './AgencyAgentSearchParameters';

/**
 * The GetAgencyAgents404Response model module.
 * @module model/GetAgencyAgents404Response
 * @version 3.0.0
 */
class GetAgencyAgents404Response {
    /**
     * Constructs a new <code>GetAgencyAgents404Response</code>.
     * The not found response body.
     * @alias module:model/GetAgencyAgents404Response
     * @param error {String} The error message for an unlinked agency.
     */
    constructor(error) { 
        
        GetAgencyAgents404Response.initialize(this, error);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, error) { 
        obj['error'] = error;
    }

    /**
     * Constructs a <code>GetAgencyAgents404Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAgencyAgents404Response} obj Optional instance to populate.
     * @return {module:model/GetAgencyAgents404Response} The populated <code>GetAgencyAgents404Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAgencyAgents404Response();

            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('agents')) {
                obj['agents'] = ApiClient.convertToType(data['agents'], [AgencyAgent]);
            }
            if (data.hasOwnProperty('searchParameters')) {
                obj['searchParameters'] = AgencyAgentSearchParameters.constructFromObject(data['searchParameters']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetAgencyAgents404Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetAgencyAgents404Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetAgencyAgents404Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }
        if (data['agents']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['agents'])) {
                throw new Error("Expected the field `agents` to be an array in the JSON data but got " + data['agents']);
            }
            // validate the optional field `agents` (array)
            for (const item of data['agents']) {
                AgencyAgent.validateJSON(item);
            };
        }
        // validate the optional field `searchParameters`
        if (data['searchParameters']) { // data not null
          AgencyAgentSearchParameters.validateJSON(data['searchParameters']);
        }

        return true;
    }


}

GetAgencyAgents404Response.RequiredProperties = ["error"];

/**
 * The error message for an unlinked agency.
 * @member {String} error
 */
GetAgencyAgents404Response.prototype['error'] = undefined;

/**
 * The filtered agents associated with your agency
 * @member {Array.<module:model/AgencyAgent>} agents
 */
GetAgencyAgents404Response.prototype['agents'] = undefined;

/**
 * @member {module:model/AgencyAgentSearchParameters} searchParameters
 */
GetAgencyAgents404Response.prototype['searchParameters'] = undefined;






export default GetAgencyAgents404Response;

