/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetAgencyAgents401Response model module.
 * @module model/GetAgencyAgents401Response
 * @version 3.0.0
 */
class GetAgencyAgents401Response {
    /**
     * Constructs a new <code>GetAgencyAgents401Response</code>.
     * The unauthorized error response body.
     * @alias module:model/GetAgencyAgents401Response
     * @param message {module:model/GetAgencyAgents401Response.MessageEnum} The error message.
     */
    constructor(message) { 
        
        GetAgencyAgents401Response.initialize(this, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message) { 
        obj['message'] = message;
    }

    /**
     * Constructs a <code>GetAgencyAgents401Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAgencyAgents401Response} obj Optional instance to populate.
     * @return {module:model/GetAgencyAgents401Response} The populated <code>GetAgencyAgents401Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAgencyAgents401Response();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetAgencyAgents401Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetAgencyAgents401Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetAgencyAgents401Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

GetAgencyAgents401Response.RequiredProperties = ["message"];

/**
 * The error message.
 * @member {module:model/GetAgencyAgents401Response.MessageEnum} message
 */
GetAgencyAgents401Response.prototype['message'] = undefined;





/**
 * Allowed values for the <code>message</code> property.
 * @enum {String}
 * @readonly
 */
GetAgencyAgents401Response['MessageEnum'] = {

    /**
     * value: "unauthorized"
     * @const
     */
    "unauthorized": "unauthorized"
};



export default GetAgencyAgents401Response;

