/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetPolicyDocumentsPolicyIdentifierParameter model module.
 * @module model/GetPolicyDocumentsPolicyIdentifierParameter
 * @version 3.0.0
 */
class GetPolicyDocumentsPolicyIdentifierParameter {
    /**
     * Constructs a new <code>GetPolicyDocumentsPolicyIdentifierParameter</code>.
     * @alias module:model/GetPolicyDocumentsPolicyIdentifierParameter
     * @param {(module:model/String)} instance The actual instance to initialize GetPolicyDocumentsPolicyIdentifierParameter.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            // validate string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid value. Must be string. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        try {
            // validate string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid value. Must be string. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `GetPolicyDocumentsPolicyIdentifierParameter` with oneOf schemas String. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `GetPolicyDocumentsPolicyIdentifierParameter` with oneOf schemas String. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>GetPolicyDocumentsPolicyIdentifierParameter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetPolicyDocumentsPolicyIdentifierParameter} obj Optional instance to populate.
     * @return {module:model/GetPolicyDocumentsPolicyIdentifierParameter} The populated <code>GetPolicyDocumentsPolicyIdentifierParameter</code> instance.
     */
    static constructFromObject(data, obj) {
        return new GetPolicyDocumentsPolicyIdentifierParameter(data);
    }

    /**
     * Gets the actual instance, which can be <code>String</code>.
     * @return {(module:model/String)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>String</code>.
     * @param {(module:model/String)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = GetPolicyDocumentsPolicyIdentifierParameter.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of GetPolicyDocumentsPolicyIdentifierParameter from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/GetPolicyDocumentsPolicyIdentifierParameter} An instance of GetPolicyDocumentsPolicyIdentifierParameter.
     */
    static fromJSON = function(json_string){
        return GetPolicyDocumentsPolicyIdentifierParameter.constructFromObject(JSON.parse(json_string));
    }
}


GetPolicyDocumentsPolicyIdentifierParameter.OneOf = ["String"];

export default GetPolicyDocumentsPolicyIdentifierParameter;

