/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiBooleanValue from './ApiBooleanValue';
import MostRecentPolicy from './MostRecentPolicy';
import UninsuredInLastYear from './UninsuredInLastYear';

/**
 * The InsuranceHistory model module.
 * @module model/InsuranceHistory
 * @version 3.0.0
 */
class InsuranceHistory {
    /**
     * Constructs a new <code>InsuranceHistory</code>.
     * The attested insurance history of the policy holder.
     * @alias module:model/InsuranceHistory
     */
    constructor() { 
        
        InsuranceHistory.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InsuranceHistory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InsuranceHistory} obj Optional instance to populate.
     * @return {module:model/InsuranceHistory} The populated <code>InsuranceHistory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InsuranceHistory();

            if (data.hasOwnProperty('currentlyInsured')) {
                obj['currentlyInsured'] = ApiBooleanValue.constructFromObject(data['currentlyInsured']);
            }
            if (data.hasOwnProperty('mostRecentPolicy')) {
                obj['mostRecentPolicy'] = MostRecentPolicy.constructFromObject(data['mostRecentPolicy']);
            }
            if (data.hasOwnProperty('uninsuredInLastYear')) {
                obj['uninsuredInLastYear'] = UninsuredInLastYear.constructFromObject(data['uninsuredInLastYear']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InsuranceHistory</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InsuranceHistory</code>.
     */
    static validateJSON(data) {
        // validate the optional field `currentlyInsured`
        if (data['currentlyInsured']) { // data not null
          ApiBooleanValue.validateJSON(data['currentlyInsured']);
        }
        // validate the optional field `mostRecentPolicy`
        if (data['mostRecentPolicy']) { // data not null
          MostRecentPolicy.validateJSON(data['mostRecentPolicy']);
        }
        // validate the optional field `uninsuredInLastYear`
        if (data['uninsuredInLastYear']) { // data not null
          UninsuredInLastYear.validateJSON(data['uninsuredInLastYear']);
        }

        return true;
    }


}



/**
 * @member {module:model/ApiBooleanValue} currentlyInsured
 */
InsuranceHistory.prototype['currentlyInsured'] = undefined;

/**
 * @member {module:model/MostRecentPolicy} mostRecentPolicy
 */
InsuranceHistory.prototype['mostRecentPolicy'] = undefined;

/**
 * @member {module:model/UninsuredInLastYear} uninsuredInLastYear
 */
InsuranceHistory.prototype['uninsuredInLastYear'] = undefined;






export default InsuranceHistory;

