/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LegalDocument model module.
 * @module model/LegalDocument
 * @version 3.0.0
 */
class LegalDocument {
    /**
     * Constructs a new <code>LegalDocument</code>.
     * A legal document which must be presented to the customer.
     * @alias module:model/LegalDocument
     * @param id {String} The unique identifiers for this legal document.
     * @param title {String} The title of the document.
     * @param processing {Boolean} The document is processing.
     */
    constructor(id, title, processing) { 
        
        LegalDocument.initialize(this, id, title, processing);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, title, processing) { 
        obj['id'] = id;
        obj['title'] = title;
        obj['processing'] = processing;
    }

    /**
     * Constructs a <code>LegalDocument</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LegalDocument} obj Optional instance to populate.
     * @return {module:model/LegalDocument} The populated <code>LegalDocument</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LegalDocument();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('processing')) {
                obj['processing'] = ApiClient.convertToType(data['processing'], 'Boolean');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LegalDocument</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LegalDocument</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LegalDocument.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }

        return true;
    }


}

LegalDocument.RequiredProperties = ["id", "title", "processing"];

/**
 * The unique identifiers for this legal document.
 * @member {String} id
 */
LegalDocument.prototype['id'] = undefined;

/**
 * The title of the document.
 * @member {String} title
 */
LegalDocument.prototype['title'] = undefined;

/**
 * The document is processing.
 * @member {Boolean} processing
 */
LegalDocument.prototype['processing'] = undefined;

/**
 * The url to the document.
 * @member {String} url
 */
LegalDocument.prototype['url'] = undefined;






export default LegalDocument;

