/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LienholderParameters model module.
 * @module model/LienholderParameters
 * @version 3.0.0
 */
class LienholderParameters {
    /**
     * Constructs a new <code>LienholderParameters</code>.
     * A single lienholder associated with this quote.
     * @alias module:model/LienholderParameters
     */
    constructor() { 
        
        LienholderParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LienholderParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LienholderParameters} obj Optional instance to populate.
     * @return {module:model/LienholderParameters} The populated <code>LienholderParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LienholderParameters();

            if (data.hasOwnProperty('address1')) {
                obj['address1'] = ApiClient.convertToType(data['address1'], 'String');
            }
            if (data.hasOwnProperty('address2')) {
                obj['address2'] = ApiClient.convertToType(data['address2'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('vins')) {
                obj['vins'] = ApiClient.convertToType(data['vins'], ['String']);
            }
            if (data.hasOwnProperty('zip')) {
                obj['zip'] = ApiClient.convertToType(data['zip'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LienholderParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LienholderParameters</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['address1'] && !(typeof data['address1'] === 'string' || data['address1'] instanceof String)) {
            throw new Error("Expected the field `address1` to be a primitive type in the JSON string but got " + data['address1']);
        }
        // ensure the json data is a string
        if (data['address2'] && !(typeof data['address2'] === 'string' || data['address2'] instanceof String)) {
            throw new Error("Expected the field `address2` to be a primitive type in the JSON string but got " + data['address2']);
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['vins'])) {
            throw new Error("Expected the field `vins` to be an array in the JSON data but got " + data['vins']);
        }
        // ensure the json data is a string
        if (data['zip'] && !(typeof data['zip'] === 'string' || data['zip'] instanceof String)) {
            throw new Error("Expected the field `zip` to be a primitive type in the JSON string but got " + data['zip']);
        }

        return true;
    }


}



/**
 * The address line 1 of this lienholder's location.
 * @member {String} address1
 */
LienholderParameters.prototype['address1'] = undefined;

/**
 * The address line 2 of this lienholder's location.
 * @member {String} address2
 */
LienholderParameters.prototype['address2'] = undefined;

/**
 * The address city of this lienholder's location.
 * @member {String} city
 */
LienholderParameters.prototype['city'] = undefined;

/**
 * The unique identifier for this lienholder.
 * @member {String} id
 */
LienholderParameters.prototype['id'] = undefined;

/**
 * The name of this lienholder.
 * @member {String} name
 */
LienholderParameters.prototype['name'] = undefined;

/**
 * The address state of this lienholder's location.
 * @member {module:model/LienholderParameters.StateEnum} state
 */
LienholderParameters.prototype['state'] = undefined;

/**
 * The VINs associated with this lienholder.
 * @member {Array.<String>} vins
 */
LienholderParameters.prototype['vins'] = undefined;

/**
 * The address ZIP of this lienholder's location.
 * @member {String} zip
 */
LienholderParameters.prototype['zip'] = undefined;





/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
LienholderParameters['StateEnum'] = {

    /**
     * value: "AK"
     * @const
     */
    "AK": "AK",

    /**
     * value: "AL"
     * @const
     */
    "AL": "AL",

    /**
     * value: "AR"
     * @const
     */
    "AR": "AR",

    /**
     * value: "AZ"
     * @const
     */
    "AZ": "AZ",

    /**
     * value: "CA"
     * @const
     */
    "CA": "CA",

    /**
     * value: "CO"
     * @const
     */
    "CO": "CO",

    /**
     * value: "CT"
     * @const
     */
    "CT": "CT",

    /**
     * value: "DC"
     * @const
     */
    "DC": "DC",

    /**
     * value: "DE"
     * @const
     */
    "DE": "DE",

    /**
     * value: "FL"
     * @const
     */
    "FL": "FL",

    /**
     * value: "GA"
     * @const
     */
    "GA": "GA",

    /**
     * value: "HI"
     * @const
     */
    "HI": "HI",

    /**
     * value: "IA"
     * @const
     */
    "IA": "IA",

    /**
     * value: "ID"
     * @const
     */
    "ID": "ID",

    /**
     * value: "IL"
     * @const
     */
    "IL": "IL",

    /**
     * value: "IN"
     * @const
     */
    "IN": "IN",

    /**
     * value: "KS"
     * @const
     */
    "KS": "KS",

    /**
     * value: "KY"
     * @const
     */
    "KY": "KY",

    /**
     * value: "LA"
     * @const
     */
    "LA": "LA",

    /**
     * value: "MA"
     * @const
     */
    "MA": "MA",

    /**
     * value: "MD"
     * @const
     */
    "MD": "MD",

    /**
     * value: "ME"
     * @const
     */
    "ME": "ME",

    /**
     * value: "MI"
     * @const
     */
    "MI": "MI",

    /**
     * value: "MN"
     * @const
     */
    "MN": "MN",

    /**
     * value: "MO"
     * @const
     */
    "MO": "MO",

    /**
     * value: "MS"
     * @const
     */
    "MS": "MS",

    /**
     * value: "MT"
     * @const
     */
    "MT": "MT",

    /**
     * value: "NC"
     * @const
     */
    "NC": "NC",

    /**
     * value: "ND"
     * @const
     */
    "ND": "ND",

    /**
     * value: "NE"
     * @const
     */
    "NE": "NE",

    /**
     * value: "NH"
     * @const
     */
    "NH": "NH",

    /**
     * value: "NJ"
     * @const
     */
    "NJ": "NJ",

    /**
     * value: "NM"
     * @const
     */
    "NM": "NM",

    /**
     * value: "NV"
     * @const
     */
    "NV": "NV",

    /**
     * value: "NY"
     * @const
     */
    "NY": "NY",

    /**
     * value: "OH"
     * @const
     */
    "OH": "OH",

    /**
     * value: "OK"
     * @const
     */
    "OK": "OK",

    /**
     * value: "OR"
     * @const
     */
    "OR": "OR",

    /**
     * value: "PA"
     * @const
     */
    "PA": "PA",

    /**
     * value: "RI"
     * @const
     */
    "RI": "RI",

    /**
     * value: "SC"
     * @const
     */
    "SC": "SC",

    /**
     * value: "SD"
     * @const
     */
    "SD": "SD",

    /**
     * value: "TN"
     * @const
     */
    "TN": "TN",

    /**
     * value: "TX"
     * @const
     */
    "TX": "TX",

    /**
     * value: "UT"
     * @const
     */
    "UT": "UT",

    /**
     * value: "VA"
     * @const
     */
    "VA": "VA",

    /**
     * value: "VT"
     * @const
     */
    "VT": "VT",

    /**
     * value: "WA"
     * @const
     */
    "WA": "WA",

    /**
     * value: "WI"
     * @const
     */
    "WI": "WI",

    /**
     * value: "WV"
     * @const
     */
    "WV": "WV",

    /**
     * value: "WY"
     * @const
     */
    "WY": "WY"
};



export default LienholderParameters;

