/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MostRecentPolicyParametersCoveragesBiPdCombined model module.
 * @module model/MostRecentPolicyParametersCoveragesBiPdCombined
 * @version 3.0.0
 */
class MostRecentPolicyParametersCoveragesBiPdCombined {
    /**
     * Constructs a new <code>MostRecentPolicyParametersCoveragesBiPdCombined</code>.
     * The bi_pd_combined coverage associated with this policy.
     * @alias module:model/MostRecentPolicyParametersCoveragesBiPdCombined
     */
    constructor() { 
        
        MostRecentPolicyParametersCoveragesBiPdCombined.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MostRecentPolicyParametersCoveragesBiPdCombined</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MostRecentPolicyParametersCoveragesBiPdCombined} obj Optional instance to populate.
     * @return {module:model/MostRecentPolicyParametersCoveragesBiPdCombined} The populated <code>MostRecentPolicyParametersCoveragesBiPdCombined</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MostRecentPolicyParametersCoveragesBiPdCombined();

            if (data.hasOwnProperty('perOccurrence')) {
                obj['perOccurrence'] = ApiClient.convertToType(data['perOccurrence'], 'Number');
            }
            if (data.hasOwnProperty('perPerson')) {
                obj['perPerson'] = ApiClient.convertToType(data['perPerson'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MostRecentPolicyParametersCoveragesBiPdCombined</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MostRecentPolicyParametersCoveragesBiPdCombined</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * The per occurrence limit for this coverage.
 * @member {Number} perOccurrence
 */
MostRecentPolicyParametersCoveragesBiPdCombined.prototype['perOccurrence'] = undefined;

/**
 * The per person limit for this coverage.
 * @member {Number} perPerson
 */
MostRecentPolicyParametersCoveragesBiPdCombined.prototype['perPerson'] = undefined;






export default MostRecentPolicyParametersCoveragesBiPdCombined;

