/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MostRecentPolicyParametersCoverages from './MostRecentPolicyParametersCoverages';

/**
 * The MostRecentPolicyParameters model module.
 * @module model/MostRecentPolicyParameters
 * @version 3.0.0
 */
class MostRecentPolicyParameters {
    /**
     * Constructs a new <code>MostRecentPolicyParameters</code>.
     * The most recent policy of the policy holder.
     * @alias module:model/MostRecentPolicyParameters
     */
    constructor() { 
        
        MostRecentPolicyParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MostRecentPolicyParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MostRecentPolicyParameters} obj Optional instance to populate.
     * @return {module:model/MostRecentPolicyParameters} The populated <code>MostRecentPolicyParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MostRecentPolicyParameters();

            if (data.hasOwnProperty('continuousMonthsInsured')) {
                obj['continuousMonthsInsured'] = ApiClient.convertToType(data['continuousMonthsInsured'], 'Number');
            }
            if (data.hasOwnProperty('expirationDate')) {
                obj['expirationDate'] = ApiClient.convertToType(data['expirationDate'], 'Date');
            }
            if (data.hasOwnProperty('monthsWithCarrier')) {
                obj['monthsWithCarrier'] = ApiClient.convertToType(data['monthsWithCarrier'], 'Number');
            }
            if (data.hasOwnProperty('premiumInCents')) {
                obj['premiumInCents'] = ApiClient.convertToType(data['premiumInCents'], 'Number');
            }
            if (data.hasOwnProperty('termLengthInMonths')) {
                obj['termLengthInMonths'] = ApiClient.convertToType(data['termLengthInMonths'], 'Number');
            }
            if (data.hasOwnProperty('coverages')) {
                obj['coverages'] = MostRecentPolicyParametersCoverages.constructFromObject(data['coverages']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MostRecentPolicyParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MostRecentPolicyParameters</code>.
     */
    static validateJSON(data) {
        // validate the optional field `coverages`
        if (data['coverages']) { // data not null
          MostRecentPolicyParametersCoverages.validateJSON(data['coverages']);
        }

        return true;
    }


}



/**
 * The number of months the policy holder has been or was continuously insured.
 * @member {Number} continuousMonthsInsured
 */
MostRecentPolicyParameters.prototype['continuousMonthsInsured'] = undefined;

/**
 * The date on which the policy holder's most recent policy expired or will expire in ISO 8601 full-date format. See RFC 3339 section 5.6: https://www.rfc-editor.org/rfc/rfc3339#section-5.6
 * @member {Date} expirationDate
 */
MostRecentPolicyParameters.prototype['expirationDate'] = undefined;

/**
 * The number of months the policy holder has been or was with this carrier.
 * @member {Number} monthsWithCarrier
 */
MostRecentPolicyParameters.prototype['monthsWithCarrier'] = undefined;

/**
 * The total premium cost in USD cents for this policy for the full duration of the policy term.
 * @member {Number} premiumInCents
 */
MostRecentPolicyParameters.prototype['premiumInCents'] = undefined;

/**
 * The length of the policy term in months.
 * @member {Number} termLengthInMonths
 */
MostRecentPolicyParameters.prototype['termLengthInMonths'] = undefined;

/**
 * @member {module:model/MostRecentPolicyParametersCoverages} coverages
 */
MostRecentPolicyParameters.prototype['coverages'] = undefined;






export default MostRecentPolicyParameters;

