/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiDateValue from './ApiDateValue';
import ApiIntegerValue from './ApiIntegerValue';
import MostRecentPolicyCoverages from './MostRecentPolicyCoverages';

/**
 * The MostRecentPolicy model module.
 * @module model/MostRecentPolicy
 * @version 3.0.0
 */
class MostRecentPolicy {
    /**
     * Constructs a new <code>MostRecentPolicy</code>.
     * The most recent policy of the policy holder.
     * @alias module:model/MostRecentPolicy
     */
    constructor() { 
        
        MostRecentPolicy.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MostRecentPolicy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MostRecentPolicy} obj Optional instance to populate.
     * @return {module:model/MostRecentPolicy} The populated <code>MostRecentPolicy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MostRecentPolicy();

            if (data.hasOwnProperty('continuousMonthsInsured')) {
                obj['continuousMonthsInsured'] = ApiIntegerValue.constructFromObject(data['continuousMonthsInsured']);
            }
            if (data.hasOwnProperty('expirationDate')) {
                obj['expirationDate'] = ApiDateValue.constructFromObject(data['expirationDate']);
            }
            if (data.hasOwnProperty('monthsWithCarrier')) {
                obj['monthsWithCarrier'] = ApiIntegerValue.constructFromObject(data['monthsWithCarrier']);
            }
            if (data.hasOwnProperty('premiumInCents')) {
                obj['premiumInCents'] = ApiIntegerValue.constructFromObject(data['premiumInCents']);
            }
            if (data.hasOwnProperty('termLengthInMonths')) {
                obj['termLengthInMonths'] = ApiIntegerValue.constructFromObject(data['termLengthInMonths']);
            }
            if (data.hasOwnProperty('coverages')) {
                obj['coverages'] = MostRecentPolicyCoverages.constructFromObject(data['coverages']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MostRecentPolicy</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MostRecentPolicy</code>.
     */
    static validateJSON(data) {
        // validate the optional field `continuousMonthsInsured`
        if (data['continuousMonthsInsured']) { // data not null
          ApiIntegerValue.validateJSON(data['continuousMonthsInsured']);
        }
        // validate the optional field `expirationDate`
        if (data['expirationDate']) { // data not null
          ApiDateValue.validateJSON(data['expirationDate']);
        }
        // validate the optional field `monthsWithCarrier`
        if (data['monthsWithCarrier']) { // data not null
          ApiIntegerValue.validateJSON(data['monthsWithCarrier']);
        }
        // validate the optional field `premiumInCents`
        if (data['premiumInCents']) { // data not null
          ApiIntegerValue.validateJSON(data['premiumInCents']);
        }
        // validate the optional field `termLengthInMonths`
        if (data['termLengthInMonths']) { // data not null
          ApiIntegerValue.validateJSON(data['termLengthInMonths']);
        }
        // validate the optional field `coverages`
        if (data['coverages']) { // data not null
          MostRecentPolicyCoverages.validateJSON(data['coverages']);
        }

        return true;
    }


}



/**
 * @member {module:model/ApiIntegerValue} continuousMonthsInsured
 */
MostRecentPolicy.prototype['continuousMonthsInsured'] = undefined;

/**
 * @member {module:model/ApiDateValue} expirationDate
 */
MostRecentPolicy.prototype['expirationDate'] = undefined;

/**
 * @member {module:model/ApiIntegerValue} monthsWithCarrier
 */
MostRecentPolicy.prototype['monthsWithCarrier'] = undefined;

/**
 * @member {module:model/ApiIntegerValue} premiumInCents
 */
MostRecentPolicy.prototype['premiumInCents'] = undefined;

/**
 * @member {module:model/ApiIntegerValue} termLengthInMonths
 */
MostRecentPolicy.prototype['termLengthInMonths'] = undefined;

/**
 * @member {module:model/MostRecentPolicyCoverages} coverages
 */
MostRecentPolicy.prototype['coverages'] = undefined;






export default MostRecentPolicy;

