/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiStringValue from './ApiStringValue';
import OptionsTelematics from './OptionsTelematics';

/**
 * The Options model module.
 * @module model/Options
 * @version 3.0.0
 */
class Options {
    /**
     * Constructs a new <code>Options</code>.
     * The options for this quote. This includes things like invoice period.
     * @alias module:model/Options
     */
    constructor() { 
        
        Options.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Options</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Options} obj Optional instance to populate.
     * @return {module:model/Options} The populated <code>Options</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Options();

            if (data.hasOwnProperty('invoicePeriod')) {
                obj['invoicePeriod'] = ApiStringValue.constructFromObject(data['invoicePeriod']);
            }
            if (data.hasOwnProperty('telematics')) {
                obj['telematics'] = OptionsTelematics.constructFromObject(data['telematics']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Options</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Options</code>.
     */
    static validateJSON(data) {
        // validate the optional field `invoicePeriod`
        if (data['invoicePeriod']) { // data not null
          ApiStringValue.validateJSON(data['invoicePeriod']);
        }
        // validate the optional field `telematics`
        if (data['telematics']) { // data not null
          OptionsTelematics.validateJSON(data['telematics']);
        }

        return true;
    }


}



/**
 * @member {module:model/ApiStringValue} invoicePeriod
 */
Options.prototype['invoicePeriod'] = undefined;

/**
 * @member {module:model/OptionsTelematics} telematics
 */
Options.prototype['telematics'] = undefined;






export default Options;

