/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RequestTelematicsProgram from './RequestTelematicsProgram';

/**
 * The OptionsParametersTelematics model module.
 * @module model/OptionsParametersTelematics
 * @version 3.0.0
 */
class OptionsParametersTelematics {
    /**
     * Constructs a new <code>OptionsParametersTelematics</code>.
     * Represents telematics programs which a user can consent to.
     * @alias module:model/OptionsParametersTelematics
     */
    constructor() { 
        
        OptionsParametersTelematics.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OptionsParametersTelematics</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OptionsParametersTelematics} obj Optional instance to populate.
     * @return {module:model/OptionsParametersTelematics} The populated <code>OptionsParametersTelematics</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OptionsParametersTelematics();

            if (data.hasOwnProperty('programs')) {
                obj['programs'] = ApiClient.convertToType(data['programs'], [RequestTelematicsProgram]);
            }
            if (data.hasOwnProperty('testDrives')) {
                obj['testDrives'] = ApiClient.convertToType(data['testDrives'], [RequestTelematicsProgram]);
            }
            if (data.hasOwnProperty('electives')) {
                obj['electives'] = ApiClient.convertToType(data['electives'], [RequestTelematicsProgram]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OptionsParametersTelematics</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OptionsParametersTelematics</code>.
     */
    static validateJSON(data) {
        if (data['programs']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['programs'])) {
                throw new Error("Expected the field `programs` to be an array in the JSON data but got " + data['programs']);
            }
            // validate the optional field `programs` (array)
            for (const item of data['programs']) {
                RequestTelematicsProgram.validateJSON(item);
            };
        }
        if (data['testDrives']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['testDrives'])) {
                throw new Error("Expected the field `testDrives` to be an array in the JSON data but got " + data['testDrives']);
            }
            // validate the optional field `testDrives` (array)
            for (const item of data['testDrives']) {
                RequestTelematicsProgram.validateJSON(item);
            };
        }
        if (data['electives']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['electives'])) {
                throw new Error("Expected the field `electives` to be an array in the JSON data but got " + data['electives']);
            }
            // validate the optional field `electives` (array)
            for (const item of data['electives']) {
                RequestTelematicsProgram.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * DEPRECATED: Use testDrives and electives instead. This field will be removed in an upcoming release.
 * @member {Array.<module:model/RequestTelematicsProgram>} programs
 */
OptionsParametersTelematics.prototype['programs'] = undefined;

/**
 * The primary telematics programs available to the user. One must be chosen.
 * @member {Array.<module:model/RequestTelematicsProgram>} testDrives
 */
OptionsParametersTelematics.prototype['testDrives'] = undefined;

/**
 * The secondary telematics programs available to the user. These are optional.
 * @member {Array.<module:model/RequestTelematicsProgram>} electives
 */
OptionsParametersTelematics.prototype['electives'] = undefined;






export default OptionsParametersTelematics;

