/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PatchQuote425Response model module.
 * @module model/PatchQuote425Response
 * @version 3.0.0
 */
class PatchQuote425Response {
    /**
     * Constructs a new <code>PatchQuote425Response</code>.
     * The too early response body.
     * @alias module:model/PatchQuote425Response
     * @param error {String} The error message.
     */
    constructor(error) { 
        
        PatchQuote425Response.initialize(this, error);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, error) { 
        obj['error'] = error;
    }

    /**
     * Constructs a <code>PatchQuote425Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchQuote425Response} obj Optional instance to populate.
     * @return {module:model/PatchQuote425Response} The populated <code>PatchQuote425Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchQuote425Response();

            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PatchQuote425Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PatchQuote425Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PatchQuote425Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }

        return true;
    }


}

PatchQuote425Response.RequiredProperties = ["error"];

/**
 * The error message.
 * @member {String} error
 */
PatchQuote425Response.prototype['error'] = undefined;






export default PatchQuote425Response;

