/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InvoicePeriod from './InvoicePeriod';
import Payment from './Payment';

/**
 * The PaymentPlan model module.
 * @module model/PaymentPlan
 * @version 3.0.0
 */
class PaymentPlan {
    /**
     * Constructs a new <code>PaymentPlan</code>.
     * A named plan describing how a customer pays for their policy, as an ordered sequence of payments.
     * @alias module:model/PaymentPlan
     * @param invoicePeriod {module:model/InvoicePeriod} 
     * @param name {String} A human-readable name for this payment plan.
     * @param description {String} A human-readable description of this payment plan.
     * @param payments {Array.<module:model/Payment>} The payments in this plan, in the order they are due. Order is significant and represents the sequence in which payments are made.
     */
    constructor(invoicePeriod, name, description, payments) { 
        
        PaymentPlan.initialize(this, invoicePeriod, name, description, payments);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, invoicePeriod, name, description, payments) { 
        obj['invoicePeriod'] = invoicePeriod;
        obj['name'] = name;
        obj['description'] = description;
        obj['payments'] = payments;
    }

    /**
     * Constructs a <code>PaymentPlan</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentPlan} obj Optional instance to populate.
     * @return {module:model/PaymentPlan} The populated <code>PaymentPlan</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentPlan();

            if (data.hasOwnProperty('invoicePeriod')) {
                obj['invoicePeriod'] = InvoicePeriod.constructFromObject(data['invoicePeriod']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('payments')) {
                obj['payments'] = ApiClient.convertToType(data['payments'], [Payment]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentPlan</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentPlan</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentPlan.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        if (data['payments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['payments'])) {
                throw new Error("Expected the field `payments` to be an array in the JSON data but got " + data['payments']);
            }
            // validate the optional field `payments` (array)
            for (const item of data['payments']) {
                Payment.validateJSON(item);
            };
        }

        return true;
    }


}

PaymentPlan.RequiredProperties = ["invoicePeriod", "name", "description", "payments"];

/**
 * @member {module:model/InvoicePeriod} invoicePeriod
 */
PaymentPlan.prototype['invoicePeriod'] = undefined;

/**
 * A human-readable name for this payment plan.
 * @member {String} name
 */
PaymentPlan.prototype['name'] = undefined;

/**
 * A human-readable description of this payment plan.
 * @member {String} description
 */
PaymentPlan.prototype['description'] = undefined;

/**
 * The payments in this plan, in the order they are due. Order is significant and represents the sequence in which payments are made.
 * @member {Array.<module:model/Payment>} payments
 */
PaymentPlan.prototype['payments'] = undefined;






export default PaymentPlan;

