/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Charge from './Charge';

/**
 * The Payment model module.
 * @module model/Payment
 * @version 3.0.0
 */
class Payment {
    /**
     * Constructs a new <code>Payment</code>.
     * A payment due by the customer for this quote.
     * @alias module:model/Payment
     * @param charges {Array.<module:model/Charge>} A breakdown of the component charges, including premium and applicable fees.
     * @param totalAmountInCents {Number} The total amount in USD cents for this payment.
     * @param totalAmountInDollars {Number} The total amount in USD dollars for this payment.
     */
    constructor(charges, totalAmountInCents, totalAmountInDollars) { 
        
        Payment.initialize(this, charges, totalAmountInCents, totalAmountInDollars);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, charges, totalAmountInCents, totalAmountInDollars) { 
        obj['charges'] = charges;
        obj['totalAmountInCents'] = totalAmountInCents;
        obj['totalAmountInDollars'] = totalAmountInDollars;
    }

    /**
     * Constructs a <code>Payment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Payment} obj Optional instance to populate.
     * @return {module:model/Payment} The populated <code>Payment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Payment();

            if (data.hasOwnProperty('charges')) {
                obj['charges'] = ApiClient.convertToType(data['charges'], [Charge]);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('totalAmountInCents')) {
                obj['totalAmountInCents'] = ApiClient.convertToType(data['totalAmountInCents'], 'Number');
            }
            if (data.hasOwnProperty('totalAmountInDollars')) {
                obj['totalAmountInDollars'] = ApiClient.convertToType(data['totalAmountInDollars'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Payment</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Payment</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Payment.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['charges']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['charges'])) {
                throw new Error("Expected the field `charges` to be an array in the JSON data but got " + data['charges']);
            }
            // validate the optional field `charges` (array)
            for (const item of data['charges']) {
                Charge.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['totalAmountInDollars'] && !(typeof data['totalAmountInDollars'] === 'string' || data['totalAmountInDollars'] instanceof String)) {
            throw new Error("Expected the field `totalAmountInDollars` to be a primitive type in the JSON string but got " + data['totalAmountInDollars']);
        }

        return true;
    }


}

Payment.RequiredProperties = ["charges", "totalAmountInCents", "totalAmountInDollars"];

/**
 * A breakdown of the component charges, including premium and applicable fees.
 * @member {Array.<module:model/Charge>} charges
 */
Payment.prototype['charges'] = undefined;

/**
 * An optional human-readable description of this payment.
 * @member {String} description
 */
Payment.prototype['description'] = undefined;

/**
 * The total amount in USD cents for this payment.
 * @member {Number} totalAmountInCents
 */
Payment.prototype['totalAmountInCents'] = undefined;

/**
 * The total amount in USD dollars for this payment.
 * @member {Number} totalAmountInDollars
 */
Payment.prototype['totalAmountInDollars'] = undefined;






export default Payment;

