/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentMethodCreateParameters model module.
 * @module model/PaymentMethodCreateParameters
 * @version 3.0.0
 */
class PaymentMethodCreateParameters {
    /**
     * Constructs a new <code>PaymentMethodCreateParameters</code>.
     * The request payload for creating a payment method.
     * @alias module:model/PaymentMethodCreateParameters
     * @param kind {module:model/PaymentMethodCreateParameters.KindEnum} The kind of payment method being submitted.
     */
    constructor(kind) { 
        
        PaymentMethodCreateParameters.initialize(this, kind);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, kind) { 
        obj['kind'] = kind;
    }

    /**
     * Constructs a <code>PaymentMethodCreateParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentMethodCreateParameters} obj Optional instance to populate.
     * @return {module:model/PaymentMethodCreateParameters} The populated <code>PaymentMethodCreateParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentMethodCreateParameters();

            if (data.hasOwnProperty('kind')) {
                obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentMethodCreateParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentMethodCreateParameters</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentMethodCreateParameters.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['kind'] && !(typeof data['kind'] === 'string' || data['kind'] instanceof String)) {
            throw new Error("Expected the field `kind` to be a primitive type in the JSON string but got " + data['kind']);
        }

        return true;
    }


}

PaymentMethodCreateParameters.RequiredProperties = ["kind"];

/**
 * The kind of payment method being submitted.
 * @member {module:model/PaymentMethodCreateParameters.KindEnum} kind
 */
PaymentMethodCreateParameters.prototype['kind'] = undefined;





/**
 * Allowed values for the <code>kind</code> property.
 * @enum {String}
 * @readonly
 */
PaymentMethodCreateParameters['KindEnum'] = {

    /**
     * value: "partner_commitment"
     * @const
     */
    "partner_commitment": "partner_commitment"
};



export default PaymentMethodCreateParameters;

