/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PolicyAddress from './PolicyAddress';
import PolicyLienholder from './PolicyLienholder';

/**
 * The PolicyVehicle model module.
 * @module model/PolicyVehicle
 * @version 3.0.0
 */
class PolicyVehicle {
    /**
     * Constructs a new <code>PolicyVehicle</code>.
     * A single vehicle covered by this policy.
     * @alias module:model/PolicyVehicle
     */
    constructor() { 
        
        PolicyVehicle.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PolicyVehicle</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PolicyVehicle} obj Optional instance to populate.
     * @return {module:model/PolicyVehicle} The populated <code>PolicyVehicle</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PolicyVehicle();

            if (data.hasOwnProperty('annualizedMileage')) {
                obj['annualizedMileage'] = ApiClient.convertToType(data['annualizedMileage'], 'Number');
            }
            if (data.hasOwnProperty('garagingAddress')) {
                obj['garagingAddress'] = PolicyAddress.constructFromObject(data['garagingAddress']);
            }
            if (data.hasOwnProperty('lienholders')) {
                obj['lienholders'] = ApiClient.convertToType(data['lienholders'], [PolicyLienholder]);
            }
            if (data.hasOwnProperty('make')) {
                obj['make'] = ApiClient.convertToType(data['make'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('primaryUsage')) {
                obj['primaryUsage'] = ApiClient.convertToType(data['primaryUsage'], 'String');
            }
            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('vin')) {
                obj['vin'] = ApiClient.convertToType(data['vin'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PolicyVehicle</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PolicyVehicle</code>.
     */
    static validateJSON(data) {
        // validate the optional field `garagingAddress`
        if (data['garagingAddress']) { // data not null
          PolicyAddress.validateJSON(data['garagingAddress']);
        }
        if (data['lienholders']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['lienholders'])) {
                throw new Error("Expected the field `lienholders` to be an array in the JSON data but got " + data['lienholders']);
            }
            // validate the optional field `lienholders` (array)
            for (const item of data['lienholders']) {
                PolicyLienholder.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['make'] && !(typeof data['make'] === 'string' || data['make'] instanceof String)) {
            throw new Error("Expected the field `make` to be a primitive type in the JSON string but got " + data['make']);
        }
        // ensure the json data is a string
        if (data['model'] && !(typeof data['model'] === 'string' || data['model'] instanceof String)) {
            throw new Error("Expected the field `model` to be a primitive type in the JSON string but got " + data['model']);
        }
        // ensure the json data is a string
        if (data['primaryUsage'] && !(typeof data['primaryUsage'] === 'string' || data['primaryUsage'] instanceof String)) {
            throw new Error("Expected the field `primaryUsage` to be a primitive type in the JSON string but got " + data['primaryUsage']);
        }
        // ensure the json data is a string
        if (data['vin'] && !(typeof data['vin'] === 'string' || data['vin'] instanceof String)) {
            throw new Error("Expected the field `vin` to be a primitive type in the JSON string but got " + data['vin']);
        }

        return true;
    }


}



/**
 * The distance in miles that this vehicle is expected to be driven in a year.
 * @member {Number} annualizedMileage
 */
PolicyVehicle.prototype['annualizedMileage'] = undefined;

/**
 * @member {module:model/PolicyAddress} garagingAddress
 */
PolicyVehicle.prototype['garagingAddress'] = undefined;

/**
 * The lienholders who have interest in this particular vehicle.
 * @member {Array.<module:model/PolicyLienholder>} lienholders
 */
PolicyVehicle.prototype['lienholders'] = undefined;

/**
 * The vehicle make.
 * @member {String} make
 */
PolicyVehicle.prototype['make'] = undefined;

/**
 * The vehicle model.
 * @member {String} model
 */
PolicyVehicle.prototype['model'] = undefined;

/**
 * The primary usage of this vehicle.
 * @member {module:model/PolicyVehicle.PrimaryUsageEnum} primaryUsage
 */
PolicyVehicle.prototype['primaryUsage'] = undefined;

/**
 * The vehicle model year.
 * @member {Number} year
 */
PolicyVehicle.prototype['year'] = undefined;

/**
 * The vehicle identification number.
 * @member {String} vin
 */
PolicyVehicle.prototype['vin'] = undefined;





/**
 * Allowed values for the <code>primaryUsage</code> property.
 * @enum {String}
 * @readonly
 */
PolicyVehicle['PrimaryUsageEnum'] = {

    /**
     * value: "business"
     * @const
     */
    "business": "business",

    /**
     * value: "commute"
     * @const
     */
    "commute": "commute",

    /**
     * value: "farm"
     * @const
     */
    "farm": "farm",

    /**
     * value: "pleasure"
     * @const
     */
    "pleasure": "pleasure",

    /**
     * value: "occasional"
     * @const
     */
    "occasional": "occasional",

    /**
     * value: "rideshare"
     * @const
     */
    "rideshare": "rideshare",

    /**
     * value: "work"
     * @const
     */
    "work": "work"
};



export default PolicyVehicle;

