/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PolicyCoverageSymbolRequirementsInner from './PolicyCoverageSymbolRequirementsInner';

/**
 * The PolicyCoverageSymbol model module.
 * @module model/PolicyCoverageSymbol
 * @version 3.0.0
 */
class PolicyCoverageSymbol {
    /**
     * Constructs a new <code>PolicyCoverageSymbol</code>.
     * A shorthand for the coverage kind such as &#39;bi&#39; for Bodily Injury.
     * @alias module:model/PolicyCoverageSymbol
     * @param message {String} An error message if applicable.
     * @param requirements {Array.<module:model/PolicyCoverageSymbolRequirementsInner>} A list of requirements that must be met for this value to be valid.
     * @param valid {Boolean} This value is valid.
     * @param value {module:model/PolicyCoverageSymbol.ValueEnum} The current value.
     */
    constructor(message, requirements, valid, value) { 
        
        PolicyCoverageSymbol.initialize(this, message, requirements, valid, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, requirements, valid, value) { 
        obj['message'] = message;
        obj['requirements'] = requirements;
        obj['valid'] = valid;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>PolicyCoverageSymbol</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PolicyCoverageSymbol} obj Optional instance to populate.
     * @return {module:model/PolicyCoverageSymbol} The populated <code>PolicyCoverageSymbol</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PolicyCoverageSymbol();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('requirements')) {
                obj['requirements'] = ApiClient.convertToType(data['requirements'], [PolicyCoverageSymbolRequirementsInner]);
            }
            if (data.hasOwnProperty('valid')) {
                obj['valid'] = ApiClient.convertToType(data['valid'], 'Boolean');
            }
            if (data.hasOwnProperty('inferredValue')) {
                obj['inferredValue'] = ApiClient.convertToType(data['inferredValue'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PolicyCoverageSymbol</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PolicyCoverageSymbol</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PolicyCoverageSymbol.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        if (data['requirements']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['requirements'])) {
                throw new Error("Expected the field `requirements` to be an array in the JSON data but got " + data['requirements']);
            }
            // validate the optional field `requirements` (array)
            for (const item of data['requirements']) {
                PolicyCoverageSymbolRequirementsInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['inferredValue'] && !(typeof data['inferredValue'] === 'string' || data['inferredValue'] instanceof String)) {
            throw new Error("Expected the field `inferredValue` to be a primitive type in the JSON string but got " + data['inferredValue']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }

        return true;
    }


}

PolicyCoverageSymbol.RequiredProperties = ["message", "requirements", "valid", "value"];

/**
 * An error message if applicable.
 * @member {String} message
 */
PolicyCoverageSymbol.prototype['message'] = undefined;

/**
 * A list of requirements that must be met for this value to be valid.
 * @member {Array.<module:model/PolicyCoverageSymbolRequirementsInner>} requirements
 */
PolicyCoverageSymbol.prototype['requirements'] = undefined;

/**
 * This value is valid.
 * @member {Boolean} valid
 */
PolicyCoverageSymbol.prototype['valid'] = undefined;

/**
 * The value inferred and used instead for pricing when value is invalid.
 * @member {module:model/PolicyCoverageSymbol.InferredValueEnum} inferredValue
 */
PolicyCoverageSymbol.prototype['inferredValue'] = undefined;

/**
 * The current value.
 * @member {module:model/PolicyCoverageSymbol.ValueEnum} value
 */
PolicyCoverageSymbol.prototype['value'] = undefined;





/**
 * Allowed values for the <code>inferredValue</code> property.
 * @enum {String}
 * @readonly
 */
PolicyCoverageSymbol['InferredValueEnum'] = {

    /**
     * value: "adb"
     * @const
     */
    "adb": "adb",

    /**
     * value: "bi"
     * @const
     */
    "bi": "bi",

    /**
     * value: "bi_pd_combined"
     * @const
     */
    "bi_pd_combined": "bi_pd_combined",

    /**
     * value: "coll"
     * @const
     */
    "coll": "coll",

    /**
     * value: "cdw"
     * @const
     */
    "cdw": "cdw",

    /**
     * value: "comp"
     * @const
     */
    "comp": "comp",

    /**
     * value: "custe"
     * @const
     */
    "custe": "custe",

    /**
     * value: "fnrl"
     * @const
     */
    "fnrl": "fnrl",

    /**
     * value: "med_exp"
     * @const
     */
    "med_exp": "med_exp",

    /**
     * value: "med_pay"
     * @const
     */
    "med_pay": "med_pay",

    /**
     * value: "pip"
     * @const
     */
    "pip": "pip",

    /**
     * value: "pd"
     * @const
     */
    "pd": "pd",

    /**
     * value: "rental"
     * @const
     */
    "rental": "rental",

    /**
     * value: "roadside"
     * @const
     */
    "roadside": "roadside",

    /**
     * value: "uim"
     * @const
     */
    "uim": "uim",

    /**
     * value: "uimpd"
     * @const
     */
    "uimpd": "uimpd",

    /**
     * value: "umuim"
     * @const
     */
    "umuim": "umuim",

    /**
     * value: "um"
     * @const
     */
    "um": "um",

    /**
     * value: "umpd"
     * @const
     */
    "umpd": "umpd",

    /**
     * value: "wk_ls"
     * @const
     */
    "wk_ls": "wk_ls",

    /**
     * value: "wlb"
     * @const
     */
    "wlb": "wlb",

    /**
     * value: "tort"
     * @const
     */
    "tort": "tort"
};


/**
 * Allowed values for the <code>value</code> property.
 * @enum {String}
 * @readonly
 */
PolicyCoverageSymbol['ValueEnum'] = {

    /**
     * value: "adb"
     * @const
     */
    "adb": "adb",

    /**
     * value: "bi"
     * @const
     */
    "bi": "bi",

    /**
     * value: "bi_pd_combined"
     * @const
     */
    "bi_pd_combined": "bi_pd_combined",

    /**
     * value: "coll"
     * @const
     */
    "coll": "coll",

    /**
     * value: "cdw"
     * @const
     */
    "cdw": "cdw",

    /**
     * value: "comp"
     * @const
     */
    "comp": "comp",

    /**
     * value: "custe"
     * @const
     */
    "custe": "custe",

    /**
     * value: "fnrl"
     * @const
     */
    "fnrl": "fnrl",

    /**
     * value: "med_exp"
     * @const
     */
    "med_exp": "med_exp",

    /**
     * value: "med_pay"
     * @const
     */
    "med_pay": "med_pay",

    /**
     * value: "pip"
     * @const
     */
    "pip": "pip",

    /**
     * value: "pd"
     * @const
     */
    "pd": "pd",

    /**
     * value: "rental"
     * @const
     */
    "rental": "rental",

    /**
     * value: "roadside"
     * @const
     */
    "roadside": "roadside",

    /**
     * value: "uim"
     * @const
     */
    "uim": "uim",

    /**
     * value: "uimpd"
     * @const
     */
    "uimpd": "uimpd",

    /**
     * value: "umuim"
     * @const
     */
    "umuim": "umuim",

    /**
     * value: "um"
     * @const
     */
    "um": "um",

    /**
     * value: "umpd"
     * @const
     */
    "umpd": "umpd",

    /**
     * value: "wk_ls"
     * @const
     */
    "wk_ls": "wk_ls",

    /**
     * value: "wlb"
     * @const
     */
    "wlb": "wlb",

    /**
     * value: "tort"
     * @const
     */
    "tort": "tort"
};



export default PolicyCoverageSymbol;

