/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CoverageAttributeParameters from './CoverageAttributeParameters';

/**
 * The PolicyCoveragePatchParameters model module.
 * @module model/PolicyCoveragePatchParameters
 * @version 3.0.0
 */
class PolicyCoveragePatchParameters {
    /**
     * Constructs a new <code>PolicyCoveragePatchParameters</code>.
     * An object meant to represent a single policy-level coverage selection.
     * @alias module:model/PolicyCoveragePatchParameters
     */
    constructor() { 
        
        PolicyCoveragePatchParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PolicyCoveragePatchParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PolicyCoveragePatchParameters} obj Optional instance to populate.
     * @return {module:model/PolicyCoveragePatchParameters} The populated <code>PolicyCoveragePatchParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PolicyCoveragePatchParameters();

            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], {'String': CoverageAttributeParameters});
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PolicyCoveragePatchParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PolicyCoveragePatchParameters</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['symbol'] && !(typeof data['symbol'] === 'string' || data['symbol'] instanceof String)) {
            throw new Error("Expected the field `symbol` to be a primitive type in the JSON string but got " + data['symbol']);
        }

        return true;
    }


}



/**
 * The object's key is the index of the attribute within the attributes array, and the value is an object with the parameters to be updated. If value is null, the attribute will be deleted.
 * @member {Object.<String, module:model/CoverageAttributeParameters>} attributes
 */
PolicyCoveragePatchParameters.prototype['attributes'] = undefined;

/**
 * A shorthand for the coverage kind such as 'umuim' for Uninsured and Underinsured Motorist Bodily Injury.
 * @member {module:model/PolicyCoveragePatchParameters.SymbolEnum} symbol
 */
PolicyCoveragePatchParameters.prototype['symbol'] = undefined;





/**
 * Allowed values for the <code>symbol</code> property.
 * @enum {String}
 * @readonly
 */
PolicyCoveragePatchParameters['SymbolEnum'] = {

    /**
     * value: "adb"
     * @const
     */
    "adb": "adb",

    /**
     * value: "bi"
     * @const
     */
    "bi": "bi",

    /**
     * value: "bi_pd_combined"
     * @const
     */
    "bi_pd_combined": "bi_pd_combined",

    /**
     * value: "coll"
     * @const
     */
    "coll": "coll",

    /**
     * value: "cdw"
     * @const
     */
    "cdw": "cdw",

    /**
     * value: "comp"
     * @const
     */
    "comp": "comp",

    /**
     * value: "custe"
     * @const
     */
    "custe": "custe",

    /**
     * value: "fnrl"
     * @const
     */
    "fnrl": "fnrl",

    /**
     * value: "med_exp"
     * @const
     */
    "med_exp": "med_exp",

    /**
     * value: "med_pay"
     * @const
     */
    "med_pay": "med_pay",

    /**
     * value: "pip"
     * @const
     */
    "pip": "pip",

    /**
     * value: "pd"
     * @const
     */
    "pd": "pd",

    /**
     * value: "rental"
     * @const
     */
    "rental": "rental",

    /**
     * value: "roadside"
     * @const
     */
    "roadside": "roadside",

    /**
     * value: "uim"
     * @const
     */
    "uim": "uim",

    /**
     * value: "uimpd"
     * @const
     */
    "uimpd": "uimpd",

    /**
     * value: "umuim"
     * @const
     */
    "umuim": "umuim",

    /**
     * value: "um"
     * @const
     */
    "um": "um",

    /**
     * value: "umpd"
     * @const
     */
    "umpd": "umpd",

    /**
     * value: "wk_ls"
     * @const
     */
    "wk_ls": "wk_ls",

    /**
     * value: "wlb"
     * @const
     */
    "wlb": "wlb",

    /**
     * value: "tort"
     * @const
     */
    "tort": "tort"
};



export default PolicyCoveragePatchParameters;

