/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DisplayCoverageAttribute from './DisplayCoverageAttribute';

/**
 * The PolicyDisplayCoverage model module.
 * @module model/PolicyDisplayCoverage
 * @version 3.0.0
 */
class PolicyDisplayCoverage {
    /**
     * Constructs a new <code>PolicyDisplayCoverage</code>.
     * An object meant to represent a single policy-level coverage selection.
     * @alias module:model/PolicyDisplayCoverage
     * @param attributes {Array.<module:model/DisplayCoverageAttribute>} Attributes associated with this coverage such as limits or if it's declined.
     * @param applyTo {String} (Experimental) The entity this coverage applies to ('policy' or a specific vehicle identifier). Please see your Root representative to request access to this experimental endpoint.
     * @param description {String} A human readable version of the coverage and its attributes.
     * @param longDescription {String} (Experimental) A more detailed human readable version of the coverage and its attributes. Please see your Root representative to request access to this experimental endpoint.
     * @param name {String} A human readable version of the coverage symbol.
     * @param pricedBy {module:model/PolicyDisplayCoverage.PricedByEnum} (Experimental) The level at which we price the coverage ('policy' or 'vehicle'). Please see your Root representative to request access to this experimental endpoint.
     * @param symbol {module:model/PolicyDisplayCoverage.SymbolEnum} A shorthand for the coverage kind such as 'umuim' for Uninsured and Underinsured Motorist Bodily Injury.
     */
    constructor(attributes, applyTo, description, longDescription, name, pricedBy, symbol) { 
        
        PolicyDisplayCoverage.initialize(this, attributes, applyTo, description, longDescription, name, pricedBy, symbol);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, attributes, applyTo, description, longDescription, name, pricedBy, symbol) { 
        obj['attributes'] = attributes;
        obj['applyTo'] = applyTo;
        obj['description'] = description;
        obj['longDescription'] = longDescription;
        obj['name'] = name;
        obj['pricedBy'] = pricedBy;
        obj['symbol'] = symbol;
    }

    /**
     * Constructs a <code>PolicyDisplayCoverage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PolicyDisplayCoverage} obj Optional instance to populate.
     * @return {module:model/PolicyDisplayCoverage} The populated <code>PolicyDisplayCoverage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PolicyDisplayCoverage();

            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], [DisplayCoverageAttribute]);
            }
            if (data.hasOwnProperty('applyTo')) {
                obj['applyTo'] = ApiClient.convertToType(data['applyTo'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('longDescription')) {
                obj['longDescription'] = ApiClient.convertToType(data['longDescription'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('pricedBy')) {
                obj['pricedBy'] = ApiClient.convertToType(data['pricedBy'], 'String');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PolicyDisplayCoverage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PolicyDisplayCoverage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PolicyDisplayCoverage.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['attributes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['attributes'])) {
                throw new Error("Expected the field `attributes` to be an array in the JSON data but got " + data['attributes']);
            }
            // validate the optional field `attributes` (array)
            for (const item of data['attributes']) {
                DisplayCoverageAttribute.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['applyTo'] && !(typeof data['applyTo'] === 'string' || data['applyTo'] instanceof String)) {
            throw new Error("Expected the field `applyTo` to be a primitive type in the JSON string but got " + data['applyTo']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['longDescription'] && !(typeof data['longDescription'] === 'string' || data['longDescription'] instanceof String)) {
            throw new Error("Expected the field `longDescription` to be a primitive type in the JSON string but got " + data['longDescription']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['pricedBy'] && !(typeof data['pricedBy'] === 'string' || data['pricedBy'] instanceof String)) {
            throw new Error("Expected the field `pricedBy` to be a primitive type in the JSON string but got " + data['pricedBy']);
        }
        // ensure the json data is a string
        if (data['symbol'] && !(typeof data['symbol'] === 'string' || data['symbol'] instanceof String)) {
            throw new Error("Expected the field `symbol` to be a primitive type in the JSON string but got " + data['symbol']);
        }

        return true;
    }


}

PolicyDisplayCoverage.RequiredProperties = ["attributes", "applyTo", "description", "longDescription", "name", "pricedBy", "symbol"];

/**
 * Attributes associated with this coverage such as limits or if it's declined.
 * @member {Array.<module:model/DisplayCoverageAttribute>} attributes
 */
PolicyDisplayCoverage.prototype['attributes'] = undefined;

/**
 * (Experimental) The entity this coverage applies to ('policy' or a specific vehicle identifier). Please see your Root representative to request access to this experimental endpoint.
 * @member {String} applyTo
 */
PolicyDisplayCoverage.prototype['applyTo'] = undefined;

/**
 * A human readable version of the coverage and its attributes.
 * @member {String} description
 */
PolicyDisplayCoverage.prototype['description'] = undefined;

/**
 * (Experimental) A more detailed human readable version of the coverage and its attributes. Please see your Root representative to request access to this experimental endpoint.
 * @member {String} longDescription
 */
PolicyDisplayCoverage.prototype['longDescription'] = undefined;

/**
 * A human readable version of the coverage symbol.
 * @member {String} name
 */
PolicyDisplayCoverage.prototype['name'] = undefined;

/**
 * (Experimental) The level at which we price the coverage ('policy' or 'vehicle'). Please see your Root representative to request access to this experimental endpoint.
 * @member {module:model/PolicyDisplayCoverage.PricedByEnum} pricedBy
 */
PolicyDisplayCoverage.prototype['pricedBy'] = undefined;

/**
 * A shorthand for the coverage kind such as 'umuim' for Uninsured and Underinsured Motorist Bodily Injury.
 * @member {module:model/PolicyDisplayCoverage.SymbolEnum} symbol
 */
PolicyDisplayCoverage.prototype['symbol'] = undefined;





/**
 * Allowed values for the <code>pricedBy</code> property.
 * @enum {String}
 * @readonly
 */
PolicyDisplayCoverage['PricedByEnum'] = {

    /**
     * value: "policy"
     * @const
     */
    "policy": "policy",

    /**
     * value: "vehicle"
     * @const
     */
    "vehicle": "vehicle"
};


/**
 * Allowed values for the <code>symbol</code> property.
 * @enum {String}
 * @readonly
 */
PolicyDisplayCoverage['SymbolEnum'] = {

    /**
     * value: "adb"
     * @const
     */
    "adb": "adb",

    /**
     * value: "bi"
     * @const
     */
    "bi": "bi",

    /**
     * value: "bi_pd_combined"
     * @const
     */
    "bi_pd_combined": "bi_pd_combined",

    /**
     * value: "coll"
     * @const
     */
    "coll": "coll",

    /**
     * value: "cdw"
     * @const
     */
    "cdw": "cdw",

    /**
     * value: "comp"
     * @const
     */
    "comp": "comp",

    /**
     * value: "custe"
     * @const
     */
    "custe": "custe",

    /**
     * value: "fnrl"
     * @const
     */
    "fnrl": "fnrl",

    /**
     * value: "med_exp"
     * @const
     */
    "med_exp": "med_exp",

    /**
     * value: "med_pay"
     * @const
     */
    "med_pay": "med_pay",

    /**
     * value: "pip"
     * @const
     */
    "pip": "pip",

    /**
     * value: "pd"
     * @const
     */
    "pd": "pd",

    /**
     * value: "rental"
     * @const
     */
    "rental": "rental",

    /**
     * value: "roadside"
     * @const
     */
    "roadside": "roadside",

    /**
     * value: "uim"
     * @const
     */
    "uim": "uim",

    /**
     * value: "uimpd"
     * @const
     */
    "uimpd": "uimpd",

    /**
     * value: "umuim"
     * @const
     */
    "umuim": "umuim",

    /**
     * value: "um"
     * @const
     */
    "um": "um",

    /**
     * value: "umpd"
     * @const
     */
    "umpd": "umpd",

    /**
     * value: "wk_ls"
     * @const
     */
    "wk_ls": "wk_ls",

    /**
     * value: "wlb"
     * @const
     */
    "wlb": "wlb",

    /**
     * value: "tort"
     * @const
     */
    "tort": "tort"
};



export default PolicyDisplayCoverage;

