/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Quote from './Quote';

/**
 * The PostFinalizeQuote202Response model module.
 * @module model/PostFinalizeQuote202Response
 * @version 3.0.0
 */
class PostFinalizeQuote202Response {
    /**
     * Constructs a new <code>PostFinalizeQuote202Response</code>.
     * The success entity response body.
     * @alias module:model/PostFinalizeQuote202Response
     * @param quote {module:model/Quote} 
     */
    constructor(quote) { 
        
        PostFinalizeQuote202Response.initialize(this, quote);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, quote) { 
        obj['quote'] = quote;
    }

    /**
     * Constructs a <code>PostFinalizeQuote202Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostFinalizeQuote202Response} obj Optional instance to populate.
     * @return {module:model/PostFinalizeQuote202Response} The populated <code>PostFinalizeQuote202Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostFinalizeQuote202Response();

            if (data.hasOwnProperty('quote')) {
                obj['quote'] = Quote.constructFromObject(data['quote']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostFinalizeQuote202Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostFinalizeQuote202Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostFinalizeQuote202Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `quote`
        if (data['quote']) { // data not null
          Quote.validateJSON(data['quote']);
        }

        return true;
    }


}

PostFinalizeQuote202Response.RequiredProperties = ["quote"];

/**
 * @member {module:model/Quote} quote
 */
PostFinalizeQuote202Response.prototype['quote'] = undefined;






export default PostFinalizeQuote202Response;

