/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostBindQuote422ResponseOneOf model module.
 * @module model/PostBindQuote422ResponseOneOf
 * @version 3.0.0
 */
class PostBindQuote422ResponseOneOf {
    /**
     * Constructs a new <code>PostBindQuote422ResponseOneOf</code>.
     * The unprocessable entity response body.
     * @alias module:model/PostBindQuote422ResponseOneOf
     * @param error {String} The error message.
     * @param errorType {module:model/PostBindQuote422ResponseOneOf.ErrorTypeEnum} The classification of error that occurred.
     */
    constructor(error, errorType) { 
        
        PostBindQuote422ResponseOneOf.initialize(this, error, errorType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, error, errorType) { 
        obj['error'] = error;
        obj['errorType'] = errorType;
    }

    /**
     * Constructs a <code>PostBindQuote422ResponseOneOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostBindQuote422ResponseOneOf} obj Optional instance to populate.
     * @return {module:model/PostBindQuote422ResponseOneOf} The populated <code>PostBindQuote422ResponseOneOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostBindQuote422ResponseOneOf();

            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('errorType')) {
                obj['errorType'] = ApiClient.convertToType(data['errorType'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostBindQuote422ResponseOneOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostBindQuote422ResponseOneOf</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostBindQuote422ResponseOneOf.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }
        // ensure the json data is a string
        if (data['errorType'] && !(typeof data['errorType'] === 'string' || data['errorType'] instanceof String)) {
            throw new Error("Expected the field `errorType` to be a primitive type in the JSON string but got " + data['errorType']);
        }

        return true;
    }


}

PostBindQuote422ResponseOneOf.RequiredProperties = ["error", "errorType"];

/**
 * The error message.
 * @member {String} error
 */
PostBindQuote422ResponseOneOf.prototype['error'] = undefined;

/**
 * The classification of error that occurred.
 * @member {module:model/PostBindQuote422ResponseOneOf.ErrorTypeEnum} errorType
 */
PostBindQuote422ResponseOneOf.prototype['errorType'] = undefined;





/**
 * Allowed values for the <code>errorType</code> property.
 * @enum {String}
 * @readonly
 */
PostBindQuote422ResponseOneOf['ErrorTypeEnum'] = {

    /**
     * value: "agent_not_found"
     * @const
     */
    "agent_not_found": "agent_not_found",

    /**
     * value: "agent_not_active"
     * @const
     */
    "agent_not_active": "agent_not_active",

    /**
     * value: "agent_not_appointed_for_market"
     * @const
     */
    "agent_not_appointed_for_market": "agent_not_appointed_for_market",

    /**
     * value: "denylisted_drivers"
     * @const
     */
    "denylisted_drivers": "denylisted_drivers",

    /**
     * value: "deprecated_policyholder"
     * @const
     */
    "deprecated_policyholder": "deprecated_policyholder",

    /**
     * value: "driver_already_bound"
     * @const
     */
    "driver_already_bound": "driver_already_bound",

    /**
     * value: "incorrect_rating_request_reason"
     * @const
     */
    "incorrect_rating_request_reason": "incorrect_rating_request_reason",

    /**
     * value: "invalid_effective_date"
     * @const
     */
    "invalid_effective_date": "invalid_effective_date",

    /**
     * value: "payment_failed"
     * @const
     */
    "payment_failed": "payment_failed",

    /**
     * value: "quote_already_bound"
     * @const
     */
    "quote_already_bound": "quote_already_bound",

    /**
     * value: "quote_expired"
     * @const
     */
    "quote_expired": "quote_expired",

    /**
     * value: "rating_request_expired"
     * @const
     */
    "rating_request_expired": "rating_request_expired",

    /**
     * value: "underwriting_not_approved"
     * @const
     */
    "underwriting_not_approved": "underwriting_not_approved",

    /**
     * value: "customer_account_erased"
     * @const
     */
    "customer_account_erased": "customer_account_erased",

    /**
     * value: "endorsement_policy_invalid"
     * @const
     */
    "endorsement_policy_invalid": "endorsement_policy_invalid",

    /**
     * value: "endorsement_quote_invalid"
     * @const
     */
    "endorsement_quote_invalid": "endorsement_quote_invalid",

    /**
     * value: "bound_quotes_cannot_be_modified"
     * @const
     */
    "bound_quotes_cannot_be_modified": "bound_quotes_cannot_be_modified",

    /**
     * value: "quote_not_partnership_committed"
     * @const
     */
    "quote_not_partnership_committed": "quote_not_partnership_committed",

    /**
     * value: "direct_payment_failed"
     * @const
     */
    "direct_payment_failed": "direct_payment_failed",

    /**
     * value: "missing_default_payment_method"
     * @const
     */
    "missing_default_payment_method": "missing_default_payment_method",

    /**
     * value: "endorsement_compliance_blocked"
     * @const
     */
    "endorsement_compliance_blocked": "endorsement_compliance_blocked"
};



export default PostBindQuote422ResponseOneOf;

