/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PrefillReportIdentifier from './PrefillReportIdentifier';

/**
 * The PrefillDriver model module.
 * @module model/PrefillDriver
 * @version 3.0.0
 */
class PrefillDriver {
    /**
     * Constructs a new <code>PrefillDriver</code>.
     * A single driver found on the prefill report.
     * @alias module:model/PrefillDriver
     * @param id {String} The prefill driver's ID to be used in the Quote API. When used in the Quote API, this ID should be provided as the prefillDriverId on the intended Driver object.
     * @param isRequestedDriver {Boolean} Indicates whether this driver matches the parameters provided during the creation of the prefill request. There will be at most 1 prefill driver with this set to true, and the requested driver (if present) will be the first prefill driver in the list.
     */
    constructor(id, isRequestedDriver) { 
        
        PrefillDriver.initialize(this, id, isRequestedDriver);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, isRequestedDriver) { 
        obj['id'] = id;
        obj['isRequestedDriver'] = isRequestedDriver;
    }

    /**
     * Constructs a <code>PrefillDriver</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PrefillDriver} obj Optional instance to populate.
     * @return {module:model/PrefillDriver} The populated <code>PrefillDriver</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PrefillDriver();

            if (data.hasOwnProperty('dob')) {
                obj['dob'] = ApiClient.convertToType(data['dob'], 'Date');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('isDenylistedDriver')) {
                obj['isDenylistedDriver'] = ApiClient.convertToType(data['isDenylistedDriver'], 'Boolean');
            }
            if (data.hasOwnProperty('isRequestedDriver')) {
                obj['isRequestedDriver'] = ApiClient.convertToType(data['isRequestedDriver'], 'Boolean');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('licenseNumber')) {
                obj['licenseNumber'] = ApiClient.convertToType(data['licenseNumber'], 'String');
            }
            if (data.hasOwnProperty('licenseState')) {
                obj['licenseState'] = ApiClient.convertToType(data['licenseState'], 'String');
            }
            if (data.hasOwnProperty('prefillReportIdentifiers')) {
                obj['prefillReportIdentifiers'] = ApiClient.convertToType(data['prefillReportIdentifiers'], [PrefillReportIdentifier]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PrefillDriver</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PrefillDriver</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PrefillDriver.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['firstName'] && !(typeof data['firstName'] === 'string' || data['firstName'] instanceof String)) {
            throw new Error("Expected the field `firstName` to be a primitive type in the JSON string but got " + data['firstName']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['lastName'] && !(typeof data['lastName'] === 'string' || data['lastName'] instanceof String)) {
            throw new Error("Expected the field `lastName` to be a primitive type in the JSON string but got " + data['lastName']);
        }
        // ensure the json data is a string
        if (data['licenseNumber'] && !(typeof data['licenseNumber'] === 'string' || data['licenseNumber'] instanceof String)) {
            throw new Error("Expected the field `licenseNumber` to be a primitive type in the JSON string but got " + data['licenseNumber']);
        }
        // ensure the json data is a string
        if (data['licenseState'] && !(typeof data['licenseState'] === 'string' || data['licenseState'] instanceof String)) {
            throw new Error("Expected the field `licenseState` to be a primitive type in the JSON string but got " + data['licenseState']);
        }
        if (data['prefillReportIdentifiers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['prefillReportIdentifiers'])) {
                throw new Error("Expected the field `prefillReportIdentifiers` to be an array in the JSON data but got " + data['prefillReportIdentifiers']);
            }
            // validate the optional field `prefillReportIdentifiers` (array)
            for (const item of data['prefillReportIdentifiers']) {
                PrefillReportIdentifier.validateJSON(item);
            };
        }

        return true;
    }


}

PrefillDriver.RequiredProperties = ["id", "isRequestedDriver"];

/**
 * The driver's date of birth. This field is obfuscated to only show the birth year in ISO 8601 full-date format with month and day masked. See rfc 3339 section 5.6: https://www.rfc-editor.org/rfc/rfc3339#section-5.6..
 * @member {Date} dob
 */
PrefillDriver.prototype['dob'] = undefined;

/**
 * The driver's first name.
 * @member {String} firstName
 */
PrefillDriver.prototype['firstName'] = undefined;

/**
 * The prefill driver's ID to be used in the Quote API. When used in the Quote API, this ID should be provided as the prefillDriverId on the intended Driver object.
 * @member {String} id
 */
PrefillDriver.prototype['id'] = undefined;

/**
 * Indicates whether this driver is on Root's denylist.Drivers on the denylist will not be underwritten by Root and cannot be included on the policy.
 * @member {Boolean} isDenylistedDriver
 */
PrefillDriver.prototype['isDenylistedDriver'] = undefined;

/**
 * Indicates whether this driver matches the parameters provided during the creation of the prefill request. There will be at most 1 prefill driver with this set to true, and the requested driver (if present) will be the first prefill driver in the list.
 * @member {Boolean} isRequestedDriver
 */
PrefillDriver.prototype['isRequestedDriver'] = undefined;

/**
 * The driver's last name.
 * @member {String} lastName
 */
PrefillDriver.prototype['lastName'] = undefined;

/**
 * The driver's license number. This field is obfuscated to only show the last 3 characters.
 * @member {String} licenseNumber
 */
PrefillDriver.prototype['licenseNumber'] = undefined;

/**
 * The driver's license state issuer.
 * @member {module:model/PrefillDriver.LicenseStateEnum} licenseState
 */
PrefillDriver.prototype['licenseState'] = undefined;

/**
 * The unique identifiers for the associated prefilled report.
 * @member {Array.<module:model/PrefillReportIdentifier>} prefillReportIdentifiers
 */
PrefillDriver.prototype['prefillReportIdentifiers'] = undefined;





/**
 * Allowed values for the <code>licenseState</code> property.
 * @enum {String}
 * @readonly
 */
PrefillDriver['LicenseStateEnum'] = {

    /**
     * value: "AK"
     * @const
     */
    "AK": "AK",

    /**
     * value: "AL"
     * @const
     */
    "AL": "AL",

    /**
     * value: "AR"
     * @const
     */
    "AR": "AR",

    /**
     * value: "AZ"
     * @const
     */
    "AZ": "AZ",

    /**
     * value: "CA"
     * @const
     */
    "CA": "CA",

    /**
     * value: "CO"
     * @const
     */
    "CO": "CO",

    /**
     * value: "CT"
     * @const
     */
    "CT": "CT",

    /**
     * value: "DC"
     * @const
     */
    "DC": "DC",

    /**
     * value: "DE"
     * @const
     */
    "DE": "DE",

    /**
     * value: "FL"
     * @const
     */
    "FL": "FL",

    /**
     * value: "GA"
     * @const
     */
    "GA": "GA",

    /**
     * value: "HI"
     * @const
     */
    "HI": "HI",

    /**
     * value: "IA"
     * @const
     */
    "IA": "IA",

    /**
     * value: "ID"
     * @const
     */
    "ID": "ID",

    /**
     * value: "IL"
     * @const
     */
    "IL": "IL",

    /**
     * value: "IN"
     * @const
     */
    "IN": "IN",

    /**
     * value: "KS"
     * @const
     */
    "KS": "KS",

    /**
     * value: "KY"
     * @const
     */
    "KY": "KY",

    /**
     * value: "LA"
     * @const
     */
    "LA": "LA",

    /**
     * value: "MA"
     * @const
     */
    "MA": "MA",

    /**
     * value: "MD"
     * @const
     */
    "MD": "MD",

    /**
     * value: "ME"
     * @const
     */
    "ME": "ME",

    /**
     * value: "MI"
     * @const
     */
    "MI": "MI",

    /**
     * value: "MN"
     * @const
     */
    "MN": "MN",

    /**
     * value: "MO"
     * @const
     */
    "MO": "MO",

    /**
     * value: "MS"
     * @const
     */
    "MS": "MS",

    /**
     * value: "MT"
     * @const
     */
    "MT": "MT",

    /**
     * value: "NC"
     * @const
     */
    "NC": "NC",

    /**
     * value: "ND"
     * @const
     */
    "ND": "ND",

    /**
     * value: "NE"
     * @const
     */
    "NE": "NE",

    /**
     * value: "NH"
     * @const
     */
    "NH": "NH",

    /**
     * value: "NJ"
     * @const
     */
    "NJ": "NJ",

    /**
     * value: "NM"
     * @const
     */
    "NM": "NM",

    /**
     * value: "NV"
     * @const
     */
    "NV": "NV",

    /**
     * value: "NY"
     * @const
     */
    "NY": "NY",

    /**
     * value: "OH"
     * @const
     */
    "OH": "OH",

    /**
     * value: "OK"
     * @const
     */
    "OK": "OK",

    /**
     * value: "OR"
     * @const
     */
    "OR": "OR",

    /**
     * value: "PA"
     * @const
     */
    "PA": "PA",

    /**
     * value: "RI"
     * @const
     */
    "RI": "RI",

    /**
     * value: "SC"
     * @const
     */
    "SC": "SC",

    /**
     * value: "SD"
     * @const
     */
    "SD": "SD",

    /**
     * value: "TN"
     * @const
     */
    "TN": "TN",

    /**
     * value: "TX"
     * @const
     */
    "TX": "TX",

    /**
     * value: "UT"
     * @const
     */
    "UT": "UT",

    /**
     * value: "VA"
     * @const
     */
    "VA": "VA",

    /**
     * value: "VT"
     * @const
     */
    "VT": "VT",

    /**
     * value: "WA"
     * @const
     */
    "WA": "WA",

    /**
     * value: "WI"
     * @const
     */
    "WI": "WI",

    /**
     * value: "WV"
     * @const
     */
    "WV": "WV",

    /**
     * value: "WY"
     * @const
     */
    "WY": "WY"
};



export default PrefillDriver;

