/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AgentParameters from './AgentParameters';
import AttributionParameters from './AttributionParameters';
import BridgeLinkParameters from './BridgeLinkParameters';
import CoveragesParameters from './CoveragesParameters';
import OptionsParameters from './OptionsParameters';
import ProfileParameters from './ProfileParameters';
import RateCallParameters from './RateCallParameters';

/**
 * The QuoteCreateParameters model module.
 * @module model/QuoteCreateParameters
 * @version 3.0.0
 */
class QuoteCreateParameters {
    /**
     * Constructs a new <code>QuoteCreateParameters</code>.
     * The full description of the quote need from the partner. This includes profile data and coverage selections.
     * @alias module:model/QuoteCreateParameters
     */
    constructor() { 
        
        QuoteCreateParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QuoteCreateParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QuoteCreateParameters} obj Optional instance to populate.
     * @return {module:model/QuoteCreateParameters} The populated <code>QuoteCreateParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuoteCreateParameters();

            if (data.hasOwnProperty('profile')) {
                obj['profile'] = ProfileParameters.constructFromObject(data['profile']);
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = OptionsParameters.constructFromObject(data['options']);
            }
            if (data.hasOwnProperty('coverages')) {
                obj['coverages'] = CoveragesParameters.constructFromObject(data['coverages']);
            }
            if (data.hasOwnProperty('agent')) {
                obj['agent'] = AgentParameters.constructFromObject(data['agent']);
            }
            if (data.hasOwnProperty('bridgeLink')) {
                obj['bridgeLink'] = BridgeLinkParameters.constructFromObject(data['bridgeLink']);
            }
            if (data.hasOwnProperty('attributionParameters')) {
                obj['attributionParameters'] = AttributionParameters.constructFromObject(data['attributionParameters']);
            }
            if (data.hasOwnProperty('rateCall')) {
                obj['rateCall'] = RateCallParameters.constructFromObject(data['rateCall']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QuoteCreateParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QuoteCreateParameters</code>.
     */
    static validateJSON(data) {
        // validate the optional field `profile`
        if (data['profile']) { // data not null
          ProfileParameters.validateJSON(data['profile']);
        }
        // validate the optional field `options`
        if (data['options']) { // data not null
          OptionsParameters.validateJSON(data['options']);
        }
        // validate the optional field `coverages`
        if (data['coverages']) { // data not null
          CoveragesParameters.validateJSON(data['coverages']);
        }
        // validate the optional field `agent`
        if (data['agent']) { // data not null
          AgentParameters.validateJSON(data['agent']);
        }
        // validate the optional field `bridgeLink`
        if (data['bridgeLink']) { // data not null
          BridgeLinkParameters.validateJSON(data['bridgeLink']);
        }
        // validate the optional field `attributionParameters`
        if (data['attributionParameters']) { // data not null
          AttributionParameters.validateJSON(data['attributionParameters']);
        }
        // validate the optional field `rateCall`
        if (data['rateCall']) { // data not null
          RateCallParameters.validateJSON(data['rateCall']);
        }

        return true;
    }


}



/**
 * @member {module:model/ProfileParameters} profile
 */
QuoteCreateParameters.prototype['profile'] = undefined;

/**
 * @member {module:model/OptionsParameters} options
 */
QuoteCreateParameters.prototype['options'] = undefined;

/**
 * @member {module:model/CoveragesParameters} coverages
 */
QuoteCreateParameters.prototype['coverages'] = undefined;

/**
 * @member {module:model/AgentParameters} agent
 */
QuoteCreateParameters.prototype['agent'] = undefined;

/**
 * @member {module:model/BridgeLinkParameters} bridgeLink
 */
QuoteCreateParameters.prototype['bridgeLink'] = undefined;

/**
 * @member {module:model/AttributionParameters} attributionParameters
 */
QuoteCreateParameters.prototype['attributionParameters'] = undefined;

/**
 * @member {module:model/RateCallParameters} rateCall
 */
QuoteCreateParameters.prototype['rateCall'] = undefined;






export default QuoteCreateParameters;

