/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequestTelematicsProgram model module.
 * @module model/RequestTelematicsProgram
 * @version 3.0.0
 */
class RequestTelematicsProgram {
    /**
     * Constructs a new <code>RequestTelematicsProgram</code>.
     * The telematics program available to the user which can be consented to.
     * @alias module:model/RequestTelematicsProgram
     */
    constructor() { 
        
        RequestTelematicsProgram.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RequestTelematicsProgram</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestTelematicsProgram} obj Optional instance to populate.
     * @return {module:model/RequestTelematicsProgram} The populated <code>RequestTelematicsProgram</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestTelematicsProgram();

            if (data.hasOwnProperty('consentedAt')) {
                obj['consentedAt'] = ApiClient.convertToType(data['consentedAt'], 'Date');
            }
            if (data.hasOwnProperty('enrollment')) {
                obj['enrollment'] = ApiClient.convertToType(data['enrollment'], 'String');
            }
            if (data.hasOwnProperty('program')) {
                obj['program'] = ApiClient.convertToType(data['program'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RequestTelematicsProgram</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RequestTelematicsProgram</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['enrollment'] && !(typeof data['enrollment'] === 'string' || data['enrollment'] instanceof String)) {
            throw new Error("Expected the field `enrollment` to be a primitive type in the JSON string but got " + data['enrollment']);
        }
        // ensure the json data is a string
        if (data['program'] && !(typeof data['program'] === 'string' || data['program'] instanceof String)) {
            throw new Error("Expected the field `program` to be a primitive type in the JSON string but got " + data['program']);
        }

        return true;
    }


}



/**
 * The timestamp when the user consented to this telematics program, in ISO 8601 format.
 * @member {Date} consentedAt
 */
RequestTelematicsProgram.prototype['consentedAt'] = undefined;

/**
 * Whether the user has consented to this telematics program.
 * @member {module:model/RequestTelematicsProgram.EnrollmentEnum} enrollment
 */
RequestTelematicsProgram.prototype['enrollment'] = undefined;

/**
 * The telematics program identifier. While this list shows all possible programs, the available programs differ on a quote-by-quote basis, so a particular quote will only have a subset (or none) of these options.
 * @member {module:model/RequestTelematicsProgram.ProgramEnum} program
 */
RequestTelematicsProgram.prototype['program'] = undefined;





/**
 * Allowed values for the <code>enrollment</code> property.
 * @enum {String}
 * @readonly
 */
RequestTelematicsProgram['EnrollmentEnum'] = {

    /**
     * value: "declined"
     * @const
     */
    "declined": "declined",

    /**
     * value: "enrolled"
     * @const
     */
    "enrolled": "enrolled"
};


/**
 * Allowed values for the <code>program</code> property.
 * @enum {String}
 * @readonly
 */
RequestTelematicsProgram['ProgramEnum'] = {

    /**
     * value: "root_test_drive"
     * @const
     */
    "root_test_drive": "root_test_drive",

    /**
     * value: "root_ready_test_drive_cas"
     * @const
     */
    "root_ready_test_drive_cas": "root_ready_test_drive_cas",

    /**
     * value: "root_ready_test_drive_arity"
     * @const
     */
    "root_ready_test_drive_arity": "root_ready_test_drive_arity",

    /**
     * value: "no_test_drive"
     * @const
     */
    "no_test_drive": "no_test_drive",

    /**
     * value: "continuous_connectivity"
     * @const
     */
    "continuous_connectivity": "continuous_connectivity"
};



export default RequestTelematicsProgram;

