/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResponseTelematicsProgramEnrollmentRequirementsInner from './ResponseTelematicsProgramEnrollmentRequirementsInner';

/**
 * The ResponseTelematicsProgramEnrollment model module.
 * @module model/ResponseTelematicsProgramEnrollment
 * @version 3.0.0
 */
class ResponseTelematicsProgramEnrollment {
    /**
     * Constructs a new <code>ResponseTelematicsProgramEnrollment</code>.
     * Whether the user has been enrolled to this telematics program.
     * @alias module:model/ResponseTelematicsProgramEnrollment
     */
    constructor() { 
        
        ResponseTelematicsProgramEnrollment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResponseTelematicsProgramEnrollment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseTelematicsProgramEnrollment} obj Optional instance to populate.
     * @return {module:model/ResponseTelematicsProgramEnrollment} The populated <code>ResponseTelematicsProgramEnrollment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseTelematicsProgramEnrollment();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('inferredValue')) {
                obj['inferredValue'] = ApiClient.convertToType(data['inferredValue'], 'String');
            }
            if (data.hasOwnProperty('valid')) {
                obj['valid'] = ApiClient.convertToType(data['valid'], 'Boolean');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('requirements')) {
                obj['requirements'] = ApiClient.convertToType(data['requirements'], [ResponseTelematicsProgramEnrollmentRequirementsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResponseTelematicsProgramEnrollment</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResponseTelematicsProgramEnrollment</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }
        // ensure the json data is a string
        if (data['inferredValue'] && !(typeof data['inferredValue'] === 'string' || data['inferredValue'] instanceof String)) {
            throw new Error("Expected the field `inferredValue` to be a primitive type in the JSON string but got " + data['inferredValue']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        if (data['requirements']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['requirements'])) {
                throw new Error("Expected the field `requirements` to be an array in the JSON data but got " + data['requirements']);
            }
            // validate the optional field `requirements` (array)
            for (const item of data['requirements']) {
                ResponseTelematicsProgramEnrollmentRequirementsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * The enrollment status of the telematics program. Requires a valid consentedAt timestamp to enroll.
 * @member {module:model/ResponseTelematicsProgramEnrollment.ValueEnum} value
 */
ResponseTelematicsProgramEnrollment.prototype['value'] = undefined;

/**
 * The value inferred and used instead for enrollment when value is invalid.
 * @member {module:model/ResponseTelematicsProgramEnrollment.InferredValueEnum} inferredValue
 */
ResponseTelematicsProgramEnrollment.prototype['inferredValue'] = undefined;

/**
 * This value is valid.
 * @member {Boolean} valid
 */
ResponseTelematicsProgramEnrollment.prototype['valid'] = undefined;

/**
 * An error message if applicable.
 * @member {String} message
 */
ResponseTelematicsProgramEnrollment.prototype['message'] = undefined;

/**
 * A list of requirements that must be met for this value to be valid.
 * @member {Array.<module:model/ResponseTelematicsProgramEnrollmentRequirementsInner>} requirements
 */
ResponseTelematicsProgramEnrollment.prototype['requirements'] = undefined;





/**
 * Allowed values for the <code>value</code> property.
 * @enum {String}
 * @readonly
 */
ResponseTelematicsProgramEnrollment['ValueEnum'] = {

    /**
     * value: "declined"
     * @const
     */
    "declined": "declined",

    /**
     * value: "enrolled"
     * @const
     */
    "enrolled": "enrolled",

    /**
     * value: "unspecified"
     * @const
     */
    "unspecified": "unspecified"
};


/**
 * Allowed values for the <code>inferredValue</code> property.
 * @enum {String}
 * @readonly
 */
ResponseTelematicsProgramEnrollment['InferredValueEnum'] = {

    /**
     * value: "declined"
     * @const
     */
    "declined": "declined",

    /**
     * value: "enrolled"
     * @const
     */
    "enrolled": "enrolled",

    /**
     * value: "unspecified"
     * @const
     */
    "unspecified": "unspecified"
};



export default ResponseTelematicsProgramEnrollment;

