/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';

/**
 * The ValidateAddress201Response model module.
 * @module model/ValidateAddress201Response
 * @version 3.0.0
 */
class ValidateAddress201Response {
    /**
     * Constructs a new <code>ValidateAddress201Response</code>.
     * The success response body.
     * @alias module:model/ValidateAddress201Response
     * @param address {module:model/Address} 
     */
    constructor(address) { 
        
        ValidateAddress201Response.initialize(this, address);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address) { 
        obj['address'] = address;
    }

    /**
     * Constructs a <code>ValidateAddress201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidateAddress201Response} obj Optional instance to populate.
     * @return {module:model/ValidateAddress201Response} The populated <code>ValidateAddress201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidateAddress201Response();

            if (data.hasOwnProperty('address')) {
                obj['address'] = Address.constructFromObject(data['address']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ValidateAddress201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ValidateAddress201Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ValidateAddress201Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `address`
        if (data['address']) { // data not null
          Address.validateJSON(data['address']);
        }

        return true;
    }


}

ValidateAddress201Response.RequiredProperties = ["address"];

/**
 * @member {module:model/Address} address
 */
ValidateAddress201Response.prototype['address'] = undefined;






export default ValidateAddress201Response;

