/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiStringValue from './ApiStringValue';
import CoverageAttribute from './CoverageAttribute';
import VehicleCoverageSymbol from './VehicleCoverageSymbol';

/**
 * The VehicleCoverage model module.
 * @module model/VehicleCoverage
 * @version 3.0.0
 */
class VehicleCoverage {
    /**
     * Constructs a new <code>VehicleCoverage</code>.
     * An object meant to represent a single vehicle-level coverage selection.
     * @alias module:model/VehicleCoverage
     * @param attributes {Array.<module:model/CoverageAttribute>} Attributes associated with this coverage such as limits or if it's declined.
     * @param applyTo {module:model/ApiStringValue} 
     * @param description {String} A human readable version of the coverage and its attributes.
     * @param longDescription {String} (Experimental) A more detailed human readable version of the coverage and its attributes. Please see your Root representative to request access to this experimental endpoint.
     * @param name {String} A human readable version of the coverage symbol.
     * @param pricedBy {module:model/VehicleCoverage.PricedByEnum} (Experimental) The level at which we price the coverage ('policy' or 'vehicle'). Please see your Root representative to request access to this experimental endpoint.
     * @param symbol {module:model/VehicleCoverageSymbol} 
     */
    constructor(attributes, applyTo, description, longDescription, name, pricedBy, symbol) { 
        
        VehicleCoverage.initialize(this, attributes, applyTo, description, longDescription, name, pricedBy, symbol);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, attributes, applyTo, description, longDescription, name, pricedBy, symbol) { 
        obj['attributes'] = attributes;
        obj['applyTo'] = applyTo;
        obj['description'] = description;
        obj['longDescription'] = longDescription;
        obj['name'] = name;
        obj['pricedBy'] = pricedBy;
        obj['symbol'] = symbol;
    }

    /**
     * Constructs a <code>VehicleCoverage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VehicleCoverage} obj Optional instance to populate.
     * @return {module:model/VehicleCoverage} The populated <code>VehicleCoverage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleCoverage();

            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], [CoverageAttribute]);
            }
            if (data.hasOwnProperty('applyTo')) {
                obj['applyTo'] = ApiStringValue.constructFromObject(data['applyTo']);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('longDescription')) {
                obj['longDescription'] = ApiClient.convertToType(data['longDescription'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('priceDescription')) {
                obj['priceDescription'] = ApiClient.convertToType(data['priceDescription'], 'String');
            }
            if (data.hasOwnProperty('priceInCents')) {
                obj['priceInCents'] = ApiClient.convertToType(data['priceInCents'], 'Number');
            }
            if (data.hasOwnProperty('pricedBy')) {
                obj['pricedBy'] = ApiClient.convertToType(data['pricedBy'], 'String');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = VehicleCoverageSymbol.constructFromObject(data['symbol']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VehicleCoverage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VehicleCoverage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of VehicleCoverage.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['attributes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['attributes'])) {
                throw new Error("Expected the field `attributes` to be an array in the JSON data but got " + data['attributes']);
            }
            // validate the optional field `attributes` (array)
            for (const item of data['attributes']) {
                CoverageAttribute.validateJSON(item);
            };
        }
        // validate the optional field `applyTo`
        if (data['applyTo']) { // data not null
          ApiStringValue.validateJSON(data['applyTo']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['longDescription'] && !(typeof data['longDescription'] === 'string' || data['longDescription'] instanceof String)) {
            throw new Error("Expected the field `longDescription` to be a primitive type in the JSON string but got " + data['longDescription']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['priceDescription'] && !(typeof data['priceDescription'] === 'string' || data['priceDescription'] instanceof String)) {
            throw new Error("Expected the field `priceDescription` to be a primitive type in the JSON string but got " + data['priceDescription']);
        }
        // ensure the json data is a string
        if (data['pricedBy'] && !(typeof data['pricedBy'] === 'string' || data['pricedBy'] instanceof String)) {
            throw new Error("Expected the field `pricedBy` to be a primitive type in the JSON string but got " + data['pricedBy']);
        }
        // validate the optional field `symbol`
        if (data['symbol']) { // data not null
          VehicleCoverageSymbol.validateJSON(data['symbol']);
        }

        return true;
    }


}

VehicleCoverage.RequiredProperties = ["attributes", "applyTo", "description", "longDescription", "name", "pricedBy", "symbol"];

/**
 * Attributes associated with this coverage such as limits or if it's declined.
 * @member {Array.<module:model/CoverageAttribute>} attributes
 */
VehicleCoverage.prototype['attributes'] = undefined;

/**
 * @member {module:model/ApiStringValue} applyTo
 */
VehicleCoverage.prototype['applyTo'] = undefined;

/**
 * A human readable version of the coverage and its attributes.
 * @member {String} description
 */
VehicleCoverage.prototype['description'] = undefined;

/**
 * (Experimental) A more detailed human readable version of the coverage and its attributes. Please see your Root representative to request access to this experimental endpoint.
 * @member {String} longDescription
 */
VehicleCoverage.prototype['longDescription'] = undefined;

/**
 * A human readable version of the coverage symbol.
 * @member {String} name
 */
VehicleCoverage.prototype['name'] = undefined;

/**
 * A human readable version of the coverage price.
 * @member {String} priceDescription
 */
VehicleCoverage.prototype['priceDescription'] = undefined;

/**
 * The price for the coverage in cents, depending on the currently selected invoice period (i.e. monthly vs full term). Note that due to taxes, fees, and other factors, these prices per coverage cannot be naively added together to arrive at the total due today when binding the policy. For that information, look at the breakdown of payments at the top level of the quote response.  If a coverage has a null priceInCents, this does not mean the coverage is free (0 is free).
 * @member {Number} priceInCents
 */
VehicleCoverage.prototype['priceInCents'] = undefined;

/**
 * (Experimental) The level at which we price the coverage ('policy' or 'vehicle'). Please see your Root representative to request access to this experimental endpoint.
 * @member {module:model/VehicleCoverage.PricedByEnum} pricedBy
 */
VehicleCoverage.prototype['pricedBy'] = undefined;

/**
 * @member {module:model/VehicleCoverageSymbol} symbol
 */
VehicleCoverage.prototype['symbol'] = undefined;





/**
 * Allowed values for the <code>pricedBy</code> property.
 * @enum {String}
 * @readonly
 */
VehicleCoverage['PricedByEnum'] = {

    /**
     * value: "policy"
     * @const
     */
    "policy": "policy",

    /**
     * value: "vehicle"
     * @const
     */
    "vehicle": "vehicle"
};



export default VehicleCoverage;

