/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiStringValue from './ApiStringValue';
import VehicleCoverage from './VehicleCoverage';

/**
 * The VehicleCoverages model module.
 * @module model/VehicleCoverages
 * @version 3.0.0
 */
class VehicleCoverages {
    /**
     * Constructs a new <code>VehicleCoverages</code>.
     * This object is meant to represent the current coverage selections associated with a single vehicle.
     * @alias module:model/VehicleCoverages
     * @param coverages {Array.<module:model/VehicleCoverage>} The coverages that apply to just this vehicle.
     * @param vin {module:model/ApiStringValue} 
     */
    constructor(coverages, vin) { 
        
        VehicleCoverages.initialize(this, coverages, vin);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, coverages, vin) { 
        obj['coverages'] = coverages;
        obj['vin'] = vin;
    }

    /**
     * Constructs a <code>VehicleCoverages</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VehicleCoverages} obj Optional instance to populate.
     * @return {module:model/VehicleCoverages} The populated <code>VehicleCoverages</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleCoverages();

            if (data.hasOwnProperty('coverages')) {
                obj['coverages'] = ApiClient.convertToType(data['coverages'], [VehicleCoverage]);
            }
            if (data.hasOwnProperty('vin')) {
                obj['vin'] = ApiStringValue.constructFromObject(data['vin']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VehicleCoverages</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VehicleCoverages</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of VehicleCoverages.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['coverages']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['coverages'])) {
                throw new Error("Expected the field `coverages` to be an array in the JSON data but got " + data['coverages']);
            }
            // validate the optional field `coverages` (array)
            for (const item of data['coverages']) {
                VehicleCoverage.validateJSON(item);
            };
        }
        // validate the optional field `vin`
        if (data['vin']) { // data not null
          ApiStringValue.validateJSON(data['vin']);
        }

        return true;
    }


}

VehicleCoverages.RequiredProperties = ["coverages", "vin"];

/**
 * The coverages that apply to just this vehicle.
 * @member {Array.<module:model/VehicleCoverage>} coverages
 */
VehicleCoverages.prototype['coverages'] = undefined;

/**
 * @member {module:model/ApiStringValue} vin
 */
VehicleCoverages.prototype['vin'] = undefined;






export default VehicleCoverages;

