/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VehicleCoverageParameters from './VehicleCoverageParameters';

/**
 * The VehicleCoveragesParameters model module.
 * @module model/VehicleCoveragesParameters
 * @version 3.0.0
 */
class VehicleCoveragesParameters {
    /**
     * Constructs a new <code>VehicleCoveragesParameters</code>.
     * This object is meant to represent the current coverage selections associated with a single vehicle.
     * @alias module:model/VehicleCoveragesParameters
     */
    constructor() { 
        
        VehicleCoveragesParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VehicleCoveragesParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VehicleCoveragesParameters} obj Optional instance to populate.
     * @return {module:model/VehicleCoveragesParameters} The populated <code>VehicleCoveragesParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleCoveragesParameters();

            if (data.hasOwnProperty('coverages')) {
                obj['coverages'] = ApiClient.convertToType(data['coverages'], [VehicleCoverageParameters]);
            }
            if (data.hasOwnProperty('vin')) {
                obj['vin'] = ApiClient.convertToType(data['vin'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VehicleCoveragesParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VehicleCoveragesParameters</code>.
     */
    static validateJSON(data) {
        if (data['coverages']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['coverages'])) {
                throw new Error("Expected the field `coverages` to be an array in the JSON data but got " + data['coverages']);
            }
            // validate the optional field `coverages` (array)
            for (const item of data['coverages']) {
                VehicleCoverageParameters.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['vin'] && !(typeof data['vin'] === 'string' || data['vin'] instanceof String)) {
            throw new Error("Expected the field `vin` to be a primitive type in the JSON string but got " + data['vin']);
        }

        return true;
    }


}



/**
 * The coverages that apply to just this vehicle.
 * @member {Array.<module:model/VehicleCoverageParameters>} coverages
 */
VehicleCoveragesParameters.prototype['coverages'] = undefined;

/**
 * The VIN these coverages apply to.
 * @member {String} vin
 */
VehicleCoveragesParameters.prototype['vin'] = undefined;






export default VehicleCoveragesParameters;

