/**
 * Root Embedded API
 * APIs available to Root embedded partners
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VehicleParameters model module.
 * @module model/VehicleParameters
 * @version 3.0.0
 */
class VehicleParameters {
    /**
     * Constructs a new <code>VehicleParameters</code>.
     * A single vehicle associated with this quote.
     * @alias module:model/VehicleParameters
     */
    constructor() { 
        
        VehicleParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VehicleParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VehicleParameters} obj Optional instance to populate.
     * @return {module:model/VehicleParameters} The populated <code>VehicleParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleParameters();

            if (data.hasOwnProperty('annualizedMileage')) {
                obj['annualizedMileage'] = ApiClient.convertToType(data['annualizedMileage'], 'Number');
            }
            if (data.hasOwnProperty('antiTheftEquipment')) {
                obj['antiTheftEquipment'] = ApiClient.convertToType(data['antiTheftEquipment'], 'Boolean');
            }
            if (data.hasOwnProperty('commuteDistance')) {
                obj['commuteDistance'] = ApiClient.convertToType(data['commuteDistance'], 'Number');
            }
            if (data.hasOwnProperty('garagingAddress1')) {
                obj['garagingAddress1'] = ApiClient.convertToType(data['garagingAddress1'], 'String');
            }
            if (data.hasOwnProperty('garagingAddress2')) {
                obj['garagingAddress2'] = ApiClient.convertToType(data['garagingAddress2'], 'String');
            }
            if (data.hasOwnProperty('garagingCity')) {
                obj['garagingCity'] = ApiClient.convertToType(data['garagingCity'], 'String');
            }
            if (data.hasOwnProperty('garagingState')) {
                obj['garagingState'] = ApiClient.convertToType(data['garagingState'], 'String');
            }
            if (data.hasOwnProperty('garagingZip')) {
                obj['garagingZip'] = ApiClient.convertToType(data['garagingZip'], 'String');
            }
            if (data.hasOwnProperty('make')) {
                obj['make'] = ApiClient.convertToType(data['make'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('primaryUsage')) {
                obj['primaryUsage'] = ApiClient.convertToType(data['primaryUsage'], 'String');
            }
            if (data.hasOwnProperty('purchaseDate')) {
                obj['purchaseDate'] = ApiClient.convertToType(data['purchaseDate'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('vin')) {
                obj['vin'] = ApiClient.convertToType(data['vin'], 'String');
            }
            if (data.hasOwnProperty('vinEtching')) {
                obj['vinEtching'] = ApiClient.convertToType(data['vinEtching'], 'Boolean');
            }
            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VehicleParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VehicleParameters</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['garagingAddress1'] && !(typeof data['garagingAddress1'] === 'string' || data['garagingAddress1'] instanceof String)) {
            throw new Error("Expected the field `garagingAddress1` to be a primitive type in the JSON string but got " + data['garagingAddress1']);
        }
        // ensure the json data is a string
        if (data['garagingAddress2'] && !(typeof data['garagingAddress2'] === 'string' || data['garagingAddress2'] instanceof String)) {
            throw new Error("Expected the field `garagingAddress2` to be a primitive type in the JSON string but got " + data['garagingAddress2']);
        }
        // ensure the json data is a string
        if (data['garagingCity'] && !(typeof data['garagingCity'] === 'string' || data['garagingCity'] instanceof String)) {
            throw new Error("Expected the field `garagingCity` to be a primitive type in the JSON string but got " + data['garagingCity']);
        }
        // ensure the json data is a string
        if (data['garagingState'] && !(typeof data['garagingState'] === 'string' || data['garagingState'] instanceof String)) {
            throw new Error("Expected the field `garagingState` to be a primitive type in the JSON string but got " + data['garagingState']);
        }
        // ensure the json data is a string
        if (data['garagingZip'] && !(typeof data['garagingZip'] === 'string' || data['garagingZip'] instanceof String)) {
            throw new Error("Expected the field `garagingZip` to be a primitive type in the JSON string but got " + data['garagingZip']);
        }
        // ensure the json data is a string
        if (data['make'] && !(typeof data['make'] === 'string' || data['make'] instanceof String)) {
            throw new Error("Expected the field `make` to be a primitive type in the JSON string but got " + data['make']);
        }
        // ensure the json data is a string
        if (data['model'] && !(typeof data['model'] === 'string' || data['model'] instanceof String)) {
            throw new Error("Expected the field `model` to be a primitive type in the JSON string but got " + data['model']);
        }
        // ensure the json data is a string
        if (data['primaryUsage'] && !(typeof data['primaryUsage'] === 'string' || data['primaryUsage'] instanceof String)) {
            throw new Error("Expected the field `primaryUsage` to be a primitive type in the JSON string but got " + data['primaryUsage']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['vin'] && !(typeof data['vin'] === 'string' || data['vin'] instanceof String)) {
            throw new Error("Expected the field `vin` to be a primitive type in the JSON string but got " + data['vin']);
        }

        return true;
    }


}



/**
 * The distance in miles that this vehicle is expected to be driven in a year.
 * @member {Number} annualizedMileage
 */
VehicleParameters.prototype['annualizedMileage'] = undefined;

/**
 * This vehicle is equipped with anti theft equipment. This may apply a discount.
 * @member {Boolean} antiTheftEquipment
 */
VehicleParameters.prototype['antiTheftEquipment'] = undefined;

/**
 * The distance in miles that this vehicle is driven during your commute.
 * @member {Number} commuteDistance
 */
VehicleParameters.prototype['commuteDistance'] = undefined;

/**
 * The address line 1 of this vehicle's garaging location.
 * @member {String} garagingAddress1
 */
VehicleParameters.prototype['garagingAddress1'] = undefined;

/**
 * The address line 2 of this vehicle's garaging location.
 * @member {String} garagingAddress2
 */
VehicleParameters.prototype['garagingAddress2'] = undefined;

/**
 * The address city of this vehicle's garaging location.
 * @member {String} garagingCity
 */
VehicleParameters.prototype['garagingCity'] = undefined;

/**
 * The address state of this vehicle's garaging location.
 * @member {module:model/VehicleParameters.GaragingStateEnum} garagingState
 */
VehicleParameters.prototype['garagingState'] = undefined;

/**
 * The address ZIP of this vehicle's garaging location.
 * @member {String} garagingZip
 */
VehicleParameters.prototype['garagingZip'] = undefined;

/**
 * The vehicle make.
 * @member {String} make
 */
VehicleParameters.prototype['make'] = undefined;

/**
 * The vehicle model.
 * @member {String} model
 */
VehicleParameters.prototype['model'] = undefined;

/**
 * The primary usage of this vehicle.
 * @member {module:model/VehicleParameters.PrimaryUsageEnum} primaryUsage
 */
VehicleParameters.prototype['primaryUsage'] = undefined;

/**
 * The date this vehicle was purchased in ISO 8601 full-date format. See rfc 3339 section 5.6: https://www.rfc-editor.org/rfc/rfc3339#section-5.6
 * @member {Date} purchaseDate
 */
VehicleParameters.prototype['purchaseDate'] = undefined;

/**
 * The status of the vehicle for this policy.
 * @member {module:model/VehicleParameters.StatusEnum} status
 */
VehicleParameters.prototype['status'] = undefined;

/**
 * The vehicle identification number.
 * @member {String} vin
 */
VehicleParameters.prototype['vin'] = undefined;

/**
 * The VIN is etched into the vehicle windows. This may apply a discount.
 * @member {Boolean} vinEtching
 */
VehicleParameters.prototype['vinEtching'] = undefined;

/**
 * The vehicle model year.
 * @member {Number} year
 */
VehicleParameters.prototype['year'] = undefined;





/**
 * Allowed values for the <code>garagingState</code> property.
 * @enum {String}
 * @readonly
 */
VehicleParameters['GaragingStateEnum'] = {

    /**
     * value: "AK"
     * @const
     */
    "AK": "AK",

    /**
     * value: "AL"
     * @const
     */
    "AL": "AL",

    /**
     * value: "AR"
     * @const
     */
    "AR": "AR",

    /**
     * value: "AZ"
     * @const
     */
    "AZ": "AZ",

    /**
     * value: "CA"
     * @const
     */
    "CA": "CA",

    /**
     * value: "CO"
     * @const
     */
    "CO": "CO",

    /**
     * value: "CT"
     * @const
     */
    "CT": "CT",

    /**
     * value: "DC"
     * @const
     */
    "DC": "DC",

    /**
     * value: "DE"
     * @const
     */
    "DE": "DE",

    /**
     * value: "FL"
     * @const
     */
    "FL": "FL",

    /**
     * value: "GA"
     * @const
     */
    "GA": "GA",

    /**
     * value: "HI"
     * @const
     */
    "HI": "HI",

    /**
     * value: "IA"
     * @const
     */
    "IA": "IA",

    /**
     * value: "ID"
     * @const
     */
    "ID": "ID",

    /**
     * value: "IL"
     * @const
     */
    "IL": "IL",

    /**
     * value: "IN"
     * @const
     */
    "IN": "IN",

    /**
     * value: "KS"
     * @const
     */
    "KS": "KS",

    /**
     * value: "KY"
     * @const
     */
    "KY": "KY",

    /**
     * value: "LA"
     * @const
     */
    "LA": "LA",

    /**
     * value: "MA"
     * @const
     */
    "MA": "MA",

    /**
     * value: "MD"
     * @const
     */
    "MD": "MD",

    /**
     * value: "ME"
     * @const
     */
    "ME": "ME",

    /**
     * value: "MI"
     * @const
     */
    "MI": "MI",

    /**
     * value: "MN"
     * @const
     */
    "MN": "MN",

    /**
     * value: "MO"
     * @const
     */
    "MO": "MO",

    /**
     * value: "MS"
     * @const
     */
    "MS": "MS",

    /**
     * value: "MT"
     * @const
     */
    "MT": "MT",

    /**
     * value: "NC"
     * @const
     */
    "NC": "NC",

    /**
     * value: "ND"
     * @const
     */
    "ND": "ND",

    /**
     * value: "NE"
     * @const
     */
    "NE": "NE",

    /**
     * value: "NH"
     * @const
     */
    "NH": "NH",

    /**
     * value: "NJ"
     * @const
     */
    "NJ": "NJ",

    /**
     * value: "NM"
     * @const
     */
    "NM": "NM",

    /**
     * value: "NV"
     * @const
     */
    "NV": "NV",

    /**
     * value: "NY"
     * @const
     */
    "NY": "NY",

    /**
     * value: "OH"
     * @const
     */
    "OH": "OH",

    /**
     * value: "OK"
     * @const
     */
    "OK": "OK",

    /**
     * value: "OR"
     * @const
     */
    "OR": "OR",

    /**
     * value: "PA"
     * @const
     */
    "PA": "PA",

    /**
     * value: "RI"
     * @const
     */
    "RI": "RI",

    /**
     * value: "SC"
     * @const
     */
    "SC": "SC",

    /**
     * value: "SD"
     * @const
     */
    "SD": "SD",

    /**
     * value: "TN"
     * @const
     */
    "TN": "TN",

    /**
     * value: "TX"
     * @const
     */
    "TX": "TX",

    /**
     * value: "UT"
     * @const
     */
    "UT": "UT",

    /**
     * value: "VA"
     * @const
     */
    "VA": "VA",

    /**
     * value: "VT"
     * @const
     */
    "VT": "VT",

    /**
     * value: "WA"
     * @const
     */
    "WA": "WA",

    /**
     * value: "WI"
     * @const
     */
    "WI": "WI",

    /**
     * value: "WV"
     * @const
     */
    "WV": "WV",

    /**
     * value: "WY"
     * @const
     */
    "WY": "WY"
};


/**
 * Allowed values for the <code>primaryUsage</code> property.
 * @enum {String}
 * @readonly
 */
VehicleParameters['PrimaryUsageEnum'] = {

    /**
     * value: "business"
     * @const
     */
    "business": "business",

    /**
     * value: "commute"
     * @const
     */
    "commute": "commute",

    /**
     * value: "farm"
     * @const
     */
    "farm": "farm",

    /**
     * value: "pleasure"
     * @const
     */
    "pleasure": "pleasure",

    /**
     * value: "occasional"
     * @const
     */
    "occasional": "occasional",

    /**
     * value: "rideshare"
     * @const
     */
    "rideshare": "rideshare",

    /**
     * value: "work"
     * @const
     */
    "work": "work"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
VehicleParameters['StatusEnum'] = {

    /**
     * value: "Covered"
     * @const
     */
    "Covered": "Covered",

    /**
     * value: "Excluded"
     * @const
     */
    "Excluded": "Excluded"
};



export default VehicleParameters;

